In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_rows',7000)
pd.set_option('display.max_columns',2000)

In [2]:
kcensus = pd.read_csv('kobo_data.csv')
tcensus = pd.read_csv('tamma_data.csv')
kcensus['How many FEMALE students  above AGE 8 YEARS OLD are in Pre-Kindergarten?'][3776]= 10
kcensus['How many FEMALE students  above AGE 8 YEARS OLD are in Pre-Kindergarten?'][3776]

/home/alton/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (5,6,10,11,648,745,746,753,772,773,796,801,806,811,816,821,826,831,836,841,846,851,856,861,866,871,876,881,886,891,896,901,902,903,904,974,1197,1222,1241,1250,1261,1269,1299,1399,1401,1403,1405,1408,1409,1413,1414,1415,1419,1421,1423,1425,1427,1429,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1452) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/home/alton/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (2,12,13,14,115,893,995,1019,1020,1021,1022,1023) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
<ipython-input-2-8fec5fc5cfc6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kcensus['How many FEMALE students  above AGE 8 YEARS OLD are in Pre-Kindergarten?'][3776]= 10

10.0

In [3]:
kstaff = pd.read_csv('kobo_staff.csv')
tstaff = pd.read_csv('tamma_staff.csv')

In [4]:
kece_student =kcensus.iloc[:,692:734]
kece_student.head()

,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age less than 10 enrolled in Level I of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level II of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are FE MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are FEMALES?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
kece_age = kcensus.iloc[:,692:734]
kece_age.head()

,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age less than 10 enrolled in Level I of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level II of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are FE MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are FEMALES?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
kece_studentg = kcensus.iloc[:,686:692]
kece_studentg.head()

,How many students enrolled in Level I of Alternative Education are MALES?,How many students enrolled in Level II of Alternative Education are MALES?,How many students enrolled in Level III of Alternative Education are MALES?,How many students enrolled in Level I of Alternative Education are FEMALES?,How many students enrolled in Level II of Alternative Education are FEMALES?,How many students enrolled in Level III of Alternative Education are FEMALES?
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#kece_student_dic = pd.Series(kece_student.columns)
#kece_student_dic.to_csv('kece_student_dic.csv', index = False)

# Table 1: ALP Enrollment by Ownership and Gender

In [8]:
kece_c = kcensus.iloc[:,[2]]
kece_o = kcensus.iloc[:,[39]]
kece_s = kcensus.iloc[:,692:734]
kece_g =  kcensus.iloc[:,686:692]
kece_s.head()

,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age less than 10 enrolled in Level I of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level II of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are FE MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are FEMALES?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
kece_og = pd.concat([kece_o, kece_s],axis=1).groupby('Type of school').sum()
kece_ogs = kece_og#.sum(1)
kece_ogs

,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age less than 10 enrolled in Level I of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level II of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are FE MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are FEMALES?
Type of school,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Community,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,2.0,0.0,0.0,1.0,1.0,5.0,1.0,2.0,16.0,6.0,1.0,6.0,4.0,1.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Faith-based,19.0,10.0,6.0,20.0,11.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
Private,66.0,22.0,10.0,93.0,24.0,15.0,89.0,131.0,101.0,89.0,142.0,94.0,3.0,99.0,83.0,42.0,154.0,61.0,0.0,0.0,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Public,568.0,203.0,21.0,642.0,179.0,41.0,1250.0,760.0,178.0,1117.0,612.0,160.0,286.0,230.0,103.0,243.0,226.0,96.0,45.0,47.0,36.0,36.0,19.0,38.0,37.0,21.0,26.0,18.0,11.0,20.0,12.0,13.0,6.0,27.0,10.0,9.0,9.0,5.0,6.0,13.0,10.0,7.0

In [10]:
kece_ogm  = pd.concat([kece_ogs.iloc[:,:3],
kece_ogs.iloc[:,6:9],
kece_ogs.iloc[:,12:15],
kece_ogs.iloc[:,18:21],
kece_ogs.iloc[:,24:27],
kece_ogs.iloc[:,30:33],
kece_ogs.iloc[:,36:39]], axis=1).sum(1)
kece_ogm

Type of school
Community        27.0
Faith-based      35.0
Private         610.0
Public         3862.0
dtype: float64

In [11]:
kece_ogf = kece_ogs.sum(1) - kece_ogm
kece_ogf

Type of school
Community        27.0
Faith-based      40.0
Private         716.0
Public         3534.0
dtype: float64

# Table 2: ALP Enrollment by Grade and Gender

In [12]:
kece_gg = kece_og.sum()
kece_gg#.sum()

How many students age less than 10 enrolled in Level I of Alternative Education  are MALES?             653.0
How many students age less than 10 enrolled in Level II of Alternative Education  are MALES?            235.0
How many students age less than 10 enrolled in Level III of Alternative Education  are MALES?            37.0
How many students age less than 10 enrolled in Level I of Alternative Education  are FEMALES?           755.0
How many students age less than 10 enrolled in Level II of Alternative Education  are FEMALES?          214.0
How many students age less than 10 enrolled in Level III of Alternative Education  are FEMALES?          63.0
How many students age between 10 to 15  enrolled in Level I of Alternative Education  are MALES?       1339.0
How many students age between 10 to 15  enrolled in Level II of Alternative Education  are MALES?       892.0
How many students age between 10 to 15  enrolled in Level III of Alternative Education  are MALES?      279.0
How many students age between 10 to 15 enrolled in Level I of Alternative Education  are FEMALES?      1206.0
How many students age between 10 to 15 enrolled in Level II of Alternative Education  are FEMALES?      754.0
How many students age between 10 to 15 enrolled in Level III of Alternative Education  are FEMALES?     254.0
How many students age between 15 to 20 enrolled in Level I of Alternative Education  are MALES?         289.0
How many students age between 15 to 20 enrolled in Level II of Alternative Education  are MALES?        330.0
How many students age between 15 to 20 enrolled in Level III of Alternative Education  are MALES?       186.0
How many students age between 15 to 20 enrolled in Level I of Alternative Education  are FEMALES?       287.0
How many students age between 15 to 20 enrolled in Level II of Alternative Education  are FEMALES?      382.0
How many students age between 15 to 20 enrolled in Level III of Alternative Education  are FEMALES?     157.0
How many students age between 20 to 25 enrolled in Level I of Alternative Education  are MALES?          45.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?         48.0
How many students age between 20 to 25 enrolled in Level III of Alternative Education  are MALES?        43.0
How many students age between 20 to 25 enrolled in Level I of Alternative Education  are FEMALES?        43.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are FEMALES?       20.0
How many students age between 20 to 25 enrolled in Level III of Alternative Education  are FEMALES?      40.0
How many students age between 25 to 30 enrolled in Level I of Alternative Education  are MALES?          53.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?.1       27.0
How many students age between 25 to 30 enrolled in Level III of Alternative Education  are MALES?        27.0
How many students age between 25 to 30 enrolled in Level I of Alternative Education  are FEMALES?        24.0
How many students age between 25 to 30 enrolled in Level II of Alternative Education  are FEMALES?       15.0
How many students age between 25 to 30 enrolled in Level III of Alternative Education  are FEMALES?      21.0
How many students age between 30 to 35 enrolled in Level I of Alternative Education  are MALES?          12.0
How many students age between 30 to 35 enrolled in Level II of Alternative Education  are MALES?         13.0
How many students age between 30 to 35 enrolled in Level III of Alternative Education  are MALES?         6.0
How many students age between 30 to 35 enrolled in Level I of Alternative Education  are FEMALES?        31.0
How many students age between 30 to 35 enrolled in Level II of Alternative Education  are FE MALES?      10.0
How many students age between 30 to 35 enrolled in Level III of Alternative Education  are FEMALES?      11.0
How many students age greater than  35 enrolled in Level I of Alternative Education  are MALES?           9.0
How many students age greater than  35 enrolled in Level II of Alternative Education  are MALES?          5.0
How many students age greater than  35 enrolled in Level III of Alternative Education  are MALES?         6.0
How many students age greater than  35 enrolled in Level I of Alternative Education  are FEMALES?        13.0
How many students age greater than  35 enrolled in Level II of Alternative Education  are FEMALES?       10.0
How many students age greater than  35 enrolled in Level III of Alternative Education  are FEMALES?       7.0
dtype: float64

In [13]:
kece_gg1 = kece_gg[::3]
kece_gg1.sum()

4759.0

In [14]:
kece_gg1[::2].sum()

2400.0

In [15]:
kece_gg2 = kece_gg[1::3]
kece_gg2.sum()

2955.0

In [16]:
kece_gg2[::2].sum()

1550.0

In [17]:
kece_gg3  =kece_gg[2::3]
kece_gg3.sum()

1137.0

In [18]:
kece_gg3[::2].sum()

584.0

In [19]:
kece_gg10 = kece_gg[::3]
kece_gg10.sum()

4759.0

In [20]:
kece_gg10m = kece_gg10[::2]
kece_gg10m.sum()

2400.0

In [21]:
kece_gg10f = kece_gg10[1::2]
kece_gg10f .sum()

2359.0

In [22]:
kece_gg11 =kece_gg[1::3]
kece_gg11.sum()

2955.0

In [23]:
kece_gg11m =kece_gg11[::2]
kece_gg11m.sum()

1550.0

In [24]:
kece_gg11f =kece_gg11[1::2]
kece_gg11f.sum()

1405.0

In [25]:
kece_gg12 = kece_gg[2::3]
kece_gg12.sum()

1137.0

In [26]:
kece_gg12m = kece_gg12[::2]
kece_gg12m.sum()

584.0

In [27]:
kece_gg12f = kece_gg12[1::2]
kece_gg12f.sum()

553.0

# Table 3: Number of ALP Students by County and Grade

In [28]:
kece_cos = pd.concat([kece_c, kece_o, kece_s], axis = 1).groupby(['County']).sum()
kece_cos.sum(1)

County
Bomi                   0.0
Bong                1179.0
Gbarpolu              39.0
Grand Bassa          701.0
Grand Cape Mount       0.0
Grand Gedeh            0.0
Grand Kru              0.0
Lofa                 831.0
Margibi              808.0
Maryland               0.0
Montserrado 1       1131.0
Montserrado 2        974.0
Nimba               3188.0
River Gee              0.0
Rivercess              0.0
Sinoe                  0.0
dtype: float64

In [29]:
kece_cos1 = kece_cos.iloc[:,::3]
kece_cos1.sum(1)#.sum()

County
Bomi                   0.0
Bong                 781.0
Gbarpolu              39.0
Grand Bassa          436.0
Grand Cape Mount       0.0
Grand Gedeh            0.0
Grand Kru              0.0
Lofa                 385.0
Margibi              473.0
Maryland               0.0
Montserrado 1        361.0
Montserrado 2        450.0
Nimba               1834.0
River Gee              0.0
Rivercess              0.0
Sinoe                  0.0
dtype: float64

In [30]:
kece_cos2 =kece_cos.iloc[:,1::3]
kece_cos2.sum(1)#.sum()

County
Bomi                   0.0
Bong                 346.0
Gbarpolu               0.0
Grand Bassa          189.0
Grand Cape Mount       0.0
Grand Gedeh            0.0
Grand Kru              0.0
Lofa                 315.0
Margibi              273.0
Maryland               0.0
Montserrado 1        491.0
Montserrado 2        310.0
Nimba               1031.0
River Gee              0.0
Rivercess              0.0
Sinoe                  0.0
dtype: float64

In [31]:
kece_cos3 = kece_cos.iloc[:,2::3]
kece_cos3.sum(1)#.sum()

County
Bomi                  0.0
Bong                 52.0
Gbarpolu              0.0
Grand Bassa          76.0
Grand Cape Mount      0.0
Grand Gedeh           0.0
Grand Kru             0.0
Lofa                131.0
Margibi              62.0
Maryland              0.0
Montserrado 1       279.0
Montserrado 2       214.0
Nimba               323.0
River Gee             0.0
Rivercess             0.0
Sinoe                 0.0
dtype: float64

# Table 4: ALP Students by County and Gender

In [32]:
kece_cg = pd.concat([kece_c, kece_s], axis = 1).groupby(['County']).sum()
kece_cg.sum(1)#.sum()

County
Bomi                   0.0
Bong                1179.0
Gbarpolu              39.0
Grand Bassa          701.0
Grand Cape Mount       0.0
Grand Gedeh            0.0
Grand Kru              0.0
Lofa                 831.0
Margibi              808.0
Maryland               0.0
Montserrado 1       1131.0
Montserrado 2        974.0
Nimba               3188.0
River Gee              0.0
Rivercess              0.0
Sinoe                  0.0
dtype: float64

In [33]:
kece_cg#.iloc[:,:3].sum(1)

,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age less than 10 enrolled in Level I of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level II of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are FE MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are FEMALES?
County,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Bomi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bong,105.0,82.0,10.0,175.0,45.0,11.0,233.0,111.0,15.0,160.0,77.0,15.0,60.0,14.0,0.0,40.0,17.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gbarpolu,14.0,0.0,0.0,18.0,0.0,0.0,5.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Bassa,30.0,10.0,1.0,59.0,4.0,9.0,136.0,51.0,14.0,138.0,51.0,14.0,43.0,35.0,11.0,28.0,32.0,13.0,2.0,4.0,8.0,0.0,2.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Cape Mount,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Gedeh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Kru,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lofa,42.0,17.0,0.0,27.0,24.0,0.0,82.0,91.0,30.0,87.0,49.0,15.0,45.0,38.0,27.0,39.0,44.0,26.0,21.0,17.0,5.0,13.0,11.0,8.0,16.0,9.0,6.0,7.0,10.0,6.0,0.0,0.0,1.0,6.0,5.0,4.0,0.0,0.0,1.0,0.0,0.0,2.0
Margibi,77.0,26.0,1.0,62.0,30.0,1.0,173.0,110.0,30.0,109.0,55.0,15.0,13.0,25.0,9.0,23.0,19.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0
Maryland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Montserrado 1,69.0,23.0,16.0,86.0,33.0,22.0,71.0,87.0,57.0,54.0,84.0,69.0,8.0,81.0,24.0,3.0,135.0,46.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,18.0,16.0,10.0,5.0,9.0,12.0,5.0,5.0,25.0,5.0,5.0,9.0,5.0,5.0,5.0,10.0,5.0
Montserrado 2,39.0,19.0,0.0,66.0,15.0,0.0,102.0,96.0,48.0,110.0,86.0,30.0,40.0,47.0,79.0,82.0,46.0,21.0,1.0,1.0,19.0,10.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
Nimba,277.0,58.0,9.0,262.0,63.0,20.0,537.0,346.0,85.0,546.0,352.0,96.0,80.0,90.0,36.0,72.0,89.0,44.0,21.0,26.0,11.0,20.0,7.0,12.0,12.0,0.0,5.0,7.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
River Gee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Rivercess,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sinoe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
pd.concat([kece_cg.iloc[:,:3],
kece_cg.iloc[:,6:9],
kece_cg.iloc[:,12:15],
kece_cg.iloc[:,18:21],
kece_cg.iloc[:,24:27],
kece_cg.iloc[:,30:33],
kece_cg.iloc[:,36:39]], axis=1)#.sum(1)

,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?
County,,,,,,,,,,,,,,,,,,,,,
Bomi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bong,105.0,82.0,10.0,233.0,111.0,15.0,60.0,14.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gbarpolu,14.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Bassa,30.0,10.0,1.0,136.0,51.0,14.0,43.0,35.0,11.0,2.0,4.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Cape Mount,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Gedeh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Kru,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lofa,42.0,17.0,0.0,82.0,91.0,30.0,45.0,38.0,27.0,21.0,17.0,5.0,16.0,9.0,6.0,0.0,0.0,1.0,0.0,0.0,1.0
Margibi,77.0,26.0,1.0,173.0,110.0,30.0,13.0,25.0,9.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0
Maryland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Montserrado 1,69.0,23.0,16.0,71.0,87.0,57.0,8.0,81.0,24.0,0.0,0.0,0.0,9.0,18.0,16.0,12.0,5.0,5.0,9.0,5.0,5.0
Montserrado 2,39.0,19.0,0.0,102.0,96.0,48.0,40.0,47.0,79.0,1.0,1.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Nimba,277.0,58.0,9.0,537.0,346.0,85.0,80.0,90.0,36.0,21.0,26.0,11.0,12.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
River Gee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Rivercess,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sinoe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
kece_cg.iloc[:,3:].sum(1)

County
Bomi                   0.0
Bong                 982.0
Gbarpolu              25.0
Grand Bassa          660.0
Grand Cape Mount       0.0
Grand Gedeh            0.0
Grand Kru              0.0
Lofa                 772.0
Margibi              704.0
Maryland               0.0
Montserrado 1       1023.0
Montserrado 2        916.0
Nimba               2844.0
River Gee              0.0
Rivercess              0.0
Sinoe                  0.0
dtype: float64

In [36]:
kece_cgm = pd.concat([kece_cg.iloc[:,0:3],
kece_cg.iloc[:,6:9],
kece_cg.iloc[:,12:15],
kece_cg.iloc[:,18:21],
kece_cg.iloc[:,24:27],
kece_cg.iloc[:,30:33],
kece_cg.iloc[:,36:39],
kece_cg.iloc[:,42:45],
kece_cg.iloc[:,48:51],
kece_cg.iloc[:,54:57],
kece_cg.iloc[:,60:63]],axis=1)
kece_cgm##.sum(1)#.sum()

,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?
County,,,,,,,,,,,,,,,,,,,,,
Bomi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bong,105.0,82.0,10.0,233.0,111.0,15.0,60.0,14.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gbarpolu,14.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Bassa,30.0,10.0,1.0,136.0,51.0,14.0,43.0,35.0,11.0,2.0,4.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Cape Mount,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Gedeh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Kru,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lofa,42.0,17.0,0.0,82.0,91.0,30.0,45.0,38.0,27.0,21.0,17.0,5.0,16.0,9.0,6.0,0.0,0.0,1.0,0.0,0.0,1.0
Margibi,77.0,26.0,1.0,173.0,110.0,30.0,13.0,25.0,9.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0
Maryland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Montserrado 1,69.0,23.0,16.0,71.0,87.0,57.0,8.0,81.0,24.0,0.0,0.0,0.0,9.0,18.0,16.0,12.0,5.0,5.0,9.0,5.0,5.0
Montserrado 2,39.0,19.0,0.0,102.0,96.0,48.0,40.0,47.0,79.0,1.0,1.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Nimba,277.0,58.0,9.0,537.0,346.0,85.0,80.0,90.0,36.0,21.0,26.0,11.0,12.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
River Gee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Rivercess,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sinoe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
kece_cgf = kece_cg.sum(1)-kece_cgm.sum(1)
kece_cgf

County
Bomi                   0.0
Bong                 541.0
Gbarpolu              20.0
Grand Bassa          356.0
Grand Cape Mount       0.0
Grand Gedeh            0.0
Grand Kru              0.0
Lofa                 383.0
Margibi              328.0
Maryland               0.0
Montserrado 1        611.0
Montserrado 2        483.0
Nimba               1595.0
River Gee              0.0
Rivercess              0.0
Sinoe                  0.0
dtype: float64

# Table 5: ALP Enrollment by County and Ownership

In [38]:
pd.concat([kece_c, kece_o, kece_s], axis = 1).groupby(['County', 'Type of school']).sum().sum(1)

County            Type of school
Bomi              Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public               0.0
Bong              Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public            1179.0
Gbarpolu          Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public              39.0
Grand Bassa       Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public             701.0
Grand Cape Mount  Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public               0.0
Grand Gedeh       Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public               0.0
Grand Kru         Faith-based          0.0
                  Private              0.0
                  Public               0.0
Lofa              Community           42.0
                  Faith-based          0.0
                  Private              0.0
                  Public             789.0
Margibi           Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public             808.0
Maryland          Private              0.0
                  Public               0.0
Montserrado 1     Community            0.0
                  Faith-based         73.0
                  Private            831.0
                  Public             227.0
Montserrado 2     Community            0.0
                  Faith-based          2.0
                  Private            495.0
                  Public             477.0
Nimba             Community           12.0
                  Faith-based          0.0
                  Private              0.0
                  Public            3176.0
River Gee         Faith-based          0.0
                  Private              0.0
                  Public               0.0
Rivercess         Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public               0.0
Sinoe             Community            0.0
                  Faith-based          0.0
                  Private              0.0
                  Public               0.0
dtype: float64

# Table 6: ALP Enrollment by District and Gender

In [39]:
kece_c = kcensus.iloc[:,[2]]
kece_d = kcensus.iloc[:,3:19]
kece_s.head()

,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age less than 10 enrolled in Level I of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level II of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are FE MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are FEMALES?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
kece_cds = pd.concat([kece_c, kece_d, kece_s], axis = 1)
kece_cds.columns

Index(['County', 'District in Bong County', 'District in Gbarpolu',
       'District in River Gee', 'District in Sinoe', 'District in Lofa',
       'District in Nimba', 'District in Grand Cape Mount',
       'District in Maryland', 'District in Margibi', 'District in Bomi',
       'District in Grand Bassa', 'District in Montserrado 2',
       'District in Montserrado 1', 'Districts in Grand Kru',
       'Districts in Grand Gedeh', 'Districts in River Cess',
       'How many students age less than 10 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age less than 10 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age less than 10 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15  enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 10 to 15  enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 10 to 15  enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 10 to 15 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?.1',
       'How many students age between 25 to 30 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 25 to 30 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 30 to 35 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 30 to 35 enrolled in Level II of Alternative Education  are FE MALES?',
       'How many students age between 30 to 35 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level III of Alternative Education  are FEMALES?'],
      dtype='object')

In [41]:
kece_melt =kece_cds.melt(id_vars=['County',
         'How many students age less than 10 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age less than 10 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age less than 10 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15  enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 10 to 15  enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 10 to 15  enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 10 to 15 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?.1',
       'How many students age between 25 to 30 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 25 to 30 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 30 to 35 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 30 to 35 enrolled in Level II of Alternative Education  are FE MALES?',
       'How many students age between 30 to 35 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level III of Alternative Education  are FEMALES?'],var_name = 'district',value_name='count')
kece_melt.head()

,County,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age less than 10 enrolled in Level I of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level II of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are FE MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are FEMALES?,district,count
0,Rivercess,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
1,Nimba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
2,River Gee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
3,Montserrado 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
4,Montserrado 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN

## Districts in Bomi County

In [42]:
k_s = kece_melt[(kece_melt['district']== 'District in Bomi') & (kece_melt['count']== 'Senji')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bomi') & (kece_melt['count']== 'Dewoin')].sum()
#k_s = kece_melt[(kece_melt['district']== 'District in Bomi') & (kece_melt['count']== 'Klay')].sum()
#k_s = kece_melt[(kece_melt['district']== 'District in Bomi') & (kece_melt['count']== 'Suehn-Mecca')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [43]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am .sum()

0.0

In [44]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in Bong County

In [45]:
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Gbarnga 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Gbarnga 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Zota')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Salala')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Fuamah')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Suakoko')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Sanoyea')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Panta-Kpaai')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Kokoyah')].sum()

k_a = k_s[1:-2]
k_a.sum()

769.0

In [46]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

395.0

In [47]:
k_af = k_a.sum() - k_am.sum()
k_af

374.0

## Districts in Gbarpolu

In [48]:
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Gorwalali')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Bopolu')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Gbarma')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Belle')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Bokomu')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Kongba')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [49]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [50]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in Grand Bassa

In [51]:
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 5')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 5B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 3A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 3B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 4')].sum()
k_a = k_s[1:-2]
k_a.sum()

42.0

In [52]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

24.0

In [53]:
k_af = k_a.sum() - k_am.sum()
k_af

18.0

## Districts in Grand Cape Mount

In [54]:
k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Tewor')].sum()
#k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Gola Konneh')].sum()
#k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Porkpa')].sum()
#k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Garwular')].sum()
#k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Tallah Tombay')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [55]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [56]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in Grand Gedeh

In [57]:
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Konobo')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Putu')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Gbarzon')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Tchien')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Cavalla')].sum()
k_a = k_s[1:-2]
k_a.sum()

0.0

In [58]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [59]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in Grand Kru

In [60]:
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Barclayville')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Trehn')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Buah')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Grand Cess')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Dorbor')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Jloh')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Sass Town')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Wedabo')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [61]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [62]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in Lofa

In [63]:
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Foya')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Kolahun 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Kolahun 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Salayea')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Vahun')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Voinjama')].sum()#
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Zorzor')].sum()

k_a = k_s[1:-2]
k_a.sum()

161.0

In [64]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

84.0

In [65]:
k_af = k_a.sum() - k_am.sum()
k_af

77.0

## Districts in Margibi

In [66]:
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Marshall')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Farmington')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Mama kaba')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Gibi')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Kakata 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Kakata 2')].sum()

k_a = k_s[1:-2]
k_a.sum()

97.0

In [67]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

59.0

In [68]:
k_af = k_a.sum() - k_am.sum()
k_af

38.0

## Districts in Maryland

In [69]:
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Harper 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Harper 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Barrobo 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Barrobo 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Sodoken')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Karleway 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Karleway 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Pleebo')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [70]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [71]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in Montserrado 1

In [72]:
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 3')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 4')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 5')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 6')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1C')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1D')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1E')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 2A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 2B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 2C')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 2D')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [73]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [74]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in Montserrado 2

In [75]:
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left Bank 1A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left bank 1B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left bank  1C')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left Bank 1D')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left Bank 2A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left bank 2B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Careysburg')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Todee')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Right Bank 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Right Bank 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Right Bank 3')].sum()

k_a = k_s[1:-2]
k_a.sum()

111.0

In [76]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

73.0

In [77]:
k_af = k_a.sum() - k_am.sum()
k_af

38.0

## Districts in Nimba

In [78]:
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Tappita 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Tappita 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Saclepea 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Sanniquellie Mah')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Zoe-Geh')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Tuwah River')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Gbelay-Geh')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Yarpea Mah')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Yarwein Mensonoh')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Buuyao')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Bain-Garr 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Bain- Garr 2')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [79]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [80]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in River Gee

In [81]:
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Sarbo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Tienpo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Chedepo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Putupo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Gbeapo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Webbo')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [82]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [83]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in River Cess

In [84]:
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Timobo')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Central Rivercess 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Central Rivercess 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Morwah')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Yarnee')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [85]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [86]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

## Districts in Sinoe

In [87]:
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Upper Kpanyan')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Juarzon')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Lower Kpanyan')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Butaw')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Tarjuwon')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Jeadea')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Sanquin')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Greenville')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Central Kpanyan')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [88]:
k_am = pd.concat([k_a[0:3],
k_a[6:9],
k_a[12:15],
k_a[18:21],
k_a[24:27],
k_a[30:33],
k_a[36:39],
k_a[42:45],
k_a[48:51],
k_a[54:57],
k_a[60:63]])
k_am.sum()

0.0

In [89]:
k_af = k_a.sum() - k_am.sum()
k_af

0.0

# Table 7: Enrollment by District and Grade

In [90]:
#kece_cds.columns

In [91]:
#pd.set_option('display.max_rows',2000)

#kece_cds['District in Nimba'].dropna() #[kece_cds['District in Montserrado 2']=='Left Bank 1B']

## Districts in Bomi County

In [92]:
k_s = kece_melt[(kece_melt['district']== 'District in Bomi') & (kece_melt['count']== 'Senji')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bomi') & (kece_melt['count']== 'Dewoin')].sum()
#k_s = kece_melt[(kece_melt['district']== 'District in Bomi') & (kece_melt['count']== 'Klay')].sum()
#k_s = kece_melt[(kece_melt['district']== 'District in Bomi') & (kece_melt['count']== 'Suehn-Mecca')].sum()
#k_a = k_s[1:-2]
k_a.sum()

0.0

In [93]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [94]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [95]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in Bong County

In [96]:
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Gbarnga 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Gbarnga 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Zota')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Salala')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Fuamah')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Suakoko')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Sanoyea')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Panta-Kpaai')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Bong County') & (kece_melt['count']== 'Kokoyah')].sum()
k_a = k_s[1:-2]
k_a.sum()

769.0

In [97]:
k_a1 =k_a[::3].sum()
k_a1.sum()

514.0

In [98]:
k_a2 =k_a[1::3].sum()
k_a2.sum()

235.0

In [99]:
k_a3 =k_a[2::3].sum()
k_a3.sum()

20.0

## Districts in Gbarpolu

In [100]:
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Gorwalali')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Bopolu')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Gbarma')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Belle')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Bokomu')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Kongba')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [101]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [102]:
k_a2 =k_a[1::3].sum()
k_a2.sum()

0.0

In [103]:
k_a3 =k_a[2::3].sum()
k_a3.sum()

0.0

## Districts in Grand Bassa

In [104]:
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 5')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 5B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 3A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 3B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Bassa') & (kece_melt['count']== 'District 4')].sum()
k_a = k_s[1:-2]
k_a.sum()

42.0

In [105]:
k_a1 =k_a[::3].sum()
k_a1.sum()

7.0

In [106]:
k_a2 =k_a[1::3].sum()
k_a2.sum()

14.0

In [107]:
k_a3 =k_a[2::3].sum()
k_a3.sum()

21.0

## Districts in Grand Cape Mount

In [108]:
k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Tewor')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Gola Konneh')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Porkpa')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Garwular')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Grand Cape Mount') & (kece_melt['count']== 'Tallah Tombay')].sum()
k_a = k_s[1:-2]
k_a.sum()

0.0

In [109]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [110]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [111]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in Grand Gedeh

In [112]:
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Konobo')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Putu')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Gbarzon')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Tchien')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Gedeh') & (kece_melt['count']== 'Cavalla')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [113]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [114]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [115]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in Grand Kru

In [116]:
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Barclayville')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Trehn')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Buah')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Grand Cess')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Dorbor')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Jloh')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Sass Town')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in Grand Kru') & (kece_melt['count']== 'Wedabo')].sum()

k_a = k_s[1:-2]
k_a.sum()

0.0

In [117]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [118]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [119]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in Lofa

In [120]:
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Foya')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Kolahun 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Kolahun 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Salayea')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Vahun')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Voinjama')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Lofa') & (kece_melt['count']== 'Zorzor')].sum()
k_a = k_s[1:-2]
k_a.sum()

161.0

In [121]:
k_a1 =k_a[::3].sum()
k_a1.sum()

64.0

In [122]:
k_a2 =k_a[1::3].sum()
k_a2

73.0

In [123]:
k_a3 =k_a[2::3].sum()
k_a3

24.0

## Districts in Margibi

In [124]:
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Marshall')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Farmington')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Mama kaba')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Gibi')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Kakata 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Margibi') & (kece_melt['count']== 'Kakata 2')].sum()
k_a = k_s[1:-2]
k_a.sum()

97.0

In [125]:
k_a1 =k_a[::3].sum()
k_a1.sum()

70.0

In [126]:
k_a2 =k_a[1::3].sum()
k_a2

27.0

In [127]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in Maryland

In [128]:
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Harper 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Harper 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Barrobo 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Barrobo 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Sodoken')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Karleway 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Karleway 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Maryland') & (kece_melt['count']== 'Pleebo')].sum()
k_a = k_s[1:-2]
k_a.sum()

0.0

In [129]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [130]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [131]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in Montserrado 1

In [132]:
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 3')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 4')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 5')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 6')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1C')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1D')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 1E')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 2A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 2B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 2C')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Greater Monrovia 2D')].sum()
k_a = k_s[1:-2]
k_a.sum()

0.0

In [133]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [134]:
k_a2 =k_a[1::3].sum()
k_a2.sum()

0.0

In [135]:
k_a3 =k_a[2::3].sum()
k_a3.sum()

0.0

## Districts in Montserrado 2

In [136]:
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left Bank 1A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left bank 1B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left bank  1C')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left Bank 1D')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left Bank 2A')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Left bank 2B')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Careysburg')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Todee')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Right Bank 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Right Bank 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Montserrado 2') & (kece_melt['count']== 'Right Bank 3')].sum()
k_a = k_s[1:-2]
k_a.sum()

111.0

In [137]:
k_a1 =k_a[::3].sum()
k_a1.sum()

75.0

In [138]:
k_a2 =k_a[1::3].sum()
k_a2

36.0

In [139]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in Nimba

In [140]:
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Tappita 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Tappita 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Saclepea 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Sanniquellie Mah')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Zoe-Geh')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Tuwah River')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Gbelay-Geh')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Yarpea Mah')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Yarwein Mensonoh')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Buuyao')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Bain-Garr 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Nimba') & (kece_melt['count']== 'Bain- Garr 2')].sum()
k_a = k_s[1:-2]
k_a.sum()

0.0

In [141]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [142]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [143]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in River Gee

In [144]:
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Sarbo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Tienpo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Chedepo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Putupo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Gbeapo')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in River Gee') & (kece_melt['count']== 'Webbo')].sum()
k_a = k_s[1:-2]
k_a.sum()

0.0

In [145]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [146]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [147]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in River Cess

In [148]:
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Timobo')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Central Rivercess 1')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Central Rivercess 2')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Morwah')].sum()
k_s = kece_melt[(kece_melt['district']== 'Districts in River Cess') & (kece_melt['count']== 'Yarnee')].sum()
k_a = k_s[1:-2]
k_a.sum()

0.0

In [149]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [150]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [151]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

## Districts in Sinoe

In [152]:
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Upper Kpanyan')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Juarzon')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Lower Kpanyan')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Butaw')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Tarjuwon')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Jeadea')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Sanquin')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Greenville')].sum()
k_s = kece_melt[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Central Kpanyan')].sum()
k_a = k_s[1:-2]
k_a.sum()

0.0

In [153]:
k_a1 =k_a[::3].sum()
k_a1.sum()

0.0

In [154]:
k_a2 =k_a[1::3].sum()
k_a2

0.0

In [155]:
k_a3 =k_a[2::3].sum()
k_a3

0.0

# Table 8: Enrollment by District and Ownership

In [156]:
#kece_c.head()

In [157]:
kece_c = kcensus.iloc[:,[2]]
kece_o = kcensus.iloc[:,[39]]
kece_d = kcensus.iloc[:,3:19]

In [158]:
kece_cdso = pd.concat([kece_c, kece_o, kece_d, kece_s], axis = 1)
kece_cdso.columns

Index(['County', 'Type of school', 'District in Bong County',
       'District in Gbarpolu', 'District in River Gee', 'District in Sinoe',
       'District in Lofa', 'District in Nimba', 'District in Grand Cape Mount',
       'District in Maryland', 'District in Margibi', 'District in Bomi',
       'District in Grand Bassa', 'District in Montserrado 2',
       'District in Montserrado 1', 'Districts in Grand Kru',
       'Districts in Grand Gedeh', 'Districts in River Cess',
       'How many students age less than 10 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age less than 10 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age less than 10 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15  enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 10 to 15  enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 10 to 15  enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 10 to 15 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?.1',
       'How many students age between 25 to 30 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 25 to 30 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 30 to 35 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 30 to 35 enrolled in Level II of Alternative Education  are FE MALES?',
       'How many students age between 30 to 35 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level III of Alternative Education  are FEMALES?'],
      dtype='object')

In [159]:
kece_melto =kece_cdso.melt(id_vars=['County', 'Type of school',
        'How many students age less than 10 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age less than 10 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age less than 10 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age less than 10 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15  enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 10 to 15  enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 10 to 15  enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 10 to 15 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 10 to 15 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 15 to 20 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 15 to 20 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 20 to 25 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?.1',
       'How many students age between 25 to 30 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 25 to 30 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age between 25 to 30 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age between 30 to 35 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age between 30 to 35 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age between 30 to 35 enrolled in Level II of Alternative Education  are FE MALES?',
       'How many students age between 30 to 35 enrolled in Level III of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level I of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level II of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level III of Alternative Education  are MALES?',
       'How many students age greater than  35 enrolled in Level I of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level II of Alternative Education  are FEMALES?',
       'How many students age greater than  35 enrolled in Level III of Alternative Education  are FEMALES?'],var_name = 'district',value_name='count')
kece_melto.head()

,County,Type of school,How many students age less than 10 enrolled in Level I of Alternative Education are MALES?,How many students age less than 10 enrolled in Level II of Alternative Education are MALES?,How many students age less than 10 enrolled in Level III of Alternative Education are MALES?,How many students age less than 10 enrolled in Level I of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level II of Alternative Education are FEMALES?,How many students age less than 10 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are MALES?,How many students age between 10 to 15 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 10 to 15 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are MALES?,How many students age between 15 to 20 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 15 to 20 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 20 to 25 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are MALES?,How many students age between 20 to 25 enrolled in Level II of Alternative Education are MALES?.1,How many students age between 25 to 30 enrolled in Level III of Alternative Education are MALES?,How many students age between 25 to 30 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level II of Alternative Education are FEMALES?,How many students age between 25 to 30 enrolled in Level III of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are MALES?,How many students age between 30 to 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age between 30 to 35 enrolled in Level II of Alternative Education are FE MALES?,How many students age between 30 to 35 enrolled in Level III of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are MALES?,How many students age greater than 35 enrolled in Level I of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level II of Alternative Education are FEMALES?,How many students age greater than 35 enrolled in Level III of Alternative Education are FEMALES?,district,count
0,Rivercess,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
1,Nimba,Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
2,River Gee,Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
3,Montserrado 1,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
4,Montserrado 1,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN

In [160]:
#k_so = kece_melto[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Gbarma')].head(2).groupby('Type of school').sum()#.sum(1)
#k_so
#k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Greenville')].groupby('Type of school').sum().sum(1)
#k_so
#k_so#.sum(1)

## Districts in Bomi County

In [161]:
k_so = kece_melto[(kece_melto['district']== 'District in Bomi') & (kece_melto['count']== 'Senji')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Bomi') & (kece_melto['count']== 'Dewoin')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Bomi') & (kece_melto['count']== 'Klay')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Bomi') & (kece_melto['count']== 'Suehn-Mecca')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

0.0
Type of school
Private    0.0
Public     0.0
dtype: float64

## Districts in Bong County

In [162]:
k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Gbarnga 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Gbarnga 2')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Zota')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Salala')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Fuamah')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Suakoko')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Sanoyea')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Panta-Kpaai')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Bong County') & (kece_melto['count']== 'Kokoyah')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

45.0
Type of school
Community       0.0
Faith-based     0.0
Public         45.0
dtype: float64

## Districts in Gbarpolu

In [163]:
k_so = kece_melto[(kece_melto['district']== 'District in Gbarpolu') & (kece_melto['count']== 'Gorwalali')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Gbarpolu') & (kece_melto['count']== 'Bopolu')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Gbarpolu') & (kece_melto['count']== 'Gbarma')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Gbarpolu') & (kece_melto['count']== 'Belle')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Gbarpolu') & (kece_melto['count']== 'Bokomu')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Gbarpolu') & (kece_melto['count']== 'Kongba')].groupby('Type of school').sum().sum(1)
print(k_so.sum())
print(k_so)

0.0
Type of school
Public    0.0
dtype: float64

## Districts in Grand Bassa

In [164]:
k_so = kece_melto[(kece_melto['district']== 'District in Grand Bassa') & (kece_melto['count']== 'District 5')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Grand Bassa') & (kece_melto['count']== 'District 5B')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Grand Bassa') & (kece_melto['count']== 'District 2')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Grand Bassa') & (kece_melto['count']== 'District 3A')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Grand Bassa') & (kece_melto['count']== 'District 3B')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Grand Bassa') & (kece_melto['count']== 'District 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Grand Bassa') & (kece_melto['count']== 'District 4')].groupby('Type of school').sum().sum(1)
print(k_so.sum())
print(k_so)

42.0
Type of school
Community       0.0
Faith-based     0.0
Private         0.0
Public         42.0
dtype: float64

## Districts in Grand Cape Mount

In [165]:
k_so = kece_melto[(kece_melto['district']== 'District in Grand Cape Mount') & (kece_melto['count']== 'Tewor')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Grand Cape Mount') & (kece_melto['count']== 'Gola Konneh')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Grand Cape Mount') & (kece_melto['count']== 'Porkpa')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Grand Cape Mount') & (kece_melto['count']== 'Garwular')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Grand Cape Mount') & (kece_melto['count']== 'Tallah Tombay')].groupby('Type of school').sum().sum(1)
print(k_so.sum())
print(k_so)

0.0
Type of school
Community      0.0
Faith-based    0.0
Private        0.0
Public         0.0
dtype: float64

## Districts in Grand Gedeh

In [166]:
k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Gedeh') & (kece_melto['count']== 'Konobo')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Gedeh') & (kece_melto['count']== 'Putu')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Gedeh') & (kece_melto['count']== 'Gbarzon')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Gedeh') & (kece_melto['count']== 'Tchien')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Gedeh') & (kece_melto['count']== 'Cavalla')].groupby('Type of school').sum().sum(1)
print(k_so.sum())
print(k_so)

0.0
Type of school
Private    0.0
Public     0.0
dtype: float64

## Districts in Grand Kru

In [167]:
k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Kru') & (kece_melto['count']== 'Barclayville')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Kru') & (kece_melto['count']== 'Trehn')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Kru') & (kece_melto['count']== 'Buah')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Kru') & (kece_melto['count']== 'Grand Cess')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Kru') & (kece_melto['count']== 'Dorbor')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Kru') & (kece_melto['count']== 'Jloh')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Kru') & (kece_melto['count']== 'Sass Town')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'Districts in Grand Kru') & (kece_melto['count']== 'Wedabo')].groupby('Type of school').sum().sum(1)
print(k_so.sum())
print(k_so)

0.0
Type of school
Faith-based    0.0
Private        0.0
Public         0.0
dtype: float64

## Districts in Lofa

In [168]:
k_so = kece_melto[(kece_melto['district']== 'District in Lofa') & (kece_melto['count']== 'Foya')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Lofa') & (kece_melto['count']== 'Kolahun 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Lofa') & (kece_melto['count']== 'Kolahun 2')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Lofa') & (kece_melto['count']== 'Salayea')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Lofa') & (kece_melto['count']== 'Vahun')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Lofa') & (kece_melto['count']== 'Voinjama')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Lofa') & (kece_melto['count']== 'Zorzor')].groupby('Type of school').sum().sum(1)
print(k_so.sum())
print(k_so)

161.0
Type of school
Faith-based      0.0
Private          0.0
Public         161.0
dtype: float64

## Districts in Margibi

In [169]:
k_so = kece_melto[(kece_melto['district']== 'District in Margibi') & (kece_melto['count']== 'Marshall')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Margibi') & (kece_melto['count']== 'Farmington')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Margibi') & (kece_melto['count']== 'Mama kaba')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Margibi') & (kece_melto['count']== 'Gibi')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Margibi') & (kece_melto['count']== 'Kakata 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Margibi') & (kece_melto['count']== 'Kakata 2')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

97.0
Type of school
Community       0.0
Faith-based     0.0
Private         0.0
Public         97.0
dtype: float64

## Districts in Maryland

In [170]:
k_so = kece_melto[(kece_melto['district']== 'District in Maryland') & (kece_melto['count']== 'Harper 1')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Maryland') & (kece_melto['count']== 'Harper 2')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Maryland') & (kece_melto['count']== 'Barrobo 1')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Maryland') & (kece_melto['count']== 'Barrobo 2')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Maryland') & (kece_melto['count']== 'Sodoken')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Maryland') & (kece_melto['count']== 'Karleway 1')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Maryland') & (kece_melto['count']== 'Karleway 2')].groupby('Type of school').sum().sum(1)
#k_so = kece_melto[(kece_melto['district']== 'District in Maryland') & (kece_melto['count']== 'Pleebo')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

0.0
Series([], dtype: float64)

## Districts in Montserrado 1

In [171]:
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Paynesville 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Paynesville 2')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melt['count']== 'Paynesville 3')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Paynesville 4')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Paynesville 5')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Paynesville 6')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 1A')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 1B')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 1C')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 1D')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 1E')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 2A')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 2B')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 2C')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 1') & (kece_melto['count']== 'Greater Monrovia 2D')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

0.0
Type of school
Community      0.0
Faith-based    0.0
Private        0.0
Public         0.0
dtype: float64

## Districts in Montserrado 2

In [172]:
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Left Bank 1A')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Left bank 1B')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Left bank  1C')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Left Bank 1D')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Left Bank 2A')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Left bank 2B')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Careysburg')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Todee')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Right Bank 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Right Bank 2')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Montserrado 2') & (kece_melto['count']== 'Right Bank 3')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

111.0
Type of school
Faith-based      0.0
Private          0.0
Public         111.0
dtype: float64

## Districts in Nimba

In [173]:
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Tappita 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Tappita 2')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Saclepea 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Sanniquellie Mah')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Zoe-Geh')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Tuwah River')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Gbelay-Geh')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Yarpea Mah')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Yarwein Mensonoh')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Buuyao')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Bain-Garr 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Nimba') & (kece_melto['count']== 'Bain- Garr 2')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

0.0
Type of school
Community      0.0
Faith-based    0.0
Private        0.0
Public         0.0
dtype: float64

## Districts in River Gee

In [174]:
k_so = kece_melto[(kece_melto['district']== 'District in River Gee') & (kece_melto['count']== 'Sarbo')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in River Gee') & (kece_melto['count']== 'Tienpo')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in River Gee') & (kece_melto['count']== 'Chedepo')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in River Gee') & (kece_melto['count']== 'Putupo')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in River Gee') & (kece_melto['count']== 'Gbeapo')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in River Gee') & (kece_melto['count']== 'Webbo')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

0.0
Type of school
Public    0.0
dtype: float64

## Districts in River Cess

In [175]:
k_so = kece_melto[(kece_melto['district']== 'Districts in River Cess') & (kece_melto['count']== 'Timobo')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'Districts in River Cess') & (kece_melto['count']== 'Central Rivercess 1')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'Districts in River Cess') & (kece_melto['count']== 'Central Rivercess 2')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'Districts in River Cess') & (kece_melto['count']== 'Morwah')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'Districts in River Cess') & (kece_melto['count']== 'Yarnee')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

0.0
Type of school
Faith-based    0.0
Public         0.0
dtype: float64

## Districts in Sinoe

In [176]:
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Upper Kpanyan')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Juarzon')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Lower Kpanyan')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Butaw')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Tarjuwon')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Jeadea')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Sanquin')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Greenville')].groupby('Type of school').sum().sum(1)
k_so = kece_melto[(kece_melto['district']== 'District in Sinoe') & (kece_melto['count']== 'Central Kpanyan')].groupby('Type of school').sum().sum(1)

print(k_so.sum())
print(k_so)

0.0
Type of school
Public    0.0
dtype: float64

# Table 9: ALP Disability by Ownership

In [183]:
kece_disa=kcensus.iloc[:,662:686]
kece_disa.head()
#eceo=kece_disao.iloc[:,0]
#eceo.head()
#kece_disa.head()
kece_disao=pd.concat([kece_o,kece_disa], axis =1)
kece_disao.head()
kece_dis1 = kece_disao.groupby('Type of school').sum()
kece_dis1#.sum(1).sum()

,How many FEMALE students in Alternative Education Level I are Visually impaired?,How many MALE students in Alternative Education Level I are Visually impaired ?,How many FEMALE students in Alternative Education Level II are Visually impaired ?,How many MALE students in Alternative Education Level II are Visually impaired ?,How many FEMALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level I have hearing impairment?,How many FEMALE students in Alternative Education Level I have hearing impairment?,How many MALE students in Alternative Education Level II have hearing impairment?,How many FEMALE students in Alternative Education Level II have hearing impairment?,How many MALE students in Alternative Education Level III have hearing impairment?,How many FEMALE students in Alternative Education Level III have hearing impairment?,How many MALE students in Alternative Education Level I have other physical disabilities?,How many FEMALE students in Alternative Education Level I have other physical disabilities?,How many MALE students in Alternative Education Level II have other physical disabilities?,How many FEMALE students in Alternative Education Level II have other physical disabilities?,How many MALE students in Alternative Education Level III have other physical disabilities?,How many FEMALE students in Alternative Education Level III have other physical disabilities?,How many MALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level III have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level III have other mental disability or learning difficulty?
Type of school,,,,,,,,,,,,,,,,,,,,,,,,
Community,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Faith-based,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Private,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Public,0.0,0.0,1.0,8.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,5.0,5.0,1.0,0.0,1.0,0.0,5.0,2.0,4.0,18.0,0.0,0.0

In [185]:
kece_dis1v= kece_dis1.iloc[:,:6].sum(1)
kece_dis1v

Type of school
Community       0.0
Faith-based     0.0
Private         0.0
Public         11.0
dtype: float64

In [187]:
kece_dish = kece_dis1.iloc[:,6:12].sum(1)
kece_dish

Type of school
Community      0.0
Faith-based    0.0
Private        0.0
Public         3.0
dtype: float64

In [189]:
kece_disp = kece_dis1.iloc[:,12:18].sum(1)
kece_disp

Type of school
Community       0.0
Faith-based     0.0
Private         0.0
Public         12.0
dtype: float64

In [191]:
kece_disl = kece_dis1.iloc[:,18:].sum(1)
kece_disl

Type of school
Community       0.0
Faith-based     0.0
Private         0.0
Public         29.0
dtype: float64

In [ ]:
kece_dis1.iloc[:,:6]
kece_dis1.iloc[:,6:12]
kece_dis1.iloc[:,12:18]
kece_dis1.iloc[:,18:]

# Table 10: ECE Disability by Gender

In [192]:
kece_dis1.head()

,How many FEMALE students in Alternative Education Level I are Visually impaired?,How many MALE students in Alternative Education Level I are Visually impaired ?,How many FEMALE students in Alternative Education Level II are Visually impaired ?,How many MALE students in Alternative Education Level II are Visually impaired ?,How many FEMALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level I have hearing impairment?,How many FEMALE students in Alternative Education Level I have hearing impairment?,How many MALE students in Alternative Education Level II have hearing impairment?,How many FEMALE students in Alternative Education Level II have hearing impairment?,How many MALE students in Alternative Education Level III have hearing impairment?,How many FEMALE students in Alternative Education Level III have hearing impairment?,How many MALE students in Alternative Education Level I have other physical disabilities?,How many FEMALE students in Alternative Education Level I have other physical disabilities?,How many MALE students in Alternative Education Level II have other physical disabilities?,How many FEMALE students in Alternative Education Level II have other physical disabilities?,How many MALE students in Alternative Education Level III have other physical disabilities?,How many FEMALE students in Alternative Education Level III have other physical disabilities?,How many MALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level III have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level III have other mental disability or learning difficulty?
Type of school,,,,,,,,,,,,,,,,,,,,,,,,
Community,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Faith-based,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Private,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Public,0.0,0.0,1.0,8.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,5.0,5.0,1.0,0.0,1.0,0.0,5.0,2.0,4.0,18.0,0.0,0.0

In [243]:
kece_v = kece_dis1.iloc[:,:6].sum()
kece_v.sum()

11.0

In [223]:
kece_v[1::2].sum()

10.0

In [224]:
kece_v[::2].sum()

1.0

In [228]:
kece_h = kece_dis1.iloc[:,6:12].sum()
kece_h.sum()

3.0

In [226]:
kece_h[::2].sum()

2.0

In [227]:
kece_h[1::2].sum()

1.0

In [231]:
kece_p = kece_dis1.iloc[:,12:18].sum()
kece_p.sum()

12.0

In [229]:
kece_p[::2].sum()

7.0

In [230]:
kece_p[1::2].sum()

5.0

In [220]:
kece_l = kece_dis1.iloc[:,18:].sum()
kece_l

How many MALE students in  Alternative Education Level I have other mental disability or learning difficulty?         5.0
How many FEMALE students in Alternative Education  Level I have other mental disability or learning difficulty?       2.0
How many MALE students in Alternative Education  Level II have other mental disability or learning difficulty?        4.0
How many FEMALE students in Alternative Education  Level II have other mental disability or learning difficulty?     18.0
How many MALE students in Alternative Education  Level III have other mental disability or learning difficulty?       0.0
How many FEMALE students in Alternative Education  Level III have other mental disability or learning difficulty?     0.0
dtype: float64

In [232]:
kece_l[::2].sum()

9.0

In [233]:
kece_l[1::2].sum()

20.0

In [193]:
kdist=kece_dis1.sum()
kdist

,How many FEMALE students in Alternative Education Level I are Visually impaired?,How many MALE students in Alternative Education Level I are Visually impaired ?,How many FEMALE students in Alternative Education Level II are Visually impaired ?,How many MALE students in Alternative Education Level II are Visually impaired ?,How many FEMALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level I have hearing impairment?,How many FEMALE students in Alternative Education Level I have hearing impairment?,How many MALE students in Alternative Education Level II have hearing impairment?,How many FEMALE students in Alternative Education Level II have hearing impairment?,How many MALE students in Alternative Education Level III have hearing impairment?,How many FEMALE students in Alternative Education Level III have hearing impairment?,How many MALE students in Alternative Education Level I have other physical disabilities?,How many FEMALE students in Alternative Education Level I have other physical disabilities?,How many MALE students in Alternative Education Level II have other physical disabilities?,How many FEMALE students in Alternative Education Level II have other physical disabilities?,How many MALE students in Alternative Education Level III have other physical disabilities?,How many FEMALE students in Alternative Education Level III have other physical disabilities?,How many MALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level III have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level III have other mental disability or learning difficulty?
Type of school,,,,,,,,,,,,,,,,,,,,,,,,
Community,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Faith-based,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Private,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Public,0.0,0.0,1.0,8.0,0.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,5.0,5.0,1.0,0.0,1.0,0.0,5.0,2.0,4.0,18.0,0.0,0.0

In [ ]:
kece_dis1v

In [ ]:
kdisvm=kdist[0:5:2].sum()
kdisvm

In [ ]:
kdisvf=kdist[1:6:2].sum()
kdisvf

In [ ]:
kdishm=kdist[6:12:2].sum()
kdishm

In [ ]:
kdishf=kdist[7:13:2].sum()
kdishf

In [ ]:
kdispm=kdist[12:18:2].sum()
kdispm

In [ ]:
kdispf=kdist[13:19:2].sum()
kdispf

In [ ]:
kdislm=kdist[18:21].sum()
kdislm

In [ ]:
kdislf=kdist[21:].sum()
kdislf

# Table 11: ALP Disability by Grade

In [244]:
kece_v

How many FEMALE students in Alternative Education Level I are Visually impaired?        0.0
How many MALE students in Alternative Education  Level I are Visually impaired ?        0.0
How many FEMALE students in Alternative Education  Level II are Visually impaired ?     1.0
How many MALE students in Alternative Education  Level II are Visually impaired ?       8.0
How many FEMALE students in Alternative Education  Level III are Visually impaired ?    0.0
How many MALE students in Alternative Education  Level III are Visually impaired ?      2.0
dtype: float64

In [251]:
kece_v[:2].sum()

0.0

In [252]:
kece_v[2:4].sum()

9.0

In [253]:
kece_v[4:6].sum()

2.0

In [245]:
kece_h

How many MALE students in Alternative Education  Level I have hearing impairment?        0.0
How many FEMALE students in Alternative Education  Level I have hearing impairment?      0.0
How many MALE students in Alternative Education  Level II have hearing impairment?       1.0
How many FEMALE students in Alternative Education  Level II have hearing impairment?     1.0
How many MALE students in Alternative Education  Level III have hearing impairment?      1.0
How many FEMALE students in Alternative Education  Level III have hearing impairment?    0.0
dtype: float64

In [257]:
kece_h[:2].sum()

0.0

In [258]:
kece_h[2:4].sum()

2.0

In [259]:
kece_h[4:6].sum()

1.0

In [246]:
kece_p

How many MALE students in Alternative Education Level I  have other physical disabilities?        5.0
How many FEMALE students in Alternative Education Level I  have other physical disabilities?      5.0
How many MALE students in Alternative Education Level II  have other physical disabilities?       1.0
How many FEMALE students in Alternative Education Level II  have other physical disabilities?     0.0
How many MALE students in Alternative Education Level III  have other physical disabilities?      1.0
How many FEMALE students in Alternative Education Level III  have other physical disabilities?    0.0
dtype: float64

In [263]:
kece_p[:2].sum()

10.0

In [264]:
kece_p[2:4].sum()

1.0

In [265]:
kece_p[4:6].sum()

1.0

In [247]:
kece_l

How many MALE students in  Alternative Education Level I have other mental disability or learning difficulty?         5.0
How many FEMALE students in Alternative Education  Level I have other mental disability or learning difficulty?       2.0
How many MALE students in Alternative Education  Level II have other mental disability or learning difficulty?        4.0
How many FEMALE students in Alternative Education  Level II have other mental disability or learning difficulty?     18.0
How many MALE students in Alternative Education  Level III have other mental disability or learning difficulty?       0.0
How many FEMALE students in Alternative Education  Level III have other mental disability or learning difficulty?     0.0
dtype: float64

In [269]:
kece_l[:2].sum()

7.0

In [270]:
kece_l[2:4].sum()

22.0

In [271]:
kece_l[4:6].sum()

0.0

In [240]:
ddt = kece_dis1.sum()
ddt

How many FEMALE students in Alternative Education Level I are Visually impaired?                                      0.0
How many MALE students in Alternative Education  Level I are Visually impaired ?                                      0.0
How many FEMALE students in Alternative Education  Level II are Visually impaired ?                                   1.0
How many MALE students in Alternative Education  Level II are Visually impaired ?                                     8.0
How many FEMALE students in Alternative Education  Level III are Visually impaired ?                                  0.0
How many MALE students in Alternative Education  Level III are Visually impaired ?                                    2.0
How many MALE students in Alternative Education  Level I have hearing impairment?                                     0.0
How many FEMALE students in Alternative Education  Level I have hearing impairment?                                   0.0
How many MALE students in Alternative Education  Level II have hearing impairment?                                    1.0
How many FEMALE students in Alternative Education  Level II have hearing impairment?                                  1.0
How many MALE students in Alternative Education  Level III have hearing impairment?                                   1.0
How many FEMALE students in Alternative Education  Level III have hearing impairment?                                 0.0
How many MALE students in Alternative Education Level I  have other physical disabilities?                            5.0
How many FEMALE students in Alternative Education Level I  have other physical disabilities?                          5.0
How many MALE students in Alternative Education Level II  have other physical disabilities?                           1.0
How many FEMALE students in Alternative Education Level II  have other physical disabilities?                         0.0
How many MALE students in Alternative Education Level III  have other physical disabilities?                          1.0
How many FEMALE students in Alternative Education Level III  have other physical disabilities?                        0.0
How many MALE students in  Alternative Education Level I have other mental disability or learning difficulty?         5.0
How many FEMALE students in Alternative Education  Level I have other mental disability or learning difficulty?       2.0
How many MALE students in Alternative Education  Level II have other mental disability or learning difficulty?        4.0
How many FEMALE students in Alternative Education  Level II have other mental disability or learning difficulty?     18.0
How many MALE students in Alternative Education  Level III have other mental disability or learning difficulty?       0.0
How many FEMALE students in Alternative Education  Level III have other mental disability or learning difficulty?     0.0
dtype: float64

In [241]:
dd_v

NameError: name 'dd_v' is not defined

In [237]:
dd_s[:2]#.sum()

,How many FEMALE students in Alternative Education Level I are Visually impaired?,How many MALE students in Alternative Education Level I are Visually impaired ?,How many FEMALE students in Alternative Education Level II are Visually impaired ?,How many MALE students in Alternative Education Level II are Visually impaired ?,How many FEMALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level I have hearing impairment?,How many FEMALE students in Alternative Education Level I have hearing impairment?,How many MALE students in Alternative Education Level II have hearing impairment?,How many FEMALE students in Alternative Education Level II have hearing impairment?,How many MALE students in Alternative Education Level III have hearing impairment?,How many FEMALE students in Alternative Education Level III have hearing impairment?,How many MALE students in Alternative Education Level I have other physical disabilities?,How many FEMALE students in Alternative Education Level I have other physical disabilities?,How many MALE students in Alternative Education Level II have other physical disabilities?,How many FEMALE students in Alternative Education Level II have other physical disabilities?,How many MALE students in Alternative Education Level III have other physical disabilities?,How many FEMALE students in Alternative Education Level III have other physical disabilities?,How many MALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level III have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level III have other mental disability or learning difficulty?
Type of school,,,,,,,,,,,,,,,,,,,,,,,,
Community,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Faith-based,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
dd_s[2:4].sum()

In [ ]:
dd_s[4:6].sum()

In [ ]:
dd_s[6:8].sum()

In [ ]:
dd_s[8:10].sum()

In [ ]:
dd_s[10:12].sum()

In [ ]:
dd_s[12:14].sum()

In [ ]:
dd_s[14:16].sum()

In [ ]:
dd_s[16:18].sum()

In [ ]:
dd_s[[18,21]].sum()

In [ ]:
dd_s[[19,22]].sum()

In [ ]:
dd_s[[20,23]].sum()

# Table 12: ALP by Enrollment by Disability and County

In [272]:
kece_c = kcensus.iloc[:,[2]]
kece_o = kcensus.iloc[:,[39]]
kece_d = kcensus.iloc[:,3:19]
kece_disa.head()

,How many FEMALE students in Alternative Education Level I are Visually impaired?,How many MALE students in Alternative Education Level I are Visually impaired ?,How many FEMALE students in Alternative Education Level II are Visually impaired ?,How many MALE students in Alternative Education Level II are Visually impaired ?,How many FEMALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level I have hearing impairment?,How many FEMALE students in Alternative Education Level I have hearing impairment?,How many MALE students in Alternative Education Level II have hearing impairment?,How many FEMALE students in Alternative Education Level II have hearing impairment?,How many MALE students in Alternative Education Level III have hearing impairment?,How many FEMALE students in Alternative Education Level III have hearing impairment?,How many MALE students in Alternative Education Level I have other physical disabilities?,How many FEMALE students in Alternative Education Level I have other physical disabilities?,How many MALE students in Alternative Education Level II have other physical disabilities?,How many FEMALE students in Alternative Education Level II have other physical disabilities?,How many MALE students in Alternative Education Level III have other physical disabilities?,How many FEMALE students in Alternative Education Level III have other physical disabilities?,How many MALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level III have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level III have other mental disability or learning difficulty?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [273]:
kece_cdd = pd.concat([kece_c, kece_d, kece_disa], axis = 1)
kece_cdd.columns
kece_cdd.head()

,County,District in Bong County,District in Gbarpolu,District in River Gee,District in Sinoe,District in Lofa,District in Nimba,District in Grand Cape Mount,District in Maryland,District in Margibi,District in Bomi,District in Grand Bassa,District in Montserrado 2,District in Montserrado 1,Districts in Grand Kru,Districts in Grand Gedeh,Districts in River Cess,How many FEMALE students in Alternative Education Level I are Visually impaired?,How many MALE students in Alternative Education Level I are Visually impaired ?,How many FEMALE students in Alternative Education Level II are Visually impaired ?,How many MALE students in Alternative Education Level II are Visually impaired ?,How many FEMALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level I have hearing impairment?,How many FEMALE students in Alternative Education Level I have hearing impairment?,How many MALE students in Alternative Education Level II have hearing impairment?,How many FEMALE students in Alternative Education Level II have hearing impairment?,How many MALE students in Alternative Education Level III have hearing impairment?,How many FEMALE students in Alternative Education Level III have hearing impairment?,How many MALE students in Alternative Education Level I have other physical disabilities?,How many FEMALE students in Alternative Education Level I have other physical disabilities?,How many MALE students in Alternative Education Level II have other physical disabilities?,How many FEMALE students in Alternative Education Level II have other physical disabilities?,How many MALE students in Alternative Education Level III have other physical disabilities?,How many FEMALE students in Alternative Education Level III have other physical disabilities?,How many MALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level III have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level III have other mental disability or learning difficulty?
0,Rivercess,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Timobo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nimba,NaN,NaN,NaN,NaN,NaN,Zoe-Geh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,River Gee,NaN,NaN,Tienpo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Montserrado 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Paynesville 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Montserrado 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Greater Monrovia 1A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [277]:
dd = kece_cdd.groupby('County').sum()
dd#.sum(1)

,How many FEMALE students in Alternative Education Level I are Visually impaired?,How many MALE students in Alternative Education Level I are Visually impaired ?,How many FEMALE students in Alternative Education Level II are Visually impaired ?,How many MALE students in Alternative Education Level II are Visually impaired ?,How many FEMALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level I have hearing impairment?,How many FEMALE students in Alternative Education Level I have hearing impairment?,How many MALE students in Alternative Education Level II have hearing impairment?,How many FEMALE students in Alternative Education Level II have hearing impairment?,How many MALE students in Alternative Education Level III have hearing impairment?,How many FEMALE students in Alternative Education Level III have hearing impairment?,How many MALE students in Alternative Education Level I have other physical disabilities?,How many FEMALE students in Alternative Education Level I have other physical disabilities?,How many MALE students in Alternative Education Level II have other physical disabilities?,How many FEMALE students in Alternative Education Level II have other physical disabilities?,How many MALE students in Alternative Education Level III have other physical disabilities?,How many FEMALE students in Alternative Education Level III have other physical disabilities?,How many MALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level III have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level III have other mental disability or learning difficulty?
County,,,,,,,,,,,,,,,,,,,,,,,,
Bomi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bong,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
Gbarpolu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Bassa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Cape Mount,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Gedeh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Grand Kru,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Lofa,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0
Margibi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
Maryland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Montserrado 1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,4.0,2.0,0.0,0.0
Montserrado 2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Nimba,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0
River Gee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Rivercess,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sinoe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [282]:
dd.iloc[:,:6].sum(1)

County
Bomi                0.0
Bong                0.0
Gbarpolu            0.0
Grand Bassa         0.0
Grand Cape Mount    0.0
Grand Gedeh         0.0
Grand Kru           0.0
Lofa                8.0
Margibi             0.0
Maryland            0.0
Montserrado 1       0.0
Montserrado 2       0.0
Nimba               3.0
River Gee           0.0
Rivercess           0.0
Sinoe               0.0
dtype: float64

In [283]:
dd.iloc[:,6:12].sum(1)

County
Bomi                0.0
Bong                1.0
Gbarpolu            0.0
Grand Bassa         0.0
Grand Cape Mount    0.0
Grand Gedeh         0.0
Grand Kru           0.0
Lofa                0.0
Margibi             0.0
Maryland            0.0
Montserrado 1       0.0
Montserrado 2       0.0
Nimba               2.0
River Gee           0.0
Rivercess           0.0
Sinoe               0.0
dtype: float64

In [284]:
dd.iloc[:,12:18].sum(1)

County
Bomi                0.0
Bong                2.0
Gbarpolu            0.0
Grand Bassa         2.0
Grand Cape Mount    0.0
Grand Gedeh         0.0
Grand Kru           0.0
Lofa                7.0
Margibi             0.0
Maryland            0.0
Montserrado 1       0.0
Montserrado 2       0.0
Nimba               1.0
River Gee           0.0
Rivercess           0.0
Sinoe               0.0
dtype: float64

In [285]:
dd.iloc[:,18:].sum(1)

County
Bomi                 0.0
Bong                 1.0
Gbarpolu             0.0
Grand Bassa          0.0
Grand Cape Mount     0.0
Grand Gedeh          0.0
Grand Kru            0.0
Lofa                 8.0
Margibi              1.0
Maryland             0.0
Montserrado 1       11.0
Montserrado 2        0.0
Nimba                8.0
River Gee            0.0
Rivercess            0.0
Sinoe                0.0
dtype: float64

# Table 13: ALP Enrollment by Disability and Districts

In [286]:
kece_cdd.columns

Index(['County', 'District in Bong County', 'District in Gbarpolu',
       'District in River Gee', 'District in Sinoe', 'District in Lofa',
       'District in Nimba', 'District in Grand Cape Mount',
       'District in Maryland', 'District in Margibi', 'District in Bomi',
       'District in Grand Bassa', 'District in Montserrado 2',
       'District in Montserrado 1', 'Districts in Grand Kru',
       'Districts in Grand Gedeh', 'Districts in River Cess',
       'How many FEMALE students in Alternative Education Level I are Visually impaired?',
       'How many MALE students in Alternative Education  Level I are Visually impaired ?',
       'How many FEMALE students in Alternative Education  Level II are Visually impaired ?',
       'How many MALE students in Alternative Education  Level II are Visually impaired ?',
       'How many FEMALE students in Alternative Education  Level III are Visually impaired ?',
       'How many MALE students in Alternative Education  Level III are Visually impaired ?',
       'How many MALE students in Alternative Education  Level I have hearing impairment?',
       'How many FEMALE students in Alternative Education  Level I have hearing impairment?',
       'How many MALE students in Alternative Education  Level II have hearing impairment?',
       'How many FEMALE students in Alternative Education  Level II have hearing impairment?',
       'How many MALE students in Alternative Education  Level III have hearing impairment?',
       'How many FEMALE students in Alternative Education  Level III have hearing impairment?',
       'How many MALE students in Alternative Education Level I  have other physical disabilities?',
       'How many FEMALE students in Alternative Education Level I  have other physical disabilities?',
       'How many MALE students in Alternative Education Level II  have other physical disabilities?',
       'How many FEMALE students in Alternative Education Level II  have other physical disabilities?',
       'How many MALE students in Alternative Education Level III  have other physical disabilities?',
       'How many FEMALE students in Alternative Education Level III  have other physical disabilities?',
       'How many MALE students in  Alternative Education Level I have other mental disability or learning difficulty?',
       'How many FEMALE students in Alternative Education  Level I have other mental disability or learning difficulty?',
       'How many MALE students in Alternative Education  Level II have other mental disability or learning difficulty?',
       'How many FEMALE students in Alternative Education  Level II have other mental disability or learning difficulty?',
       'How many MALE students in Alternative Education  Level III have other mental disability or learning difficulty?',
       'How many FEMALE students in Alternative Education  Level III have other mental disability or learning difficulty?'],
      dtype='object')

In [287]:
kece_meltdd =kece_cdd.melt(id_vars=['How many FEMALE students in Alternative Education Level I are Visually impaired?',
       'How many MALE students in Alternative Education  Level I are Visually impaired ?',
       'How many FEMALE students in Alternative Education  Level II are Visually impaired ?',
       'How many MALE students in Alternative Education  Level II are Visually impaired ?',
       'How many FEMALE students in Alternative Education  Level III are Visually impaired ?',
       'How many MALE students in Alternative Education  Level III are Visually impaired ?',
       'How many MALE students in Alternative Education  Level I have hearing impairment?',
       'How many FEMALE students in Alternative Education  Level I have hearing impairment?',
       'How many MALE students in Alternative Education  Level II have hearing impairment?',
       'How many FEMALE students in Alternative Education  Level II have hearing impairment?',
       'How many MALE students in Alternative Education  Level III have hearing impairment?',
       'How many FEMALE students in Alternative Education  Level III have hearing impairment?',
       'How many MALE students in Alternative Education Level I  have other physical disabilities?',
       'How many FEMALE students in Alternative Education Level I  have other physical disabilities?',
       'How many MALE students in Alternative Education Level II  have other physical disabilities?',
       'How many FEMALE students in Alternative Education Level II  have other physical disabilities?',
       'How many MALE students in Alternative Education Level III  have other physical disabilities?',
       'How many FEMALE students in Alternative Education Level III  have other physical disabilities?',
       'How many MALE students in  Alternative Education Level I have other mental disability or learning difficulty?',
       'How many FEMALE students in Alternative Education  Level I have other mental disability or learning difficulty?',
       'How many MALE students in Alternative Education  Level II have other mental disability or learning difficulty?',
       'How many FEMALE students in Alternative Education  Level II have other mental disability or learning difficulty?',
       'How many MALE students in Alternative Education  Level III have other mental disability or learning difficulty?',
       'How many FEMALE students in Alternative Education  Level III have other mental disability or learning difficulty?'],var_name = 'district',value_name='count')
kece_meltdd.head()

,How many FEMALE students in Alternative Education Level I are Visually impaired?,How many MALE students in Alternative Education Level I are Visually impaired ?,How many FEMALE students in Alternative Education Level II are Visually impaired ?,How many MALE students in Alternative Education Level II are Visually impaired ?,How many FEMALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level III are Visually impaired ?,How many MALE students in Alternative Education Level I have hearing impairment?,How many FEMALE students in Alternative Education Level I have hearing impairment?,How many MALE students in Alternative Education Level II have hearing impairment?,How many FEMALE students in Alternative Education Level II have hearing impairment?,How many MALE students in Alternative Education Level III have hearing impairment?,How many FEMALE students in Alternative Education Level III have hearing impairment?,How many MALE students in Alternative Education Level I have other physical disabilities?,How many FEMALE students in Alternative Education Level I have other physical disabilities?,How many MALE students in Alternative Education Level II have other physical disabilities?,How many FEMALE students in Alternative Education Level II have other physical disabilities?,How many MALE students in Alternative Education Level III have other physical disabilities?,How many FEMALE students in Alternative Education Level III have other physical disabilities?,How many MALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level I have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level II have other mental disability or learning difficulty?,How many MALE students in Alternative Education Level III have other mental disability or learning difficulty?,How many FEMALE students in Alternative Education Level III have other mental disability or learning difficulty?,district,count
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,County,Rivercess
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,County,Nimba
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,County,River Gee
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,County,Montserrado 1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,County,Montserrado 1

## Districts in Bomi County

In [312]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bomi') & (kece_meltdd['count']== 'Senji')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bomi') & (kece_meltdd['count']== 'Dewoin')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bomi') & (kece_meltdd['count']== 'Klay')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bomi') & (kece_meltdd['count']== 'Suehn-Mecca')]
k_dd.sum(1).sum()

0.0

In [313]:
k_dd.iloc[:,:6].sum().sum()

0.0

In [314]:
k_dd.iloc[:,6:12].sum().sum()

0.0

In [315]:
k_dd.iloc[:,12:18].sum().sum()

0.0

In [316]:
k_dd.iloc[:,18:24].sum().sum()

0.0

## Districts in Bong County

In [357]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Gbarnga 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Gbarnga 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Zota')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Salala')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Fuamah')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Suakoko')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Sanoyea')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Panta-Kpaai')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Bong County') & (kece_meltdd['count']== 'Kokoyah')]
k_dd.sum(1).sum()

2.0

In [358]:
k_dd.iloc[:,:6].sum().sum()

0.0

In [359]:
k_dd.iloc[:,6:12].sum().sum()

1.0

In [360]:
k_dd.iloc[:,12:18].sum().sum()

1.0

In [361]:
k_dd.iloc[:,18:24].sum().sum()

0.0

## Districts in Gbarpolu

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Gbarpolu') & (kece_meltdd['count']== 'Gorwalali')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Gbarpolu') & (kece_meltdd['count']== 'Bopolu')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Gbarpolu') & (kece_meltdd['count']== 'Gbarma')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Gbarpolu') & (kece_meltdd['count']== 'Belle')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Gbarpolu') & (kece_meltdd['count']== 'Bokomu')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Gbarpolu') & (kece_meltdd['count']== 'Kongba')]
#k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

## Districts in Grand Bassa

In [596]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Bassa') & (kece_meltdd['count']== 'District 5')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Bassa') & (kece_meltdd['count']== 'District 5B')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Bassa') & (kece_meltdd['count']== 'District 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Bassa') & (kece_meltdd['count']== 'District 3A')]
#k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Bassa') & (kece_meltdd['count']== 'District 3B')]
#k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Bassa') & (kece_meltdd['count']== 'District 1')]
#k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Bassa') & (kece_meltdd['count']== 'District 4')]

#k_dd.sum(1).sum()

In [597]:
k_dd.iloc[:,:6].sum().sum()

0.0

In [598]:
k_dd.iloc[:,6:12].sum().sum()

0.0

In [599]:
k_dd.iloc[:,12:18].sum().sum()

2.0

In [600]:
k_dd.iloc[:,18:24].sum().sum()

0.0

## Districts in Grand Cape Mount

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Cape Mount') & (kece_meltdd['count']== 'Tewor')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Cape Mount') & (kece_meltdd['count']== 'Gola Konneh')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Cape Mount') & (kece_meltdd['count']== 'Porkpa')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Cape Mount') & (kece_meltdd['count']== 'Garwular')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Grand Cape Mount') & (kece_meltdd['count']== 'Tallah Tombay')]
#k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

## Districts in Grand Gedeh

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Gedeh') & (kece_meltdd['count']== 'Konobo')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Gedeh') & (kece_meltdd['count']== 'Putu')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Gedeh') & (kece_meltdd['count']== 'Gbarzon')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Gedeh') & (kece_meltdd['count']== 'Tchien')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Gedeh') & (kece_meltdd['count']== 'Cavalla')]
#k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

## Districts in Grand Kru

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Kru') & (kece_meltdd['count']== 'Barclayville')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Kru') & (kece_meltdd['count']== 'Trehn')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Kru') & (kece_meltdd['count']== 'Buah')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Kru') & (kece_meltdd['count']== 'Grand Cess')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Kru') & (kece_meltdd['count']== 'Dorbor')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Kru') & (kece_meltdd['count']== 'Jloh')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Kru') & (kece_meltdd['count']== 'Sass Town')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in Grand Kru') & (kece_meltdd['count']== 'Wedabo')]

k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

## Districts in Lofa

In [576]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Lofa') & (kece_meltdd['count']== 'Foya')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Lofa') & (kece_meltdd['count']== 'Kolahun 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Lofa') & (kece_meltdd['count']== 'Kolahun 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Lofa') & (kece_meltdd['count']== 'Salayea')]
#k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Lofa') & (kece_meltdd['count']== 'Vahun')]
#k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Lofa') & (kece_meltdd['count']== 'Voinjama')]
#k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Lofa') & (kece_meltdd['count']== 'Zorzor')]

#k_dd.sum(1).sum()

In [577]:
k_dd.iloc[:,:6].sum().sum()

8.0

In [578]:
k_dd.iloc[:,6:12].sum().sum()

0.0

In [579]:
k_dd.iloc[:,12:18].sum().sum()

3.0

In [580]:
k_dd.iloc[:,18:24].sum().sum()

8.0

## Districts in Margibi

In [581]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Margibi') & (kece_meltdd['count']== 'Marshall')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Margibi') & (kece_meltdd['count']== 'Farmington')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Margibi') & (kece_meltdd['count']== 'Mama kaba')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Margibi') & (kece_meltdd['count']== 'Gibi')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Margibi') & (kece_meltdd['count']== 'Kakata 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Margibi') & (kece_meltdd['count']== 'Kakata 2')]
#k_dd.sum(1).sum()

In [582]:
k_dd.iloc[:,:6].sum().sum()

0.0

In [583]:
k_dd.iloc[:,6:12].sum().sum()

0.0

In [584]:
k_dd.iloc[:,12:18].sum().sum()

0.0

In [585]:
k_dd.iloc[:,18:24].sum().sum()

0.0

#####

## Districts in Maryland

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Maryland') & (kece_meltdd['count']== 'Harper 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Maryland') & (kece_meltdd['count']== 'Harper 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Maryland') & (kece_meltdd['count']== 'Barrobo 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Maryland') & (kece_meltdd['count']== 'Barrobo 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Maryland') & (kece_meltdd['count']== 'Sodoken')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Maryland') & (kece_meltdd['count']== 'Karleway 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Maryland') & (kece_meltdd['count']== 'Karleway 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Maryland') & (kece_meltdd['count']== 'Pleebo')]

#k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

## Districts in Montserrado 1

In [497]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Paynesville 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Paynesville 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Paynesville 3')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Paynesville 4')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Paynesville 5')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Paynesville 6')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 1A')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 1B')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 1C')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 1D')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 1E')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 2A')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 2B')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 2C')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 1') & (kece_meltdd['count']== 'Greater Monrovia 2D')]

#k_dd.sum(1).sum()

In [498]:
k_dd.iloc[:,:6].sum().sum()

0.0

In [499]:
k_dd.iloc[:,6:12].sum().sum()

0.0

In [500]:
k_dd.iloc[:,12:18].sum().sum()

0.0

In [501]:
k_dd.iloc[:,18:24].sum().sum()

0.0

## Districts in Montserrado 2

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Left Bank 1A')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Left bank 1B')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Left bank  1C')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Left Bank 1D')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Left Bank 2A')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Left bank 2B')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Careysburg')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Todee')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Right Bank 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Right Bank 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Montserrado 2') & (kece_meltdd['count']== 'Right Bank 3')]

#k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

## Districts in Nimba

In [556]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Tappita 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Tappita 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Saclepea 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Sanniquellie Mah')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Zoe-Geh')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Tuwah River')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Gbelay-Geh')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Yarpea Mah')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Yarwein Mensonoh')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Buuyao')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Bain-Garr 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Nimba') & (kece_meltdd['count']== 'Bain- Garr 2')]

#k_dd.sum(1).sum()

In [557]:
k_dd.iloc[:,:6].sum().sum()

0.0

In [558]:
k_dd.iloc[:,6:12].sum().sum()

0.0

In [559]:
k_dd.iloc[:,12:18].sum().sum()

0.0

In [560]:
k_dd.iloc[:,18:24].sum().sum()

0.0

## Districts in River Gee

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in River Gee') & (kece_meltdd['count']== 'Sarbo')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in River Gee') & (kece_meltdd['count']== 'Tienpo')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in River Gee') & (kece_meltdd['count']== 'Chedepo')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in River Gee') & (kece_meltdd['count']== 'Putupo')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in River Gee') & (kece_meltdd['count']== 'Gbeapo')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in River Gee') & (kece_meltdd['count']== 'Webbo')]

#k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

## Districts in River Cess

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in River Cess') & (kece_meltdd['count']== 'Timobo')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in River Cess') & (kece_meltdd['count']== 'Central Rivercess 1')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in River Cess') & (kece_meltdd['count']== 'Central Rivercess 2')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in River Cess') & (kece_meltdd['count']== 'Morwah')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'Districts in River Cess') & (kece_meltdd['count']== 'Yarnee')]

#k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

## Districts in Sinoe

In [ ]:
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Upper Kpanyan')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Juarzon')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Lower Kpanyan')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Butaw')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Tarjuwon')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Jeadea')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Sanquin')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Greenville')]
k_dd = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Central Kpanyan')]

#k_dd.sum(1).sum()

In [ ]:
k_dd.iloc[:,:6].sum().sum()

In [ ]:
k_dd.iloc[:,6:12].sum().sum()

In [ ]:
k_dd.iloc[:,12:18].sum().sum()

In [ ]:
k_dd.iloc[:,18:24].sum().sum()

# Table 14 ECE Enrollment by Age and Grade

In [ ]:
kece_s.head()

In [601]:
kece_s10 = kece_s.iloc[:,::3].sum()
kece_s10

How many students age less than 10 enrolled in Level I of Alternative Education  are MALES?           653.0
How many students age less than 10 enrolled in Level I of Alternative Education  are FEMALES?         755.0
How many students age between 10 to 15  enrolled in Level I of Alternative Education  are MALES?     1339.0
How many students age between 10 to 15 enrolled in Level I of Alternative Education  are FEMALES?    1206.0
How many students age between 15 to 20 enrolled in Level I of Alternative Education  are MALES?       289.0
How many students age between 15 to 20 enrolled in Level I of Alternative Education  are FEMALES?     287.0
How many students age between 20 to 25 enrolled in Level I of Alternative Education  are MALES?        45.0
How many students age between 20 to 25 enrolled in Level I of Alternative Education  are FEMALES?      43.0
How many students age between 25 to 30 enrolled in Level I of Alternative Education  are MALES?        53.0
How many students age between 25 to 30 enrolled in Level I of Alternative Education  are FEMALES?      24.0
How many students age between 30 to 35 enrolled in Level I of Alternative Education  are MALES?        12.0
How many students age between 30 to 35 enrolled in Level I of Alternative Education  are FEMALES?      31.0
How many students age greater than  35 enrolled in Level I of Alternative Education  are MALES?         9.0
How many students age greater than  35 enrolled in Level I of Alternative Education  are FEMALES?      13.0
dtype: float64

In [617]:
kece_s10[:2].sum()
kece_s10[2:4].sum()
kece_s10[4:6].sum()
kece_s10[6:8].sum()
kece_s10[8:10].sum()
kece_s10[10:12].sum()
kece_s10[12:14].sum()

22.0

In [619]:
kece_s.sum()

How many students age less than 10 enrolled in Level I of Alternative Education  are MALES?             653.0
How many students age less than 10 enrolled in Level II of Alternative Education  are MALES?            235.0
How many students age less than 10 enrolled in Level III of Alternative Education  are MALES?            37.0
How many students age less than 10 enrolled in Level I of Alternative Education  are FEMALES?           755.0
How many students age less than 10 enrolled in Level II of Alternative Education  are FEMALES?          214.0
How many students age less than 10 enrolled in Level III of Alternative Education  are FEMALES?          63.0
How many students age between 10 to 15  enrolled in Level I of Alternative Education  are MALES?       1339.0
How many students age between 10 to 15  enrolled in Level II of Alternative Education  are MALES?       892.0
How many students age between 10 to 15  enrolled in Level III of Alternative Education  are MALES?      279.0
How many students age between 10 to 15 enrolled in Level I of Alternative Education  are FEMALES?      1206.0
How many students age between 10 to 15 enrolled in Level II of Alternative Education  are FEMALES?      754.0
How many students age between 10 to 15 enrolled in Level III of Alternative Education  are FEMALES?     254.0
How many students age between 15 to 20 enrolled in Level I of Alternative Education  are MALES?         289.0
How many students age between 15 to 20 enrolled in Level II of Alternative Education  are MALES?        330.0
How many students age between 15 to 20 enrolled in Level III of Alternative Education  are MALES?       186.0
How many students age between 15 to 20 enrolled in Level I of Alternative Education  are FEMALES?       287.0
How many students age between 15 to 20 enrolled in Level II of Alternative Education  are FEMALES?      382.0
How many students age between 15 to 20 enrolled in Level III of Alternative Education  are FEMALES?     157.0
How many students age between 20 to 25 enrolled in Level I of Alternative Education  are MALES?          45.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?         48.0
How many students age between 20 to 25 enrolled in Level III of Alternative Education  are MALES?        43.0
How many students age between 20 to 25 enrolled in Level I of Alternative Education  are FEMALES?        43.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are FEMALES?       20.0
How many students age between 20 to 25 enrolled in Level III of Alternative Education  are FEMALES?      40.0
How many students age between 25 to 30 enrolled in Level I of Alternative Education  are MALES?          53.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?.1       27.0
How many students age between 25 to 30 enrolled in Level III of Alternative Education  are MALES?        27.0
How many students age between 25 to 30 enrolled in Level I of Alternative Education  are FEMALES?        24.0
How many students age between 25 to 30 enrolled in Level II of Alternative Education  are FEMALES?       15.0
How many students age between 25 to 30 enrolled in Level III of Alternative Education  are FEMALES?      21.0
How many students age between 30 to 35 enrolled in Level I of Alternative Education  are MALES?          12.0
How many students age between 30 to 35 enrolled in Level II of Alternative Education  are MALES?         13.0
How many students age between 30 to 35 enrolled in Level III of Alternative Education  are MALES?         6.0
How many students age between 30 to 35 enrolled in Level I of Alternative Education  are FEMALES?        31.0
How many students age between 30 to 35 enrolled in Level II of Alternative Education  are FE MALES?      10.0
How many students age between 30 to 35 enrolled in Level III of Alternative Education  are FEMALES?      11.0
How many students age greater than  35 enrolled in Level I of Alternative Education  are MALES?           9.0
How many students age greater than  35 enrolled in Level II of Alternative Education  are MALES?          5.0
How many students age greater than  35 enrolled in Level III of Alternative Education  are MALES?         6.0
How many students age greater than  35 enrolled in Level I of Alternative Education  are FEMALES?        13.0
How many students age greater than  35 enrolled in Level II of Alternative Education  are FEMALES?       10.0
How many students age greater than  35 enrolled in Level III of Alternative Education  are FEMALES?       7.0
dtype: float64

In [620]:
kece_s.sum()[1::3]

How many students age less than 10 enrolled in Level II of Alternative Education  are MALES?           235.0
How many students age less than 10 enrolled in Level II of Alternative Education  are FEMALES?         214.0
How many students age between 10 to 15  enrolled in Level II of Alternative Education  are MALES?      892.0
How many students age between 10 to 15 enrolled in Level II of Alternative Education  are FEMALES?     754.0
How many students age between 15 to 20 enrolled in Level II of Alternative Education  are MALES?       330.0
How many students age between 15 to 20 enrolled in Level II of Alternative Education  are FEMALES?     382.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?        48.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are FEMALES?      20.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?.1      27.0
How many students age between 25 to 30 enrolled in Level II of Alternative Education  are FEMALES?      15.0
How many students age between 30 to 35 enrolled in Level II of Alternative Education  are MALES?        13.0
How many students age between 30 to 35 enrolled in Level II of Alternative Education  are FE MALES?     10.0
How many students age greater than  35 enrolled in Level II of Alternative Education  are MALES?         5.0
How many students age greater than  35 enrolled in Level II of Alternative Education  are FEMALES?      10.0
dtype: float64

In [636]:
kece_s.sum()[1::3][:2].sum()

449.0

In [637]:
kece_s.sum()[1::3][2:4].sum()

1646.0

In [638]:
kece_s.sum()[1::3][4:6].sum()

712.0

In [639]:
kece_s.sum()[1::3][6:8].sum()

68.0

In [640]:
kece_s.sum()[1::3][8:10].sum()

42.0

In [641]:
kece_s.sum()[1::3][10:12].sum()

23.0

In [642]:
kece_s.sum()[1::3][12:14].sum()

15.0

In [621]:
kece_s.sum()[2::3]

How many students age less than 10 enrolled in Level III of Alternative Education  are MALES?           37.0
How many students age less than 10 enrolled in Level III of Alternative Education  are FEMALES?         63.0
How many students age between 10 to 15  enrolled in Level III of Alternative Education  are MALES?     279.0
How many students age between 10 to 15 enrolled in Level III of Alternative Education  are FEMALES?    254.0
How many students age between 15 to 20 enrolled in Level III of Alternative Education  are MALES?      186.0
How many students age between 15 to 20 enrolled in Level III of Alternative Education  are FEMALES?    157.0
How many students age between 20 to 25 enrolled in Level III of Alternative Education  are MALES?       43.0
How many students age between 20 to 25 enrolled in Level III of Alternative Education  are FEMALES?     40.0
How many students age between 25 to 30 enrolled in Level III of Alternative Education  are MALES?       27.0
How many students age between 25 to 30 enrolled in Level III of Alternative Education  are FEMALES?     21.0
How many students age between 30 to 35 enrolled in Level III of Alternative Education  are MALES?        6.0
How many students age between 30 to 35 enrolled in Level III of Alternative Education  are FEMALES?     11.0
How many students age greater than  35 enrolled in Level III of Alternative Education  are MALES?        6.0
How many students age greater than  35 enrolled in Level III of Alternative Education  are FEMALES?      7.0
dtype: float64

In [643]:
kece_s.sum()[2::3][:2].sum()

100.0

In [644]:
kece_s.sum()[2::3][2:4].sum()

533.0

In [645]:
kece_s.sum()[2::3][4:6].sum()

343.0

In [646]:
kece_s.sum()[2::3][6:8].sum()

83.0

In [647]:
kece_s.sum()[2::3][8:10].sum()

48.0

In [648]:
kece_s.sum()[2::3][10:12].sum()

17.0

In [649]:
kece_s.sum()[2::3][12:14].sum()

13.0

# Table 15 ECE Enrollment by Age, Grade and Gender

In [650]:
kece_s.sum()[::3]

How many students age less than 10 enrolled in Level I of Alternative Education  are MALES?           653.0
How many students age less than 10 enrolled in Level I of Alternative Education  are FEMALES?         755.0
How many students age between 10 to 15  enrolled in Level I of Alternative Education  are MALES?     1339.0
How many students age between 10 to 15 enrolled in Level I of Alternative Education  are FEMALES?    1206.0
How many students age between 15 to 20 enrolled in Level I of Alternative Education  are MALES?       289.0
How many students age between 15 to 20 enrolled in Level I of Alternative Education  are FEMALES?     287.0
How many students age between 20 to 25 enrolled in Level I of Alternative Education  are MALES?        45.0
How many students age between 20 to 25 enrolled in Level I of Alternative Education  are FEMALES?      43.0
How many students age between 25 to 30 enrolled in Level I of Alternative Education  are MALES?        53.0
How many students age between 25 to 30 enrolled in Level I of Alternative Education  are FEMALES?      24.0
How many students age between 30 to 35 enrolled in Level I of Alternative Education  are MALES?        12.0
How many students age between 30 to 35 enrolled in Level I of Alternative Education  are FEMALES?      31.0
How many students age greater than  35 enrolled in Level I of Alternative Education  are MALES?         9.0
How many students age greater than  35 enrolled in Level I of Alternative Education  are FEMALES?      13.0
dtype: float64

In [651]:
kece_s.sum()[1::3]

How many students age less than 10 enrolled in Level II of Alternative Education  are MALES?           235.0
How many students age less than 10 enrolled in Level II of Alternative Education  are FEMALES?         214.0
How many students age between 10 to 15  enrolled in Level II of Alternative Education  are MALES?      892.0
How many students age between 10 to 15 enrolled in Level II of Alternative Education  are FEMALES?     754.0
How many students age between 15 to 20 enrolled in Level II of Alternative Education  are MALES?       330.0
How many students age between 15 to 20 enrolled in Level II of Alternative Education  are FEMALES?     382.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?        48.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are FEMALES?      20.0
How many students age between 20 to 25 enrolled in Level II of Alternative Education  are MALES?.1      27.0
How many students age between 25 to 30 enrolled in Level II of Alternative Education  are FEMALES?      15.0
How many students age between 30 to 35 enrolled in Level II of Alternative Education  are MALES?        13.0
How many students age between 30 to 35 enrolled in Level II of Alternative Education  are FE MALES?     10.0
How many students age greater than  35 enrolled in Level II of Alternative Education  are MALES?         5.0
How many students age greater than  35 enrolled in Level II of Alternative Education  are FEMALES?      10.0
dtype: float64

In [652]:
kece_s.sum()[2::3]

How many students age less than 10 enrolled in Level III of Alternative Education  are MALES?           37.0
How many students age less than 10 enrolled in Level III of Alternative Education  are FEMALES?         63.0
How many students age between 10 to 15  enrolled in Level III of Alternative Education  are MALES?     279.0
How many students age between 10 to 15 enrolled in Level III of Alternative Education  are FEMALES?    254.0
How many students age between 15 to 20 enrolled in Level III of Alternative Education  are MALES?      186.0
How many students age between 15 to 20 enrolled in Level III of Alternative Education  are FEMALES?    157.0
How many students age between 20 to 25 enrolled in Level III of Alternative Education  are MALES?       43.0
How many students age between 20 to 25 enrolled in Level III of Alternative Education  are FEMALES?     40.0
How many students age between 25 to 30 enrolled in Level III of Alternative Education  are MALES?       27.0
How many students age between 25 to 30 enrolled in Level III of Alternative Education  are FEMALES?     21.0
How many students age between 30 to 35 enrolled in Level III of Alternative Education  are MALES?        6.0
How many students age between 30 to 35 enrolled in Level III of Alternative Education  are FEMALES?     11.0
How many students age greater than  35 enrolled in Level III of Alternative Education  are MALES?        6.0
How many students age greater than  35 enrolled in Level III of Alternative Education  are FEMALES?      7.0
dtype: float64

In [ ]:
kece_s7#.sum()

In [ ]:
kece_s8#.sum()

In [ ]:
kece_s9

# Table 16: ECE Repeater by School Types

In [654]:
kece_r = pd.concat([kcensus.iloc[:,[2,39]],kcensus.iloc[:,656:662]], axis=1).groupby('Type of school').sum()
kece_r

,How many MALE students in Alternative Education Level I are Repeaters?,How many FEMALE students in Alternative Education Level I are Repeaters?,How many MALE students in Alternative Education Level II are Repeaters?,How many FEMALE students in Alternative Education Level II are Repeaters?,How many MALE students in Alternative Education Level III are Repeaters?,How many FEMALE students in Alternative Education Level III are Repeaters?
Type of school,,,,,,
Community,0.0,0.0,0.0,0.0,0.0,0.0
Faith-based,0.0,0.0,0.0,0.0,0.0,0.0
Private,3.0,3.0,0.0,3.0,0.0,2.0
Public,446.0,332.0,237.0,166.0,52.0,62.0

# Table 17: ECE Repeaters by County, Gender and Grade

In [653]:
kece_rc = pd.concat([kcensus.iloc[:,[2,39]],kcensus.iloc[:,656:662]], axis=1).groupby('County').sum()
kece_rc

,How many MALE students in Alternative Education Level I are Repeaters?,How many FEMALE students in Alternative Education Level I are Repeaters?,How many MALE students in Alternative Education Level II are Repeaters?,How many FEMALE students in Alternative Education Level II are Repeaters?,How many MALE students in Alternative Education Level III are Repeaters?,How many FEMALE students in Alternative Education Level III are Repeaters?
County,,,,,,
Bomi,0.0,0.0,0.0,0.0,0.0,0.0
Bong,20.0,20.0,18.0,5.0,5.0,6.0
Gbarpolu,0.0,0.0,0.0,0.0,0.0,0.0
Grand Bassa,45.0,33.0,43.0,25.0,3.0,1.0
Grand Cape Mount,0.0,0.0,0.0,0.0,0.0,0.0
Grand Gedeh,0.0,0.0,0.0,0.0,0.0,0.0
Grand Kru,0.0,0.0,0.0,0.0,0.0,0.0
Lofa,69.0,52.0,25.0,13.0,6.0,4.0
Margibi,63.0,29.0,19.0,14.0,0.0,0.0
Maryland,0.0,0.0,0.0,0.0,0.0,0.0
Montserrado 1,10.0,13.0,3.0,9.0,0.0,2.0
Montserrado 2,14.0,19.0,9.0,8.0,4.0,2.0
Nimba,228.0,169.0,120.0,95.0,34.0,49.0
River Gee,0.0,0.0,0.0,0.0,0.0,0.0
Rivercess,0.0,0.0,0.0,0.0,0.0,0.0
Sinoe,0.0,0.0,0.0,0.0,0.0,0.0