In [77]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
pd.set_option('display.max_rows',7000)
pd.set_option('display.max_columns',7000)

In [78]:
kcensus = pd.read_csv('kobo_data.csv')
tcensus = pd.read_csv('tamma_data.csv')
kcensus['How many FEMALE students  above AGE 8 YEARS OLD are in Pre-Kindergarten?'][3776]= 10
kcensus['How many FEMALE students  above AGE 8 YEARS OLD are in Pre-Kindergarten?'][3776]

/home/alton/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (5,6,10,11,648,745,746,753,772,773,796,801,806,811,816,821,826,831,836,841,846,851,856,861,866,871,876,881,886,891,896,901,902,903,904,974,1197,1222,1241,1250,1261,1269,1299,1399,1401,1403,1405,1408,1409,1413,1414,1415,1419,1421,1423,1425,1427,1429,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1452) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/home/alton/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (2,12,13,14,115,893,995,1019,1020,1021,1022,1023) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
<ipython-input-78-8fec5fc5cfc6>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kcensus['How many FEMALE students  above AGE 8 YEARS OLD are in Pre-Kindergarten?'][3776]= 10

10.0

In [79]:
kstaff = pd.read_csv('kobo_staff.csv')
tstaff = pd.read_csv('tamma_staff.csv')
kstaff.head()

,Surname,Given name,Sex,Year of birth,Payroll Number,Current Position,Current Position/Teacher,Current Position/Principal,Current Position/Vice Principal Administration,Current Position/Vice Principal Instruction,Current Position/Registrar,Current Position/Custodian,Current Position/Others,Specify,Level(s) teaching,Level(s) teaching/ECE,Level(s) teaching/Primary (Lower Basic),Level(s) teaching/Junior Secondary (Upper Basic),Level(s) teaching/Senior High,Level(s) teaching/ALP,Level(s) teaching/ABE,Level(s) teaching/TVET,Level(s) teaching/Not teaching,Professional qualification,Academic qualification,Subject teaching,Subject teaching/Language,Subject teaching/Mathematics,Subject teaching/Science,Subject teaching/Social Studies,Subject teaching/Others,specify,Number of years in teaching position,Source of salary,Total number of teaching staff,index,School Name,County,District in Bong County,District in Gbarpolu,District in River Gee,District in Sinoe,District in Lofa,District in Nimba,District in Grand Cape Mount,District in Maryland,District in Margibi,District in Bomi,District in Grand Bassa,District in Montserrado 2,District in Montserrado 1,Districts in Grand Kru,Districts in Grand Gedeh,Districts in River Cess,Type of school
0,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,147,Robertsport Preparatory School,Grand Cape Mount,NaN,NaN,NaN,NaN,NaN,NaN,Tallah Tombay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Private
1,0,0,Male,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2153,Community of hope mission school,Rivercess,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morwah,Faith-based
2,0,0,Male,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2153,Community of hope mission school,Rivercess,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morwah,Faith-based
3,Maxwell Yalawood,1975,Male,NaN,NaN,Principal,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,ALP,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,No teaching certificate,Any Bachelor's degree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Volunteer without pay,7.0,3610,The Creative Elementary School System,Montserrado 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Left bank 1B,NaN,NaN,NaN,NaN,Faith-based
4,MCCARTHY BABARA,1976,Female,1976,NaN,Teacher Custodian,1.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,ECE,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No teaching certificate,Completed secondary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Private institution,8.0,4519,IN GOD WE TRUST MINISTRIES CHRISTIAN ACADEMY,Montserrado 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Greater Monrovia 1A,NaN,NaN,NaN,Faith-based

In [80]:
kpri_student =kcensus.iloc[:,141:397]
kpri_student.head()

,Which session or sessions does the school operate for Primary?,Which session or sessions does the school operate for Primary?/Morning,Which session or sessions does the school operate for Primary?/Afternoon,Which session or sessions does the school operate for Primary?/Evening,What is the total number of Primary school students?,What is the total number of Primary students that are Females?,What is the total number of primary students that are Males?,What is the total number of Primary teachers that are Males?,What is the total number of Primary teachers that are Females?,How many teachers are teaching only one grade at Primary level that are MALES?,How many teachers are teaching only one grade at the Primary level that are FEMALES?,How many additional teachers does the school need at the Primary level?,How many MALE students in Grade 1 are Repeaters?,How many FEMALE students in Grade 1 are Repeaters?,How many FEMALE students in Grade 2 are Repeaters?,How many MALE students in Grade 2 are Repeaters?,How many MALE students in Grade 3 are Repeaters?,How many FEMALE students in Grade 3 are Repeaters?,How many MALE students in Grade 4 are Repeaters?,How many FEMALE students in Grade 4 are Repeaters?,How many MALE students in Grade 5 are Repeaters?,How many FEMALE students in Grade 5 are Repeaters?,How many MALE students in Grade 6 are Repeaters?,How many FEMALE students in Grade 6 are Repeaters?,How many MALE students in Grade 1 are Visually impaired ?,How many FEMALE students in Grade 1 are Visually impaired?,How many MALE students in Grade 2 are Visually impaired ?,How many FEMALE students in Grade 2 are Visually impaired?,How many MALE students in Grade 3 are Visually impaired ?,How many FEMALE students in Grade 3 are Visually impaired?,How many MALE students in Grade 4 are Visually impaired ?,How many FEMALE students in Grade 4 are Visually impaired?,How many MALE students in Grade 5 are Visually impaired ?,How many FEMALE students in Grade 5 are Visually impaired?,How many MALE students in Grade 6 are Visually impaired ?,How many FEMALE students in Grade 6 are Visually impaired?,How many MALE students in Grade 1 have hearing impairment?,How many FEMALE students in Grade 1 have hearing impairment?,How many MALE students in Grade 2 have hearing impairment?,How many FEMALE students in Grade 2 have hearing impairment?,How many MALE students in Grade 3 have hearing impairment?,How many FEMALE students in Grade 3 have hearing impairment?,How many MALE students in Grade 4 have hearing impairment?,How many FEMALE students in Grade 4 have hearing impairment?,How many MALE students in Grade 5 have hearing impairment?,How many FEMALE students in Grade 5 have hearing impairment?,How many FEMALE students in Grade 6 have hearing impairment?,How many MALE students in Grade 6 have hearing impairment?,How many MALE students in Grade 1 have other physical disabilities?,How many FEMALE students in Grade 1 have other physical disabilities?,How many MALE students in Grade 2 have other physical disabilities?,How many FEMALE students in Grade 2 have other physical disabilities?,How many MALE students in Grade 3 have other physical disabilities?,How many FEMALE students in Grade 3 have other physical disabilities?,How many MALE students in Grade 4 have other physical disabilities?,How many FEMALE students in Grade 4 have other physical disabilities?,How many MALE students in Grade 5 have other physical disabilities?,How many FEMALE students in Grade 5 have other physical disabilities?,How many MALE students in Grade 6 have other physical disabilities?,How many FEMALE students in Grade 6 have other physical disabilities?,How many MALE students in Grade 1 have other mental disability or learning difficulty?,How many FEMALE students in Grade 1 have other mental disability or learning difficulty?,How many MALE students in Grade 2 have other mental disability or learning difficulty?,How many FEMALE students in Grade 2 have other mental disability or learning difficulty?,How many MALE students in Grade 3 have other mental disability or learning difficulty?,How many FEMALE students in Grade 3 have other mental disability or learning difficulty?,How many MALE students in Grade 4 have other mental disability or learning difficulty?,How many FEMALE students in Grade 4 have other mental disability or learning difficulty?,How many MALE students in Grade 5 have other mental disability or learning difficulty?,How many FEMALE students in Grade 5 have other mental disability or learning difficulty?,How many MALE students in Grade 6 have other mental disability or learning difficulty?,How many FEMALE students in Grade 6 have other mental disability or learning difficulty?,How many students enrolled in Grade 1 are MALES?,How many students enrolled in Grade 2 are MALES?,How many students enrolled in Grade 3 are MALES?,How many students enrolled in Grade 4 are MALES?,How many students enrolled in Grade 5 are MALES?,How many students enrolled in Grade 6 are MALES?,How many students enrolled in Grade 1 are FEMALES?,How many students enrolled in Grade 2 are FEMALES?,How many students enrolled in Grade 3 are FEMALES?,How many students enrolled in Grade 4 are FEMALES?,How many students enrolled in Grade 5 are FEMALES?,How many students enrolled in Grade 6 are FEMALES?,How many Sections do Grade 1 has?,How many Sections do Grade 2 has?,How many Sections do Grade 3 has?,How many Sections do Grade 4 has?,How many Sections do Grade 5 has?,How many Sections do Grade 6 has?,How many students repeating Grade 1 are MALES?,How many students repeating Grade 2 are MALES?,How many students repeating Grade 3 are MALES?,How many students repeating Grade 4 are MALES?,How many students repeating Grade 6 are MALES?,How many students repeating Grade 5 are MALES?,How many students repeating Grade 1 are FEMALES?,How many students repeating Grade 2 are FEMALES?,How many students repeating Grade 3 are FEMALES?,How many students repeating Grade 4 are FEMALES?,How many students repeating Grade 5 are FEMALES?,How many students repeating Grade 6 are FEMALES?,How many students below Age 6 in Grade 1 are MALES?,How many students below Age 6 in Grade 2 are MALES?,How many students below Age 6 in Grade 3 are MALES?,How many students below Age 6 in Grade 4 are MALES?,How many students below Age 6 in Grade 5 are MALES?,How many students below Age 6 in Grade 6 are MALES?,How many students below Age 6 in Grade 1 are FEMALES?,How many students below Age 6 in Grade 2 are FEMALES?,How many students below Age 6 in Grade 3 are FEMALES?,How many students below Age 6 in Grade 4 are FEMALES?,How many students below Age 6 in Grade 5 are FEMALES?,How many students below Age 6 in Grade 6 are FEMALES?,How many students Age 6 years old in Grade 1 are MALES?,How many students Age 6 years old in Grade 2 are MALES?,How many students Age 6 years old in Grade 3 are MALES?,How many students Age 6 years old in Grade 4 are MALES?,How many students Age 6 years old in Grade 5 are MALES?,How many students Age 6 years old in Grade 6 are MALES?,How many students Age 6 years old in Grade 1 are FEMALES?,How many students Age 6 years old in Grade 2 are FEMALES?,How many students Age 6 years old in Grade 3 are FEMALES?,How many students Age 6 years old in Grade 4 are FEMALES?,How many students Age 6 years old in Grade 5 are FEMALES?,How many students Age 6 years old in Grade 6 are FEMALES?,How many students Age 7 years old in Grade 1 are MALES?,How many students Age 7 years old in Grade 2 are MALES?,How many students Age 7 years old in Grade 3 are MALES?,How many students Age 7 years old in Grade 4 are MALES?,How many students Age 7 years old in Grade 5 are MALES?,How many students Age 7 years old in Grade 6 are MALES?,How many students Age 7 years old in Grade 1 are FEMALES?,How many students Age 7 years old in Grade 2 are FEMALES?,How many students Age 7 years old in Grade 3 are FEMALES?,How many students Age 7 years old in Grade 4 are FEMALES?,How many students Age 7 years old in Grade 5 are FEMALES?,How many students Age 7 years old in Grade 6 are FEMALES?,How many students Age 8 years old in Grade 1 are MALES?,How many students Age 8 years old in Grade 2 are MALES?,How many students Age 8 years old in Grade 3 are MALES?,How many students Age 8 years old in Grade 4 are MALES?,How many students Age 8 years old in Grade 5 are MALES?,How many students Age 8 years old in Grade 6 are MALES?,How many students Age 8 years old in Grade 1 are FEMALES?,How many students Age 8 years old in Grade 2 are FEMALES?,How many students Age 8 years old in Grade 3 are FEMALES?,How many students Age 8 years old in Grade 4 are FEMALES?,How many students Age 8 years old in Grade 5 are FEMALES?,How many students Age 8 years old in Grade 6 are FEMALES?,How many students Age 9 years old in Grade 1 are MALES?,How many students Age 9 years old in Grade 2 are MALES?,How many students Age 9 years old in Grade 3 are MALES?,How many students Age 9 years old in Grade 4 are MALES?,How many students Age 9 years old in Grade 5 are MALES?,How many students Age 9 years old in Grade 6 are MALES?,How many students Age 9 years old in Grade 1 are FEMALES?,How many students Age 9 years old in Grade 2 are FEMALES?,How many students Age 9 years old in Grade 3 are FEMALES?,How many students Age 9 years old in Grade 4 are FEMALES?,How many students Age 9 years old in Grade 5 are FEMALES?,How many students Age 9 years old in Grade 6 are FEMALES?,How many students Age 10 years old in Grade 1 are MALES?,How many students Age 10 years old in Grade 2 are MALES?,How many students Age 10 years old in Grade 3 are MALES?,How many students Age 10 years old in Grade 4 are MALES?,How many students Age 10 years old in Grade 5 are MALES?,How many students Age 10 years old in Grade 6 are MALES?,How many students Age 10 years old in Grade 1 are FEMALES?,How many students Age 10 years old in Grade 2 are FEMALES?,How many students Age 10 years old in Grade 3 are FEMALES?,How many students Age 10 years old in Grade 4 are FEMALES?,How many students Age 10 years old in Grade 5 are FEMALES?,How many students Age 10 years old in Grade 6 are FEMALES?,How many students Age 11 years old in Grade 1 are MALES?,How many students Age 11 years old in Grade 2 are MALES?,How many students Age 11 years old in Grade 3 are MALES?,How many students Age 11 years old in Grade 4 are MALES?,How many students Age 11 years old in Grade 5 are MALES?,How many students Age 11 years old in Grade 6 are MALES?,How many students Age 11 years old in Grade 1 are FEMALES?,How many students Age 11 years old in Grade 2 are FEMALES?,How many students Age 11 years old in Grade 3 are FEMALES?,How many students Age 11 years old in Grade 4 are FEMALES?,How many students Age 11 years old in Grade 5 are FEMALES?,How many students Age 11 years old in Grade 6 are FEMALES?,How many students Age 12 years old in Grade 1 are MALES?,How many students Age 12 years old in Grade 2 are MALES?,How many students Age 12 years old in Grade 3 are MALES?,How many students Age 12 years old in Grade 4 are MALES?,How many students Age 12 years old in Grade 5 are MALES?,How many students Age 12 years old in Grade 6 are MALES?,How many students Age 12 years old in Grade 1 are FEMALES?,How many students Age 12 years old in Grade 2 are FEMALES?,How many students Age 12 years old in Grade 3 are FEMALES?,How many students 12 years old in Grade 4 are FEMALES?,How many students Age 12 years old in Grade 5 are FEMALES?,How many students Age 12 years old in Grade 6 are FEMALES?,How many students Age 13 years old in Grade 1 are MALES?,How many students Age 13 years old in Grade 2 are MALES?,How many students Age 13 years old in Grade 3 are MALES?,How many students Age 13 years old in Grade 4 are MALES?,How many students Age 13 years old in Grade 5 are MALES?,How many students Age 13 years old in Grade 6 are MALES?,How many students Age 13 years old in Grade 1 are FEMALES?,How many students Age 13 years old in Grade 2 are FEMALES?,How many students Age 13 years old in Grade 3 are FEMALES?,How many students Age 13 years old in Grade 4 are FEMALES?,How many students Age 13 years old in Grade 5 are FEMALES?,How many students Age 13 years old in Grade 6 are FEMALES?,How many students Age 14 years old in Grade 1 are MALES?,How many students Age 14 years old in Grade 2 are MALES?,How many students Age 14 years old in Grade 3 are MALES?,How many students Age 14 years old in Grade 4 are MALES?,How many students Age 14 years old in Grade 5 are MALES?,How many students Age 14 years old in Grade 6 are MALES?,How many students Age 14 years old in Grade 1 are FEMALES?,How many students Age 14 years old in Grade 2 are FEMALES?,How many students Age 14 years old in Grade 3 are FEMALES?,How many students Age 14 years old in Grade 4 are FEMALES?,How many students Age 14 years old in Grade 5 are FEMALES?,How many students Age 14 years old in Grade 6 are FEMALES?,How many students Age 15 years old in Grade 1 are MALES?,How many students Age 15 years old in Grade 2 are MALES?,How many students Age 15 years old in Grade 3 are MALES?,How many students Age 15 years old in Grade 4 are MALES?,How many students Age 15 years old in Grade 5 are MALES?,How many students Age 15 years old in Grade 6 are MALES?,How many students Age 15 years old in Grade 1 are FEMALES?,How many students Age 15 years old in Grade 2 are FEMALES?,How many students Age 15 years old in Grade 3 are FEMALES?,How many students Age 15 years old in Grade 4 are FEMALES?,How many students age 15 Years old in Grade 5 are FEMALES?,How many students age 15 Years old in Grade 6 are FEMALES?,How many students above age 15 Years old in Grade 1 are MALES?,How many students above age 15 Years old in Grade 2 are MALES?,How many students above age 15 Years old in Grade 3 are MALES?,How many students above age 15 Years old in Grade 4 are MALES?,How many students above age 15 Years old in Grade 5 are MALES?,How many students above age 15 Years old in Grade 6 are MALES?,How many students above Age 15 in Grade 1 are FEMALES?,How many students above Age 15 in Grade 2 are FEMALES?,How many students above Age 15 in Grade 3 are FEMALES?,How many students above Age 15 in Grade 4 are FEMALES?,How many students above Age 15 in Grade 5 are FEMALES?,How many students above Age 15 in Grade 6 are FEMALES?,How many students who graduated from Grade 6 last Academic year are MALES,How many students who graduated from Grade 6 last Academic year are FEMALES?,What is total intake in Grade 1?,What is total intake in Grade 2?,What is total intake in Grade 3?,What is total intake in Grade 4?,What is total intake in Grade 5?,What is total intake in Grade 6?,How many male student graduated from Grade 6 last academic year?,How many female student graduated from Grade 6 last academic year?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Morning,1.0,0.0,0.0,93.0,48.0,44.0,4.0,3.0,0.0,0.0,4.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,9.0,8.0,5.0,7.0,2.0,10.0,16.0,20.0,13.0,13.0,8.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,4.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0,4.0,2.0,0.0,0.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,0.0,0.0,2.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,2.0,2.0,3.0,2.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,2.0,23.0,16.0,20.0,13.0,13.0,8.0,6.0,2.0
2,Morning,1.0,0.0,0.0,32.0,11.0,21.0,0.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,3.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,9.0,4.0,0.0,0.0,0.0,5.0,3.0,3.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,13.0,12.0,7.0,0.0,0.0,0.0,NaN,NaN
3,Morning,1.0,0.0,0.0,139.0,60.0,79.0,1.0,3.0,NaN,1.0,NaN,2.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,15.0,21.0,25.0,15.0,17.0,16.0,20.0,24.0,25.0,18.0,25.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,6.0,5.0,8.0,NaN,NaN,NaN,6.0,7.0,8.0,NaN,NaN,NaN,5.0,5.0,8.0,4.0,NaN,NaN,5.0,7.0,3.0,4.0,NaN,NaN,NaN,4.0,1.0,10.0,NaN,NaN,NaN,4.0,1.0,10.0,NaN,NaN,NaN,NaN,4.0,5.0,NaN,2.0,NaN,2.0,12.0,5.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2.0,2.0,10.0,NaN,NaN,NaN,4.0,10.0,10.0,NaN,NaN,NaN,4.0,10.0,12.0,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,10.0,32.0,35.0,45.0,54.0,33.0,42.0,9.0,10.0

In [81]:
kpri_age = kpri_student.iloc[:,102:246]
kpri_age.head()

,How many students below Age 6 in Grade 1 are MALES?,How many students below Age 6 in Grade 2 are MALES?,How many students below Age 6 in Grade 3 are MALES?,How many students below Age 6 in Grade 4 are MALES?,How many students below Age 6 in Grade 5 are MALES?,How many students below Age 6 in Grade 6 are MALES?,How many students below Age 6 in Grade 1 are FEMALES?,How many students below Age 6 in Grade 2 are FEMALES?,How many students below Age 6 in Grade 3 are FEMALES?,How many students below Age 6 in Grade 4 are FEMALES?,How many students below Age 6 in Grade 5 are FEMALES?,How many students below Age 6 in Grade 6 are FEMALES?,How many students Age 6 years old in Grade 1 are MALES?,How many students Age 6 years old in Grade 2 are MALES?,How many students Age 6 years old in Grade 3 are MALES?,How many students Age 6 years old in Grade 4 are MALES?,How many students Age 6 years old in Grade 5 are MALES?,How many students Age 6 years old in Grade 6 are MALES?,How many students Age 6 years old in Grade 1 are FEMALES?,How many students Age 6 years old in Grade 2 are FEMALES?,How many students Age 6 years old in Grade 3 are FEMALES?,How many students Age 6 years old in Grade 4 are FEMALES?,How many students Age 6 years old in Grade 5 are FEMALES?,How many students Age 6 years old in Grade 6 are FEMALES?,How many students Age 7 years old in Grade 1 are MALES?,How many students Age 7 years old in Grade 2 are MALES?,How many students Age 7 years old in Grade 3 are MALES?,How many students Age 7 years old in Grade 4 are MALES?,How many students Age 7 years old in Grade 5 are MALES?,How many students Age 7 years old in Grade 6 are MALES?,How many students Age 7 years old in Grade 1 are FEMALES?,How many students Age 7 years old in Grade 2 are FEMALES?,How many students Age 7 years old in Grade 3 are FEMALES?,How many students Age 7 years old in Grade 4 are FEMALES?,How many students Age 7 years old in Grade 5 are FEMALES?,How many students Age 7 years old in Grade 6 are FEMALES?,How many students Age 8 years old in Grade 1 are MALES?,How many students Age 8 years old in Grade 2 are MALES?,How many students Age 8 years old in Grade 3 are MALES?,How many students Age 8 years old in Grade 4 are MALES?,How many students Age 8 years old in Grade 5 are MALES?,How many students Age 8 years old in Grade 6 are MALES?,How many students Age 8 years old in Grade 1 are FEMALES?,How many students Age 8 years old in Grade 2 are FEMALES?,How many students Age 8 years old in Grade 3 are FEMALES?,How many students Age 8 years old in Grade 4 are FEMALES?,How many students Age 8 years old in Grade 5 are FEMALES?,How many students Age 8 years old in Grade 6 are FEMALES?,How many students Age 9 years old in Grade 1 are MALES?,How many students Age 9 years old in Grade 2 are MALES?,How many students Age 9 years old in Grade 3 are MALES?,How many students Age 9 years old in Grade 4 are MALES?,How many students Age 9 years old in Grade 5 are MALES?,How many students Age 9 years old in Grade 6 are MALES?,How many students Age 9 years old in Grade 1 are FEMALES?,How many students Age 9 years old in Grade 2 are FEMALES?,How many students Age 9 years old in Grade 3 are FEMALES?,How many students Age 9 years old in Grade 4 are FEMALES?,How many students Age 9 years old in Grade 5 are FEMALES?,How many students Age 9 years old in Grade 6 are FEMALES?,How many students Age 10 years old in Grade 1 are MALES?,How many students Age 10 years old in Grade 2 are MALES?,How many students Age 10 years old in Grade 3 are MALES?,How many students Age 10 years old in Grade 4 are MALES?,How many students Age 10 years old in Grade 5 are MALES?,How many students Age 10 years old in Grade 6 are MALES?,How many students Age 10 years old in Grade 1 are FEMALES?,How many students Age 10 years old in Grade 2 are FEMALES?,How many students Age 10 years old in Grade 3 are FEMALES?,How many students Age 10 years old in Grade 4 are FEMALES?,How many students Age 10 years old in Grade 5 are FEMALES?,How many students Age 10 years old in Grade 6 are FEMALES?,How many students Age 11 years old in Grade 1 are MALES?,How many students Age 11 years old in Grade 2 are MALES?,How many students Age 11 years old in Grade 3 are MALES?,How many students Age 11 years old in Grade 4 are MALES?,How many students Age 11 years old in Grade 5 are MALES?,How many students Age 11 years old in Grade 6 are MALES?,How many students Age 11 years old in Grade 1 are FEMALES?,How many students Age 11 years old in Grade 2 are FEMALES?,How many students Age 11 years old in Grade 3 are FEMALES?,How many students Age 11 years old in Grade 4 are FEMALES?,How many students Age 11 years old in Grade 5 are FEMALES?,How many students Age 11 years old in Grade 6 are FEMALES?,How many students Age 12 years old in Grade 1 are MALES?,How many students Age 12 years old in Grade 2 are MALES?,How many students Age 12 years old in Grade 3 are MALES?,How many students Age 12 years old in Grade 4 are MALES?,How many students Age 12 years old in Grade 5 are MALES?,How many students Age 12 years old in Grade 6 are MALES?,How many students Age 12 years old in Grade 1 are FEMALES?,How many students Age 12 years old in Grade 2 are FEMALES?,How many students Age 12 years old in Grade 3 are FEMALES?,How many students 12 years old in Grade 4 are FEMALES?,How many students Age 12 years old in Grade 5 are FEMALES?,How many students Age 12 years old in Grade 6 are FEMALES?,How many students Age 13 years old in Grade 1 are MALES?,How many students Age 13 years old in Grade 2 are MALES?,How many students Age 13 years old in Grade 3 are MALES?,How many students Age 13 years old in Grade 4 are MALES?,How many students Age 13 years old in Grade 5 are MALES?,How many students Age 13 years old in Grade 6 are MALES?,How many students Age 13 years old in Grade 1 are FEMALES?,How many students Age 13 years old in Grade 2 are FEMALES?,How many students Age 13 years old in Grade 3 are FEMALES?,How many students Age 13 years old in Grade 4 are FEMALES?,How many students Age 13 years old in Grade 5 are FEMALES?,How many students Age 13 years old in Grade 6 are FEMALES?,How many students Age 14 years old in Grade 1 are MALES?,How many students Age 14 years old in Grade 2 are MALES?,How many students Age 14 years old in Grade 3 are MALES?,How many students Age 14 years old in Grade 4 are MALES?,How many students Age 14 years old in Grade 5 are MALES?,How many students Age 14 years old in Grade 6 are MALES?,How many students Age 14 years old in Grade 1 are FEMALES?,How many students Age 14 years old in Grade 2 are FEMALES?,How many students Age 14 years old in Grade 3 are FEMALES?,How many students Age 14 years old in Grade 4 are FEMALES?,How many students Age 14 years old in Grade 5 are FEMALES?,How many students Age 14 years old in Grade 6 are FEMALES?,How many students Age 15 years old in Grade 1 are MALES?,How many students Age 15 years old in Grade 2 are MALES?,How many students Age 15 years old in Grade 3 are MALES?,How many students Age 15 years old in Grade 4 are MALES?,How many students Age 15 years old in Grade 5 are MALES?,How many students Age 15 years old in Grade 6 are MALES?,How many students Age 15 years old in Grade 1 are FEMALES?,How many students Age 15 years old in Grade 2 are FEMALES?,How many students Age 15 years old in Grade 3 are FEMALES?,How many students Age 15 years old in Grade 4 are FEMALES?,How many students age 15 Years old in Grade 5 are FEMALES?,How many students age 15 Years old in Grade 6 are FEMALES?,How many students above age 15 Years old in Grade 1 are MALES?,How many students above age 15 Years old in Grade 2 are MALES?,How many students above age 15 Years old in Grade 3 are MALES?,How many students above age 15 Years old in Grade 4 are MALES?,How many students above age 15 Years old in Grade 5 are MALES?,How many students above age 15 Years old in Grade 6 are MALES?,How many students above Age 15 in Grade 1 are FEMALES?,How many students above Age 15 in Grade 2 are FEMALES?,How many students above Age 15 in Grade 3 are FEMALES?,How many students above Age 15 in Grade 4 are FEMALES?,How many students above Age 15 in Grade 5 are FEMALES?,How many students above Age 15 in Grade 6 are FEMALES?
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,4.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0,4.0,2.0,0.0,0.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,0.0,0.0,2.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,2.0,2.0,3.0,2.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,6.0,5.0,8.0,NaN,NaN,NaN,6.0,7.0,8.0,NaN,NaN,NaN,5.0,5.0,8.0,4.0,NaN,NaN,5.0,7.0,3.0,4.0,NaN,NaN,NaN,4.0,1.0,10.0,NaN,NaN,NaN,4.0,1.0,10.0,NaN,NaN,NaN,NaN,4.0,5.0,NaN,2.0,NaN,2.0,12.0,5.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2.0,2.0,10.0,NaN,NaN,NaN,4.0,10.0,10.0,NaN,NaN,NaN,4.0,10.0,12.0,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,5.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [82]:
kpri_student_dic = pd.Series(kpri_student.columns)
kpri_student_dic.to_csv('kpri_student_dic.csv', index = False)

In [83]:
kpri_c = kcensus.iloc[:,[2]]
kpri_o = kcensus.iloc[:,[39]]
kpri_s = kpri_student.iloc[:,102:246]

In [84]:
kpri_cos =pd.concat([kpri_c, kpri_o, kpri_s], axis = 1).groupby(['County', 'Type of school']).sum()
kpri_cos.sum(1)

County            Type of school
Bomi              Community           113.0
                  Faith-based         955.0
                  Private            1039.0
                  Public             3590.0
Bong              Community          1235.0
                  Faith-based        3528.0
                  Private            4997.0
                  Public            18152.0
Gbarpolu          Community           115.0
                  Faith-based         198.0
                  Private             346.0
                  Public             7509.0
Grand Bassa       Community           286.0
                  Faith-based         789.0
                  Private            4227.0
                  Public             8613.0
Grand Cape Mount  Community           646.0
                  Faith-based        1586.0
                  Private            2334.0
                  Public             9886.0
Grand Gedeh       Community           874.0
                  Faith-based        2329.0
                  Private            4958.0
                  Public             9659.0
Grand Kru         Faith-based        1206.0
                  Private             445.0
                  Public             7993.0
Lofa              Community           328.0
                  Faith-based         711.0
                  Private            1238.0
                  Public            14561.0
Margibi           Community          2646.0
                  Faith-based        3556.0
                  Private            5953.0
                  Public             9137.0
Maryland          Private             406.0
                  Public             1783.0
Montserrado 1     Community          3953.0
                  Faith-based       25773.0
                  Private           49639.0
                  Public            10884.0
Montserrado 2     Community           879.0
                  Faith-based       18966.0
                  Private           38415.0
                  Public            15711.0
Nimba             Community          3453.0
                  Faith-based        7297.0
                  Private           10242.0
                  Public            39453.0
River Gee         Faith-based        2099.0
                  Private             246.0
                  Public             6129.0
Rivercess         Community             0.0
                  Faith-based         314.0
                  Private             251.0
                  Public             3438.0
Sinoe             Community             0.0
                  Faith-based        2433.0
                  Private            1708.0
                  Public             9979.0
dtype: float64

In [85]:
kpri_os =pd.concat([ kpri_o, kpri_s], axis = 1).groupby(['Type of school']).sum()
kpri_os
#kcensus.shape

,How many students below Age 6 in Grade 1 are MALES?,How many students below Age 6 in Grade 2 are MALES?,How many students below Age 6 in Grade 3 are MALES?,How many students below Age 6 in Grade 4 are MALES?,How many students below Age 6 in Grade 5 are MALES?,How many students below Age 6 in Grade 6 are MALES?,How many students below Age 6 in Grade 1 are FEMALES?,How many students below Age 6 in Grade 2 are FEMALES?,How many students below Age 6 in Grade 3 are FEMALES?,How many students below Age 6 in Grade 4 are FEMALES?,How many students below Age 6 in Grade 5 are FEMALES?,How many students below Age 6 in Grade 6 are FEMALES?,How many students Age 6 years old in Grade 1 are MALES?,How many students Age 6 years old in Grade 2 are MALES?,How many students Age 6 years old in Grade 3 are MALES?,How many students Age 6 years old in Grade 4 are MALES?,How many students Age 6 years old in Grade 5 are MALES?,How many students Age 6 years old in Grade 6 are MALES?,How many students Age 6 years old in Grade 1 are FEMALES?,How many students Age 6 years old in Grade 2 are FEMALES?,How many students Age 6 years old in Grade 3 are FEMALES?,How many students Age 6 years old in Grade 4 are FEMALES?,How many students Age 6 years old in Grade 5 are FEMALES?,How many students Age 6 years old in Grade 6 are FEMALES?,How many students Age 7 years old in Grade 1 are MALES?,How many students Age 7 years old in Grade 2 are MALES?,How many students Age 7 years old in Grade 3 are MALES?,How many students Age 7 years old in Grade 4 are MALES?,How many students Age 7 years old in Grade 5 are MALES?,How many students Age 7 years old in Grade 6 are MALES?,How many students Age 7 years old in Grade 1 are FEMALES?,How many students Age 7 years old in Grade 2 are FEMALES?,How many students Age 7 years old in Grade 3 are FEMALES?,How many students Age 7 years old in Grade 4 are FEMALES?,How many students Age 7 years old in Grade 5 are FEMALES?,How many students Age 7 years old in Grade 6 are FEMALES?,How many students Age 8 years old in Grade 1 are MALES?,How many students Age 8 years old in Grade 2 are MALES?,How many students Age 8 years old in Grade 3 are MALES?,How many students Age 8 years old in Grade 4 are MALES?,How many students Age 8 years old in Grade 5 are MALES?,How many students Age 8 years old in Grade 6 are MALES?,How many students Age 8 years old in Grade 1 are FEMALES?,How many students Age 8 years old in Grade 2 are FEMALES?,How many students Age 8 years old in Grade 3 are FEMALES?,How many students Age 8 years old in Grade 4 are FEMALES?,How many students Age 8 years old in Grade 5 are FEMALES?,How many students Age 8 years old in Grade 6 are FEMALES?,How many students Age 9 years old in Grade 1 are MALES?,How many students Age 9 years old in Grade 2 are MALES?,How many students Age 9 years old in Grade 3 are MALES?,How many students Age 9 years old in Grade 4 are MALES?,How many students Age 9 years old in Grade 5 are MALES?,How many students Age 9 years old in Grade 6 are MALES?,How many students Age 9 years old in Grade 1 are FEMALES?,How many students Age 9 years old in Grade 2 are FEMALES?,How many students Age 9 years old in Grade 3 are FEMALES?,How many students Age 9 years old in Grade 4 are FEMALES?,How many students Age 9 years old in Grade 5 are FEMALES?,How many students Age 9 years old in Grade 6 are FEMALES?,How many students Age 10 years old in Grade 1 are MALES?,How many students Age 10 years old in Grade 2 are MALES?,How many students Age 10 years old in Grade 3 are MALES?,How many students Age 10 years old in Grade 4 are MALES?,How many students Age 10 years old in Grade 5 are MALES?,How many students Age 10 years old in Grade 6 are MALES?,How many students Age 10 years old in Grade 1 are FEMALES?,How many students Age 10 years old in Grade 2 are FEMALES?,How many students Age 10 years old in Grade 3 are FEMALES?,How many students Age 10 years old in Grade 4 are FEMALES?,How many students Age 10 years old in Grade 5 are FEMALES?,How many students Age 10 years old in Grade 6 are FEMALES?,How many students Age 11 years old in Grade 1 are MALES?,How many students Age 11 years old in Grade 2 are MALES?,How many students Age 11 years old in Grade 3 are MALES?,How many students Age 11 years old in Grade 4 are MALES?,How many students Age 11 years old in Grade 5 are MALES?,How many students Age 11 years old in Grade 6 are MALES?,How many students Age 11 years old in Grade 1 are FEMALES?,How many students Age 11 years old in Grade 2 are FEMALES?,How many students Age 11 years old in Grade 3 are FEMALES?,How many students Age 11 years old in Grade 4 are FEMALES?,How many students Age 11 years old in Grade 5 are FEMALES?,How many students Age 11 years old in Grade 6 are FEMALES?,How many students Age 12 years old in Grade 1 are MALES?,How many students Age 12 years old in Grade 2 are MALES?,How many students Age 12 years old in Grade 3 are MALES?,How many students Age 12 years old in Grade 4 are MALES?,How many students Age 12 years old in Grade 5 are MALES?,How many students Age 12 years old in Grade 6 are MALES?,How many students Age 12 years old in Grade 1 are FEMALES?,How many students Age 12 years old in Grade 2 are FEMALES?,How many students Age 12 years old in Grade 3 are FEMALES?,How many students 12 years old in Grade 4 are FEMALES?,How many students Age 12 years old in Grade 5 are FEMALES?,How many students Age 12 years old in Grade 6 are FEMALES?,How many students Age 13 years old in Grade 1 are MALES?,How many students Age 13 years old in Grade 2 are MALES?,How many students Age 13 years old in Grade 3 are MALES?,How many students Age 13 years old in Grade 4 are MALES?,How many students Age 13 years old in Grade 5 are MALES?,How many students Age 13 years old in Grade 6 are MALES?,How many students Age 13 years old in Grade 1 are FEMALES?,How many students Age 13 years old in Grade 2 are FEMALES?,How many students Age 13 years old in Grade 3 are FEMALES?,How many students Age 13 years old in Grade 4 are FEMALES?,How many students Age 13 years old in Grade 5 are FEMALES?,How many students Age 13 years old in Grade 6 are FEMALES?,How many students Age 14 years old in Grade 1 are MALES?,How many students Age 14 years old in Grade 2 are MALES?,How many students Age 14 years old in Grade 3 are MALES?,How many students Age 14 years old in Grade 4 are MALES?,How many students Age 14 years old in Grade 5 are MALES?,How many students Age 14 years old in Grade 6 are MALES?,How many students Age 14 years old in Grade 1 are FEMALES?,How many students Age 14 years old in Grade 2 are FEMALES?,How many students Age 14 years old in Grade 3 are FEMALES?,How many students Age 14 years old in Grade 4 are FEMALES?,How many students Age 14 years old in Grade 5 are FEMALES?,How many students Age 14 years old in Grade 6 are FEMALES?,How many students Age 15 years old in Grade 1 are MALES?,How many students Age 15 years old in Grade 2 are MALES?,How many students Age 15 years old in Grade 3 are MALES?,How many students Age 15 years old in Grade 4 are MALES?,How many students Age 15 years old in Grade 5 are MALES?,How many students Age 15 years old in Grade 6 are MALES?,How many students Age 15 years old in Grade 1 are FEMALES?,How many students Age 15 years old in Grade 2 are FEMALES?,How many students Age 15 years old in Grade 3 are FEMALES?,How many students Age 15 years old in Grade 4 are FEMALES?,How many students age 15 Years old in Grade 5 are FEMALES?,How many students age 15 Years old in Grade 6 are FEMALES?,How many students above age 15 Years old in Grade 1 are MALES?,How many students above age 15 Years old in Grade 2 are MALES?,How many students above age 15 Years old in Grade 3 are MALES?,How many students above age 15 Years old in Grade 4 are MALES?,How many students above age 15 Years old in Grade 5 are MALES?,How many students above age 15 Years old in Grade 6 are MALES?,How many students above Age 15 in Grade 1 are FEMALES?,How many students above Age 15 in Grade 2 are FEMALES?,How many students above Age 15 in Grade 3 are FEMALES?,How many students above Age 15 in Grade 4 are FEMALES?,How many students above Age 15 in Grade 5 are FEMALES?,How many students above Age 15 in Grade 6 are FEMALES?
Type of school,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Community,84.0,31.0,84.0,18.0,11.0,6.0,72.0,29.0,20.0,25.0,15.0,6.0,180.0,75.0,72.0,30.0,30.0,5.0,138.0,69.0,62.0,30.0,32.0,2.0,269.0,196.0,133.0,57.0,50.0,14.0,291.0,179.0,120.0,59.0,35.0,24.0,253.0,223.0,206.0,86.0,46.0,42.0,236.0,220.0,167.0,76.0,39.0,23.0,221.0,217.0,181.0,170.0,78.0,53.0,159.0,201.0,198.0,122.0,88.0,58.0,151.0,136.0,218.0,169.0,113.0,99.0,168.0,168.0,202.0,165.0,141.0,105.0,122.0,94.0,140.0,162.0,91.0,102.0,120.0,95.0,131.0,143.0,102.0,66.0,106.0,98.0,114.0,131.0,165.0,115.0,95.0,121.0,138.0,133.0,147.0,135.0,102.0,75.0,112.0,127.0,176.0,109.0,73.0,84.0,104.0,132.0,150.0,130.0,32.0,52.0,63.0,105.0,143.0,132.0,11.0,55.0,70.0,106.0,120.0,154.0,29.0,42.0,46.0,73.0,92.0,113.0,34.0,27.0,52.0,71.0,127.0,112.0,23.0,21.0,19.0,53.0,102.0,131.0,19.0,17.0,32.0,41.0,87.0,131.0
Faith-based,279.0,113.0,76.0,36.0,34.0,44.0,346.0,155.0,69.0,49.0,289.0,44.0,1028.0,372.0,142.0,91.0,91.0,58.0,1041.0,463.0,177.0,76.0,76.0,71.0,1185.0,928.0,488.0,217.0,107.0,52.0,1253.0,1085.0,387.0,198.0,92.0,52.0,1113.0,948.0,860.0,397.0,228.0,105.0,1206.0,975.0,1029.0,515.0,213.0,118.0,884.0,933.0,827.0,667.0,311.0,198.0,846.0,851.0,933.0,846.0,378.0,212.0,709.0,801.0,842.0,744.0,693.0,303.0,754.0,862.0,934.0,837.0,708.0,303.0,465.0,624.0,690.0,699.0,700.0,511.0,438.0,672.0,862.0,943.0,833.0,642.0,474.0,604.0,657.0,821.0,785.0,719.0,378.0,563.0,788.0,928.0,867.0,858.0,234.0,315.0,464.0,675.0,785.0,778.0,257.0,311.0,604.0,789.0,828.0,846.0,113.0,183.0,333.0,556.0,671.0,796.0,21.0,165.0,351.0,529.0,747.0,925.0,111.0,115.0,165.0,306.0,481.0,706.0,102.0,114.0,216.0,290.0,582.0,753.0,106.0,116.0,137.0,247.0,402.0,980.0,87.0,102.0,153.0,225.0,370.0,730.0
Private,720.0,447.0,240.0,189.0,122.0,151.0,901.0,455.0,247.0,182.0,167.0,135.0,2293.0,862.0,381.0,192.0,185.0,179.0,2430.0,926.0,501.0,295.0,180.0,167.0,2276.0,2127.0,857.0,486.0,298.0,190.0,2370.0,2153.0,925.0,505.0,299.0,251.0,1870.0,1904.0,1775.0,843.0,483.0,269.0,1916.0,2040.0,1873.0,927.0,575.0,293.0,1508.0,1739.0,1774.0,1496.0,847.0,499.0,1507.0,1756.0,1826.0,1553.0,770.0,404.0,1133.0,1434.0,1561.0,1572.0,1375.0,695.0,1184.0,1377.0,1682.0,1542.0,1466.0,667.0,734.0,915.0,1336.0,1415.0,1294.0,1297.0,727.0,1014.0,1371.0,1545.0,1514.0,1319.0,488.0,668.0,1019.0,1263.0,1529.0,1285.0,475.0,767.0,1079.0,1504.0,1638.0,1350.0,246.0,429.0,714.0,993.0,1334.0,1269.0,275.0,446.0,745.0,1102.0,1389.0,1347.0,170.0,278.0,447.0,620.0,960.0,1308.0,63.0,259.0,492.0,733.0,1110.0,1394.0,124.0,110.0,232.0,398.0,673.0,951.0,133.0,136.0,254.0,451.0,652.0,1018.0,98.0,114.0,179.0,312.0,509.0,923.0,101.0,126.0,175.0,271.0,529.0,887.0
Public,431.0,203.0,193.0,105.0,99.0,152.0,328.0,169.0,71.0,101.0,42.0,42.0,2405.0,493.0,227.0,104.0,60.0,33.0,1185.0,466.0,160.0,49.0,59.0,50.0,2195.0,1327.0,730.0,212.0,164.0,94.0,1893.0,1164.0,529.0,201.0,86.0,94.0,2846.0,1897.0,1221.0,538.0,235.0,133.0,2415.0,1575.0,1106.0,527.0,178.0,94.0,2827.0,2192.0,1429.0,986.0,667.0,245.0,2389.0,1877.0,1301.0,823.0,362.0,157.0,3158.0,2456.0,1949.0,1379.0,820.0,354.0,2658.0,2166.0,1667.0,1075.0,663.0,311.0,2331.0,2340.0,1938.0,1528.0,1018.0,601.0,2082.0,1949.0,1784.0,1253.0,779.0,412.0,2095.0,2452.0,2286.0,2113.0,1268.0,894.0,1852.0,2186.0,2165.0,1733.0,1142.0,716.0,1428.0,1817.0,2380.0,2197.0,1733.0,1201.0,1163.0,1707.0,2029.0,1940.0,1548.0,1040.0,983.0,1255.0,1879.0,2340.0,2204.0,1794.0,58.0,1150.0,1538.0,2081.0,1973.0,1702.0,625.0,876.0,1368.0,1977.0,2233.0,2225.0,487.0,689.0,1143.0,1544.0,1933.0,1991.0,566.0,746.0,1161.0,1886.0,2565.0,3378.0,468.0,531.0,902.0,1541.0,2030.0,2963.0

In [86]:
kpri_osm = kpri_os.iloc[:,:6].append([
kpri_os.iloc[:,12:18],
kpri_os.iloc[:,24:30],
kpri_os.iloc[:,36:42],
kpri_os.iloc[:,48:54],
kpri_os.iloc[:,60:66],
kpri_os.iloc[:,72:78],
kpri_os.iloc[:,84:90],
kpri_os.iloc[:,96:102],
kpri_os.iloc[:,108:114],
kpri_os.iloc[:,120:126],
kpri_os.iloc[:,132:138]]).groupby('Type of school').sum()
kpri_osm

,How many students below Age 6 in Grade 1 are MALES?,How many students below Age 6 in Grade 2 are MALES?,How many students below Age 6 in Grade 3 are MALES?,How many students below Age 6 in Grade 4 are MALES?,How many students below Age 6 in Grade 5 are MALES?,How many students below Age 6 in Grade 6 are MALES?,How many students Age 6 years old in Grade 1 are MALES?,How many students Age 6 years old in Grade 2 are MALES?,How many students Age 6 years old in Grade 3 are MALES?,How many students Age 6 years old in Grade 4 are MALES?,How many students Age 6 years old in Grade 5 are MALES?,How many students Age 6 years old in Grade 6 are MALES?,How many students Age 7 years old in Grade 1 are MALES?,How many students Age 7 years old in Grade 2 are MALES?,How many students Age 7 years old in Grade 3 are MALES?,How many students Age 7 years old in Grade 4 are MALES?,How many students Age 7 years old in Grade 5 are MALES?,How many students Age 7 years old in Grade 6 are MALES?,How many students Age 8 years old in Grade 1 are MALES?,How many students Age 8 years old in Grade 2 are MALES?,How many students Age 8 years old in Grade 3 are MALES?,How many students Age 8 years old in Grade 4 are MALES?,How many students Age 8 years old in Grade 5 are MALES?,How many students Age 8 years old in Grade 6 are MALES?,How many students Age 9 years old in Grade 1 are MALES?,How many students Age 9 years old in Grade 2 are MALES?,How many students Age 9 years old in Grade 3 are MALES?,How many students Age 9 years old in Grade 4 are MALES?,How many students Age 9 years old in Grade 5 are MALES?,How many students Age 9 years old in Grade 6 are MALES?,How many students Age 10 years old in Grade 1 are MALES?,How many students Age 10 years old in Grade 2 are MALES?,How many students Age 10 years old in Grade 3 are MALES?,How many students Age 10 years old in Grade 4 are MALES?,How many students Age 10 years old in Grade 5 are MALES?,How many students Age 10 years old in Grade 6 are MALES?,How many students Age 11 years old in Grade 1 are MALES?,How many students Age 11 years old in Grade 2 are MALES?,How many students Age 11 years old in Grade 3 are MALES?,How many students Age 11 years old in Grade 4 are MALES?,How many students Age 11 years old in Grade 5 are MALES?,How many students Age 11 years old in Grade 6 are MALES?,How many students Age 12 years old in Grade 1 are MALES?,How many students Age 12 years old in Grade 2 are MALES?,How many students Age 12 years old in Grade 3 are MALES?,How many students Age 12 years old in Grade 4 are MALES?,How many students Age 12 years old in Grade 5 are MALES?,How many students Age 12 years old in Grade 6 are MALES?,How many students Age 13 years old in Grade 1 are MALES?,How many students Age 13 years old in Grade 2 are MALES?,How many students Age 13 years old in Grade 3 are MALES?,How many students Age 13 years old in Grade 4 are MALES?,How many students Age 13 years old in Grade 5 are MALES?,How many students Age 13 years old in Grade 6 are MALES?,How many students Age 14 years old in Grade 1 are MALES?,How many students Age 14 years old in Grade 2 are MALES?,How many students Age 14 years old in Grade 3 are MALES?,How many students Age 14 years old in Grade 4 are MALES?,How many students Age 14 years old in Grade 5 are MALES?,How many students Age 14 years old in Grade 6 are MALES?,How many students Age 15 years old in Grade 1 are MALES?,How many students Age 15 years old in Grade 2 are MALES?,How many students Age 15 years old in Grade 3 are MALES?,How many students Age 15 years old in Grade 4 are MALES?,How many students Age 15 years old in Grade 5 are MALES?,How many students Age 15 years old in Grade 6 are MALES?,How many students above age 15 Years old in Grade 1 are MALES?,How many students above age 15 Years old in Grade 2 are MALES?,How many students above age 15 Years old in Grade 3 are MALES?,How many students above age 15 Years old in Grade 4 are MALES?,How many students above age 15 Years old in Grade 5 are MALES?,How many students above age 15 Years old in Grade 6 are MALES?
Type of school,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Community,84.0,31.0,84.0,18.0,11.0,6.0,180.0,75.0,72.0,30.0,30.0,5.0,269.0,196.0,133.0,57.0,50.0,14.0,253.0,223.0,206.0,86.0,46.0,42.0,221.0,217.0,181.0,170.0,78.0,53.0,151.0,136.0,218.0,169.0,113.0,99.0,122.0,94.0,140.0,162.0,91.0,102.0,106.0,98.0,114.0,131.0,165.0,115.0,102.0,75.0,112.0,127.0,176.0,109.0,32.0,52.0,63.0,105.0,143.0,132.0,29.0,42.0,46.0,73.0,92.0,113.0,23.0,21.0,19.0,53.0,102.0,131.0
Faith-based,279.0,113.0,76.0,36.0,34.0,44.0,1028.0,372.0,142.0,91.0,91.0,58.0,1185.0,928.0,488.0,217.0,107.0,52.0,1113.0,948.0,860.0,397.0,228.0,105.0,884.0,933.0,827.0,667.0,311.0,198.0,709.0,801.0,842.0,744.0,693.0,303.0,465.0,624.0,690.0,699.0,700.0,511.0,474.0,604.0,657.0,821.0,785.0,719.0,234.0,315.0,464.0,675.0,785.0,778.0,113.0,183.0,333.0,556.0,671.0,796.0,111.0,115.0,165.0,306.0,481.0,706.0,106.0,116.0,137.0,247.0,402.0,980.0
Private,720.0,447.0,240.0,189.0,122.0,151.0,2293.0,862.0,381.0,192.0,185.0,179.0,2276.0,2127.0,857.0,486.0,298.0,190.0,1870.0,1904.0,1775.0,843.0,483.0,269.0,1508.0,1739.0,1774.0,1496.0,847.0,499.0,1133.0,1434.0,1561.0,1572.0,1375.0,695.0,734.0,915.0,1336.0,1415.0,1294.0,1297.0,488.0,668.0,1019.0,1263.0,1529.0,1285.0,246.0,429.0,714.0,993.0,1334.0,1269.0,170.0,278.0,447.0,620.0,960.0,1308.0,124.0,110.0,232.0,398.0,673.0,951.0,98.0,114.0,179.0,312.0,509.0,923.0
Public,431.0,203.0,193.0,105.0,99.0,152.0,2405.0,493.0,227.0,104.0,60.0,33.0,2195.0,1327.0,730.0,212.0,164.0,94.0,2846.0,1897.0,1221.0,538.0,235.0,133.0,2827.0,2192.0,1429.0,986.0,667.0,245.0,3158.0,2456.0,1949.0,1379.0,820.0,354.0,2331.0,2340.0,1938.0,1528.0,1018.0,601.0,2095.0,2452.0,2286.0,2113.0,1268.0,894.0,1428.0,1817.0,2380.0,2197.0,1733.0,1201.0,983.0,1255.0,1879.0,2340.0,2204.0,1794.0,625.0,876.0,1368.0,1977.0,2233.0,2225.0,566.0,746.0,1161.0,1886.0,2565.0,3378.0

In [87]:
kpri_os.sum(1)

Type of school
Community       14528.0
Faith-based     71740.0
Private        126444.0
Public         176477.0
dtype: float64

In [88]:
kpri_osm.sum(1)

Type of school
Community       7419.0
Faith-based    34428.0
Private        61606.0
Public         96240.0
dtype: float64

# Primary Enrollment by District and Gender

In [89]:
kpri_c = kcensus.iloc[:,[2]]
kpri_d = kcensus.iloc[:,3:19]
kpri_s = kpri_student.iloc[:,102:246]

In [90]:
kpri_cds = pd.concat([kpri_c, kpri_d, kpri_s], axis = 1)
kpri_cds.columns.tolist()

['County',
 'District in Bong County',
 'District in Gbarpolu',
 'District in River Gee',
 'District in Sinoe',
 'District in Lofa',
 'District in Nimba',
 'District in Grand Cape Mount',
 'District in Maryland',
 'District in Margibi',
 'District in Bomi',
 'District in Grand Bassa',
 'District in Montserrado 2',
 'District in Montserrado 1',
 'Districts in Grand Kru',
 'Districts in Grand Gedeh',
 'Districts in River Cess',
 'How many students  below Age 6 in Grade 1 are MALES?',
 'How many students  below Age 6 in Grade 2 are MALES?',
 'How many students  below Age 6 in Grade 3 are MALES?',
 'How many students  below Age 6 in Grade 4 are MALES?',
 'How many students  below Age 6 in Grade 5 are MALES?',
 'How many students  below Age 6 in Grade 6 are MALES?',
 'How many students  below Age 6 in Grade 1 are FEMALES?',
 'How many students  below Age 6 in Grade 2 are FEMALES?',
 'How many students  below Age 6 in Grade 3 are FEMALES?',
 'How many students  below Age 6 in Grade 4 are FEMALES?',
 'How many students  below Age 6 in Grade 5 are FEMALES?',
 'How many students  below Age 6 in Grade 6 are FEMALES?',
 'How many students  Age 6 years old in Grade 1 are MALES?',
 'How many students  Age 6 years old in Grade 2 are MALES?',
 'How many students  Age 6 years old in Grade 3 are MALES?',
 'How many students  Age 6 years old in Grade 4 are MALES?',
 'How many students  Age 6 years old in Grade 5 are MALES?',
 'How many students  Age 6 years old in Grade 6 are MALES?',
 'How many students  Age 6 years old in Grade 1 are FEMALES?',
 'How many students  Age 6 years old in Grade 2 are FEMALES?',
 'How many students  Age 6 years old in Grade 3 are FEMALES?',
 'How many students  Age 6 years old in Grade 4 are FEMALES?',
 'How many students  Age 6 years old in Grade 5 are FEMALES?',
 'How many students  Age 6 years old in Grade 6 are FEMALES?',
 'How many students  Age 7 years old in Grade 1 are MALES?',
 'How many students  Age 7 years old in Grade 2 are MALES?',
 'How many students  Age 7 years old in Grade 3 are MALES?',
 'How many students  Age 7 years old in Grade 4 are MALES?',
 'How many students  Age 7 years old in Grade 5 are MALES?',
 'How many students  Age 7 years old in Grade 6 are MALES?',
 'How many students  Age 7 years old in Grade 1 are FEMALES?',
 'How many students  Age 7 years old in Grade 2 are FEMALES?',
 'How many students  Age 7 years old in Grade 3 are FEMALES?',
 'How many students  Age 7 years old in Grade 4 are FEMALES?',
 'How many students  Age 7 years old in Grade 5 are FEMALES?',
 'How many students  Age 7 years old in Grade 6 are FEMALES?',
 'How many students  Age 8 years old  in Grade 1 are MALES?',
 'How many students  Age 8 years old  in Grade 2 are MALES?',
 'How many students  Age 8 years old  in Grade 3 are MALES?',
 'How many students  Age 8 years old  in Grade 4 are MALES?',
 'How many students  Age 8 years old  in Grade 5 are MALES?',
 'How many students  Age 8 years old  in Grade 6 are MALES?',
 'How many students  Age 8 years old  in Grade 1 are FEMALES?',
 'How many students  Age 8 years old  in Grade 2 are FEMALES?',
 'How many students  Age 8 years old  in Grade 3 are FEMALES?',
 'How many students  Age 8 years old  in Grade 4 are FEMALES?',
 'How many students  Age 8 years old  in Grade 5 are FEMALES?',
 'How many students  Age 8 years old  in Grade 6 are FEMALES?',
 'How many students   Age 9 years old in Grade 1 are MALES?',
 'How many students   Age 9 years old in Grade 2 are MALES?',
 'How many students   Age 9 years old in Grade 3 are MALES?',
 'How many students   Age 9 years old in Grade 4 are MALES?',
 'How many students   Age 9 years old in Grade 5 are MALES?',
 'How many students   Age 9 years old in Grade 6 are MALES?',
 'How many students  Age 9 years old in Grade 1 are FEMALES?',
 'How many students  Age 9 years old in Grade 2 are FEMALES?',
 'How many students  Age 9 years old in Grade 3 are FEMALES?',
 'How many students  Age 9 years old in Grade 4 are FEMALES?',
 'How many students  Age 9 years old in Grade 5 are FEMALES?',
 'How many students  Age 9 years old in Grade 6 are FEMALES?',
 'How many students  Age 10 years old in Grade 1 are MALES?',
 'How many students  Age 10 years old in Grade 2 are MALES?',
 'How many students  Age 10 years old in Grade 3 are MALES?',
 'How many students  Age 10 years old in Grade 4 are MALES?',
 'How many students  Age 10 years old in Grade 5 are MALES?',
 'How many students  Age 10 years old in Grade 6 are MALES?',
 'How many students  Age 10 years old in Grade 1 are FEMALES?',
 'How many students  Age 10 years old in Grade 2 are FEMALES?',
 'How many students   Age 10 years old in Grade 3 are FEMALES?',
 'How many students   Age 10 years old in Grade 4 are FEMALES?',
 'How many students   Age 10 years old in Grade 5 are FEMALES?',
 'How many students   Age 10 years old in Grade 6 are FEMALES?',
 'How many students   Age 11 years old in Grade 1 are MALES?',
 'How many students   Age 11 years old in Grade 2 are MALES?',
 'How many students   Age 11 years old in Grade 3 are MALES?',
 'How many students   Age 11 years old in Grade 4 are MALES?',
 'How many students   Age 11 years old in Grade 5 are MALES?',
 'How many students   Age 11 years old in Grade 6 are MALES?',
 'How many students   Age 11 years old in Grade 1 are FEMALES?',
 'How many students   Age 11 years old in Grade 2 are FEMALES?',
 'How many students   Age 11 years old in Grade 3 are FEMALES?',
 'How many students   Age 11 years old in Grade 4 are FEMALES?',
 'How many students   Age 11 years old in Grade 5 are FEMALES?',
 'How many students   Age 11 years old in Grade 6 are FEMALES?',
 'How many students  Age 12 years old in Grade 1 are MALES?',
 'How many students  Age 12 years old in Grade 2 are MALES?',
 'How many students  Age 12 years old in Grade 3 are MALES?',
 'How many students  Age 12 years old in Grade 4 are MALES?',
 'How many students  Age 12 years old in Grade 5 are MALES?',
 'How many students  Age 12 years old in Grade 6 are MALES?',
 'How many students  Age 12 years old in Grade 1 are FEMALES?',
 'How many students  Age 12 years old in Grade 2 are FEMALES?',
 'How many students  Age 12 years old in Grade 3 are FEMALES?',
 'How many students   12 years old in Grade 4 are FEMALES?',
 'How many students  Age 12 years old in Grade 5 are FEMALES?',
 'How many students  Age 12 years old in Grade 6 are FEMALES?',
 'How many students  Age 13 years old in Grade 1 are MALES?',
 'How many students  Age 13 years old in Grade 2 are MALES?',
 'How many students  Age 13 years old in Grade 3 are MALES?',
 'How many students  Age 13 years old in Grade 4 are MALES?',
 'How many students  Age 13 years old in Grade 5 are MALES?',
 'How many students  Age 13 years old in Grade 6 are MALES?',
 'How many students  Age 13 years old in Grade 1 are FEMALES?',
 'How many students  Age 13 years old in Grade 2 are FEMALES?',
 'How many students  Age 13 years old in Grade 3 are FEMALES?',
 'How many students  Age 13 years old in Grade 4 are FEMALES?',
 'How many students  Age 13 years old in Grade 5 are FEMALES?',
 'How many students  Age 13 years old in Grade 6 are FEMALES?',
 'How many students Age 14 years old in Grade 1 are MALES?',
 'How many students Age 14 years old in Grade 2 are MALES?',
 'How many students Age 14 years old in Grade 3 are MALES?',
 'How many students Age 14 years old in Grade 4 are MALES?',
 'How many students Age 14 years old in Grade 5 are MALES?',
 'How many students Age 14 years old in Grade 6 are MALES?',
 'How many students  Age 14 years old in Grade 1 are FEMALES?',
 'How many students  Age 14 years old in Grade 2 are FEMALES?',
 'How many students  Age 14 years old in Grade 3 are FEMALES?',
 'How many students  Age 14 years old in Grade 4 are FEMALES?',
 'How many students  Age 14 years old in Grade 5 are FEMALES?',
 'How many students  Age 14 years old in Grade 6 are FEMALES?',
 'How many students  Age 15 years old in Grade 1 are MALES?',
 'How many students  Age 15 years old in Grade 2 are MALES?',
 'How many students  Age 15 years old in Grade 3 are MALES?',
 'How many students  Age 15 years old in Grade 4 are MALES?',
 'How many students  Age 15 years old in Grade 5 are MALES?',
 'How many students  Age 15 years old in Grade 6 are MALES?',
 'How many students  Age 15 years old in Grade 1 are FEMALES?',
 'How many students  Age 15 years old in Grade 2 are FEMALES?',
 'How many students  Age 15 years old in Grade 3 are FEMALES?',
 'How many students  Age 15 years old in Grade 4 are FEMALES?',
 'How many students  age 15 Years old  in Grade 5 are FEMALES?',
 'How many students  age 15 Years old  in Grade 6 are FEMALES?',
 'How many students above age 15 Years old  in Grade 1 are MALES?',
 'How many students above age 15 Years old  in Grade 2 are MALES?',
 'How many students above age 15 Years old  in Grade 3 are MALES?',
 'How many students above age 15 Years old  in Grade 4 are MALES?',
 'How many students above age 15 Years old  in Grade 5 are MALES?',
 'How many students above age 15 Years old  in Grade 6 are MALES?',
 'How many students  above Age 15 in Grade 1 are FEMALES?',
 'How many students  above Age 15 in Grade 2 are FEMALES?',
 'How many students  above Age 15 in Grade 3 are FEMALES?',
 'How many students  above Age 15 in Grade 4 are FEMALES?',
 'How many students  above Age 15 in Grade 5 are FEMALES?',
 'How many students  above Age 15 in Grade 6 are FEMALES?']

In [91]:
kpri_melt =kpri_cds.melt(id_vars=['County','How many students  below Age 6 in Grade 1 are MALES?',
 'How many students  below Age 6 in Grade 2 are MALES?',
 'How many students  below Age 6 in Grade 3 are MALES?',
 'How many students  below Age 6 in Grade 4 are MALES?',
 'How many students  below Age 6 in Grade 5 are MALES?',
 'How many students  below Age 6 in Grade 6 are MALES?',
 'How many students  below Age 6 in Grade 1 are FEMALES?',
 'How many students  below Age 6 in Grade 2 are FEMALES?',
 'How many students  below Age 6 in Grade 3 are FEMALES?',
 'How many students  below Age 6 in Grade 4 are FEMALES?',
 'How many students  below Age 6 in Grade 5 are FEMALES?',
 'How many students  below Age 6 in Grade 6 are FEMALES?',
 'How many students  Age 6 years old in Grade 1 are MALES?',
 'How many students  Age 6 years old in Grade 2 are MALES?',
 'How many students  Age 6 years old in Grade 3 are MALES?',
 'How many students  Age 6 years old in Grade 4 are MALES?',
 'How many students  Age 6 years old in Grade 5 are MALES?',
 'How many students  Age 6 years old in Grade 6 are MALES?',
 'How many students  Age 6 years old in Grade 1 are FEMALES?',
 'How many students  Age 6 years old in Grade 2 are FEMALES?',
 'How many students  Age 6 years old in Grade 3 are FEMALES?',
 'How many students  Age 6 years old in Grade 4 are FEMALES?',
 'How many students  Age 6 years old in Grade 5 are FEMALES?',
 'How many students  Age 6 years old in Grade 6 are FEMALES?',
 'How many students  Age 7 years old in Grade 1 are MALES?',
 'How many students  Age 7 years old in Grade 2 are MALES?',
 'How many students  Age 7 years old in Grade 3 are MALES?',
 'How many students  Age 7 years old in Grade 4 are MALES?',
 'How many students  Age 7 years old in Grade 5 are MALES?',
 'How many students  Age 7 years old in Grade 6 are MALES?',
 'How many students  Age 7 years old in Grade 1 are FEMALES?',
 'How many students  Age 7 years old in Grade 2 are FEMALES?',
 'How many students  Age 7 years old in Grade 3 are FEMALES?',
 'How many students  Age 7 years old in Grade 4 are FEMALES?',
 'How many students  Age 7 years old in Grade 5 are FEMALES?',
 'How many students  Age 7 years old in Grade 6 are FEMALES?',
 'How many students  Age 8 years old  in Grade 1 are MALES?',
 'How many students  Age 8 years old  in Grade 2 are MALES?',
 'How many students  Age 8 years old  in Grade 3 are MALES?',
 'How many students  Age 8 years old  in Grade 4 are MALES?',
 'How many students  Age 8 years old  in Grade 5 are MALES?',
 'How many students  Age 8 years old  in Grade 6 are MALES?',
 'How many students  Age 8 years old  in Grade 1 are FEMALES?',
 'How many students  Age 8 years old  in Grade 2 are FEMALES?',
 'How many students  Age 8 years old  in Grade 3 are FEMALES?',
 'How many students  Age 8 years old  in Grade 4 are FEMALES?',
 'How many students  Age 8 years old  in Grade 5 are FEMALES?',
 'How many students  Age 8 years old  in Grade 6 are FEMALES?',
 'How many students   Age 9 years old in Grade 1 are MALES?',
 'How many students   Age 9 years old in Grade 2 are MALES?',
 'How many students   Age 9 years old in Grade 3 are MALES?',
 'How many students   Age 9 years old in Grade 4 are MALES?',
 'How many students   Age 9 years old in Grade 5 are MALES?',
 'How many students   Age 9 years old in Grade 6 are MALES?',
 'How many students  Age 9 years old in Grade 1 are FEMALES?',
 'How many students  Age 9 years old in Grade 2 are FEMALES?',
 'How many students  Age 9 years old in Grade 3 are FEMALES?',
 'How many students  Age 9 years old in Grade 4 are FEMALES?',
 'How many students  Age 9 years old in Grade 5 are FEMALES?',
 'How many students  Age 9 years old in Grade 6 are FEMALES?',
 'How many students  Age 10 years old in Grade 1 are MALES?',
 'How many students  Age 10 years old in Grade 2 are MALES?',
 'How many students  Age 10 years old in Grade 3 are MALES?',
 'How many students  Age 10 years old in Grade 4 are MALES?',
 'How many students  Age 10 years old in Grade 5 are MALES?',
 'How many students  Age 10 years old in Grade 6 are MALES?',
 'How many students  Age 10 years old in Grade 1 are FEMALES?',
 'How many students  Age 10 years old in Grade 2 are FEMALES?',
 'How many students   Age 10 years old in Grade 3 are FEMALES?',
 'How many students   Age 10 years old in Grade 4 are FEMALES?',
 'How many students   Age 10 years old in Grade 5 are FEMALES?',
 'How many students   Age 10 years old in Grade 6 are FEMALES?',
 'How many students   Age 11 years old in Grade 1 are MALES?',
 'How many students   Age 11 years old in Grade 2 are MALES?',
 'How many students   Age 11 years old in Grade 3 are MALES?',
 'How many students   Age 11 years old in Grade 4 are MALES?',
 'How many students   Age 11 years old in Grade 5 are MALES?',
 'How many students   Age 11 years old in Grade 6 are MALES?',
 'How many students   Age 11 years old in Grade 1 are FEMALES?',
 'How many students   Age 11 years old in Grade 2 are FEMALES?',
 'How many students   Age 11 years old in Grade 3 are FEMALES?',
 'How many students   Age 11 years old in Grade 4 are FEMALES?',
 'How many students   Age 11 years old in Grade 5 are FEMALES?',
 'How many students   Age 11 years old in Grade 6 are FEMALES?',
 'How many students  Age 12 years old in Grade 1 are MALES?',
 'How many students  Age 12 years old in Grade 2 are MALES?',
 'How many students  Age 12 years old in Grade 3 are MALES?',
 'How many students  Age 12 years old in Grade 4 are MALES?',
 'How many students  Age 12 years old in Grade 5 are MALES?',
 'How many students  Age 12 years old in Grade 6 are MALES?',
 'How many students  Age 12 years old in Grade 1 are FEMALES?',
 'How many students  Age 12 years old in Grade 2 are FEMALES?',
 'How many students  Age 12 years old in Grade 3 are FEMALES?',
 'How many students   12 years old in Grade 4 are FEMALES?',
 'How many students  Age 12 years old in Grade 5 are FEMALES?',
 'How many students  Age 12 years old in Grade 6 are FEMALES?',
 'How many students  Age 13 years old in Grade 1 are MALES?',
 'How many students  Age 13 years old in Grade 2 are MALES?',
 'How many students  Age 13 years old in Grade 3 are MALES?',
 'How many students  Age 13 years old in Grade 4 are MALES?',
 'How many students  Age 13 years old in Grade 5 are MALES?',
 'How many students  Age 13 years old in Grade 6 are MALES?',
 'How many students  Age 13 years old in Grade 1 are FEMALES?',
 'How many students  Age 13 years old in Grade 2 are FEMALES?',
 'How many students  Age 13 years old in Grade 3 are FEMALES?',
 'How many students  Age 13 years old in Grade 4 are FEMALES?',
 'How many students  Age 13 years old in Grade 5 are FEMALES?',
 'How many students  Age 13 years old in Grade 6 are FEMALES?',
 'How many students Age 14 years old in Grade 1 are MALES?',
 'How many students Age 14 years old in Grade 2 are MALES?',
 'How many students Age 14 years old in Grade 3 are MALES?',
 'How many students Age 14 years old in Grade 4 are MALES?',
 'How many students Age 14 years old in Grade 5 are MALES?',
 'How many students Age 14 years old in Grade 6 are MALES?',
 'How many students  Age 14 years old in Grade 1 are FEMALES?',
 'How many students  Age 14 years old in Grade 2 are FEMALES?',
 'How many students  Age 14 years old in Grade 3 are FEMALES?',
 'How many students  Age 14 years old in Grade 4 are FEMALES?',
 'How many students  Age 14 years old in Grade 5 are FEMALES?',
 'How many students  Age 14 years old in Grade 6 are FEMALES?',
 'How many students  Age 15 years old in Grade 1 are MALES?',
 'How many students  Age 15 years old in Grade 2 are MALES?',
 'How many students  Age 15 years old in Grade 3 are MALES?',
 'How many students  Age 15 years old in Grade 4 are MALES?',
 'How many students  Age 15 years old in Grade 5 are MALES?',
 'How many students  Age 15 years old in Grade 6 are MALES?',
 'How many students  Age 15 years old in Grade 1 are FEMALES?',
 'How many students  Age 15 years old in Grade 2 are FEMALES?',
 'How many students  Age 15 years old in Grade 3 are FEMALES?',
 'How many students  Age 15 years old in Grade 4 are FEMALES?',
 'How many students  age 15 Years old  in Grade 5 are FEMALES?',
 'How many students  age 15 Years old  in Grade 6 are FEMALES?',
 'How many students above age 15 Years old  in Grade 1 are MALES?',
 'How many students above age 15 Years old  in Grade 2 are MALES?',
 'How many students above age 15 Years old  in Grade 3 are MALES?',
 'How many students above age 15 Years old  in Grade 4 are MALES?',
 'How many students above age 15 Years old  in Grade 5 are MALES?',
 'How many students above age 15 Years old  in Grade 6 are MALES?',
 'How many students  above Age 15 in Grade 1 are FEMALES?',
 'How many students  above Age 15 in Grade 2 are FEMALES?',
 'How many students  above Age 15 in Grade 3 are FEMALES?',
 'How many students  above Age 15 in Grade 4 are FEMALES?',
 'How many students  above Age 15 in Grade 5 are FEMALES?',
 'How many students  above Age 15 in Grade 6 are FEMALES?'],var_name = 'district',value_name='count')
kpri_melt.shape#head()

(66656, 147)

In [92]:
k_s = kpri_melt[(kpri_melt['district']== 'District in Nimba') & (kpri_melt['count']== 'Saclepea 1')].sum()
#k_s

In [93]:
k_a = k_s[1:-2]
#k_a

In [94]:
k_a.sum()

9813.0

In [95]:
k_am = k_a[0:6].append([k_a[12:18],k_a[24:30],k_a[36:42],k_a[48:54],k_a[60:66],k_a[72:78],k_a[84:90],k_a[96:102],k_a[108:114],k_a[120:126],k_a[132:138]] )

In [96]:
k_am.sum()

5269.0

In [97]:
kpri_melt.head()

,County,How many students below Age 6 in Grade 1 are MALES?,How many students below Age 6 in Grade 2 are MALES?,How many students below Age 6 in Grade 3 are MALES?,How many students below Age 6 in Grade 4 are MALES?,How many students below Age 6 in Grade 5 are MALES?,How many students below Age 6 in Grade 6 are MALES?,How many students below Age 6 in Grade 1 are FEMALES?,How many students below Age 6 in Grade 2 are FEMALES?,How many students below Age 6 in Grade 3 are FEMALES?,How many students below Age 6 in Grade 4 are FEMALES?,How many students below Age 6 in Grade 5 are FEMALES?,How many students below Age 6 in Grade 6 are FEMALES?,How many students Age 6 years old in Grade 1 are MALES?,How many students Age 6 years old in Grade 2 are MALES?,How many students Age 6 years old in Grade 3 are MALES?,How many students Age 6 years old in Grade 4 are MALES?,How many students Age 6 years old in Grade 5 are MALES?,How many students Age 6 years old in Grade 6 are MALES?,How many students Age 6 years old in Grade 1 are FEMALES?,How many students Age 6 years old in Grade 2 are FEMALES?,How many students Age 6 years old in Grade 3 are FEMALES?,How many students Age 6 years old in Grade 4 are FEMALES?,How many students Age 6 years old in Grade 5 are FEMALES?,How many students Age 6 years old in Grade 6 are FEMALES?,How many students Age 7 years old in Grade 1 are MALES?,How many students Age 7 years old in Grade 2 are MALES?,How many students Age 7 years old in Grade 3 are MALES?,How many students Age 7 years old in Grade 4 are MALES?,How many students Age 7 years old in Grade 5 are MALES?,How many students Age 7 years old in Grade 6 are MALES?,How many students Age 7 years old in Grade 1 are FEMALES?,How many students Age 7 years old in Grade 2 are FEMALES?,How many students Age 7 years old in Grade 3 are FEMALES?,How many students Age 7 years old in Grade 4 are FEMALES?,How many students Age 7 years old in Grade 5 are FEMALES?,How many students Age 7 years old in Grade 6 are FEMALES?,How many students Age 8 years old in Grade 1 are MALES?,How many students Age 8 years old in Grade 2 are MALES?,How many students Age 8 years old in Grade 3 are MALES?,How many students Age 8 years old in Grade 4 are MALES?,How many students Age 8 years old in Grade 5 are MALES?,How many students Age 8 years old in Grade 6 are MALES?,How many students Age 8 years old in Grade 1 are FEMALES?,How many students Age 8 years old in Grade 2 are FEMALES?,How many students Age 8 years old in Grade 3 are FEMALES?,How many students Age 8 years old in Grade 4 are FEMALES?,How many students Age 8 years old in Grade 5 are FEMALES?,How many students Age 8 years old in Grade 6 are FEMALES?,How many students Age 9 years old in Grade 1 are MALES?,How many students Age 9 years old in Grade 2 are MALES?,How many students Age 9 years old in Grade 3 are MALES?,How many students Age 9 years old in Grade 4 are MALES?,How many students Age 9 years old in Grade 5 are MALES?,How many students Age 9 years old in Grade 6 are MALES?,How many students Age 9 years old in Grade 1 are FEMALES?,How many students Age 9 years old in Grade 2 are FEMALES?,How many students Age 9 years old in Grade 3 are FEMALES?,How many students Age 9 years old in Grade 4 are FEMALES?,How many students Age 9 years old in Grade 5 are FEMALES?,How many students Age 9 years old in Grade 6 are FEMALES?,How many students Age 10 years old in Grade 1 are MALES?,How many students Age 10 years old in Grade 2 are MALES?,How many students Age 10 years old in Grade 3 are MALES?,How many students Age 10 years old in Grade 4 are MALES?,How many students Age 10 years old in Grade 5 are MALES?,How many students Age 10 years old in Grade 6 are MALES?,How many students Age 10 years old in Grade 1 are FEMALES?,How many students Age 10 years old in Grade 2 are FEMALES?,How many students Age 10 years old in Grade 3 are FEMALES?,How many students Age 10 years old in Grade 4 are FEMALES?,How many students Age 10 years old in Grade 5 are FEMALES?,How many students Age 10 years old in Grade 6 are FEMALES?,How many students Age 11 years old in Grade 1 are MALES?,How many students Age 11 years old in Grade 2 are MALES?,How many students Age 11 years old in Grade 3 are MALES?,How many students Age 11 years old in Grade 4 are MALES?,How many students Age 11 years old in Grade 5 are MALES?,How many students Age 11 years old in Grade 6 are MALES?,How many students Age 11 years old in Grade 1 are FEMALES?,How many students Age 11 years old in Grade 2 are FEMALES?,How many students Age 11 years old in Grade 3 are FEMALES?,How many students Age 11 years old in Grade 4 are FEMALES?,How many students Age 11 years old in Grade 5 are FEMALES?,How many students Age 11 years old in Grade 6 are FEMALES?,How many students Age 12 years old in Grade 1 are MALES?,How many students Age 12 years old in Grade 2 are MALES?,How many students Age 12 years old in Grade 3 are MALES?,How many students Age 12 years old in Grade 4 are MALES?,How many students Age 12 years old in Grade 5 are MALES?,How many students Age 12 years old in Grade 6 are MALES?,How many students Age 12 years old in Grade 1 are FEMALES?,How many students Age 12 years old in Grade 2 are FEMALES?,How many students Age 12 years old in Grade 3 are FEMALES?,How many students 12 years old in Grade 4 are FEMALES?,How many students Age 12 years old in Grade 5 are FEMALES?,How many students Age 12 years old in Grade 6 are FEMALES?,How many students Age 13 years old in Grade 1 are MALES?,How many students Age 13 years old in Grade 2 are MALES?,How many students Age 13 years old in Grade 3 are MALES?,How many students Age 13 years old in Grade 4 are MALES?,How many students Age 13 years old in Grade 5 are MALES?,How many students Age 13 years old in Grade 6 are MALES?,How many students Age 13 years old in Grade 1 are FEMALES?,How many students Age 13 years old in Grade 2 are FEMALES?,How many students Age 13 years old in Grade 3 are FEMALES?,How many students Age 13 years old in Grade 4 are FEMALES?,How many students Age 13 years old in Grade 5 are FEMALES?,How many students Age 13 years old in Grade 6 are FEMALES?,How many students Age 14 years old in Grade 1 are MALES?,How many students Age 14 years old in Grade 2 are MALES?,How many students Age 14 years old in Grade 3 are MALES?,How many students Age 14 years old in Grade 4 are MALES?,How many students Age 14 years old in Grade 5 are MALES?,How many students Age 14 years old in Grade 6 are MALES?,How many students Age 14 years old in Grade 1 are FEMALES?,How many students Age 14 years old in Grade 2 are FEMALES?,How many students Age 14 years old in Grade 3 are FEMALES?,How many students Age 14 years old in Grade 4 are FEMALES?,How many students Age 14 years old in Grade 5 are FEMALES?,How many students Age 14 years old in Grade 6 are FEMALES?,How many students Age 15 years old in Grade 1 are MALES?,How many students Age 15 years old in Grade 2 are MALES?,How many students Age 15 years old in Grade 3 are MALES?,How many students Age 15 years old in Grade 4 are MALES?,How many students Age 15 years old in Grade 5 are MALES?,How many students Age 15 years old in Grade 6 are MALES?,How many students Age 15 years old in Grade 1 are FEMALES?,How many students Age 15 years old in Grade 2 are FEMALES?,How many students Age 15 years old in Grade 3 are FEMALES?,How many students Age 15 years old in Grade 4 are FEMALES?,How many students age 15 Years old in Grade 5 are FEMALES?,How many students age 15 Years old in Grade 6 are FEMALES?,How many students above age 15 Years old in Grade 1 are MALES?,How many students above age 15 Years old in Grade 2 are MALES?,How many students above age 15 Years old in Grade 3 are MALES?,How many students above age 15 Years old in Grade 4 are MALES?,How many students above age 15 Years old in Grade 5 are MALES?,How many students above age 15 Years old in Grade 6 are MALES?,How many students above Age 15 in Grade 1 are FEMALES?,How many students above Age 15 in Grade 2 are FEMALES?,How many students above Age 15 in Grade 3 are FEMALES?,How many students above Age 15 in Grade 4 are FEMALES?,How many students above Age 15 in Grade 5 are FEMALES?,How many students above Age 15 in Grade 6 are FEMALES?,district,count
0,Rivercess,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
1,Nimba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,4.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0,4.0,2.0,0.0,0.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,0.0,0.0,2.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,2.0,2.0,3.0,2.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,District in Bong County,NaN
2,River Gee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
3,Montserrado 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,6.0,5.0,8.0,NaN,NaN,NaN,6.0,7.0,8.0,NaN,NaN,NaN,5.0,5.0,8.0,4.0,NaN,NaN,5.0,7.0,3.0,4.0,NaN,NaN,NaN,4.0,1.0,10.0,NaN,NaN,NaN,4.0,1.0,10.0,NaN,NaN,NaN,NaN,4.0,5.0,NaN,2.0,NaN,2.0,12.0,5.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2.0,2.0,10.0,NaN,NaN,NaN,4.0,10.0,10.0,NaN,NaN,NaN,4.0,10.0,12.0,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
4,Montserrado 1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,5.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,District in Bong County,NaN

# Primary Students by Grade and District

In [98]:
k_s = kpri_melt[(kpri_melt['district']== 'District in Sinoe') & (kpri_melt['count']== 'Greenville')].sum()
k_a = k_s[1:-2]

In [99]:
k_a1 = k_a[::6]
k_a1.sum()

706.0

In [100]:
k_a2 = k_a[1::6]
k_a2.sum()

704.0

In [101]:
k_a3 = k_a[2::6]
k_a3.sum()

655.0

In [102]:
k_a4 = k_a[3::6]
k_a4.sum()

553.0

In [103]:
k_a5 = k_a[4::6]
k_a5.sum()

531.0

In [104]:
k_a6 = k_a[5::6]
k_a6.sum()

550.0

# Primary Student Enrollment by District and Ownershp

In [105]:
kpri_c = kcensus.iloc[:,[2]]
kpri_o = kcensus.iloc[:,[39]]
kpri_s = kpri_student.iloc[:,102:246]

In [106]:
kpri_cdso = pd.concat([kpri_c, kpri_o, kpri_d, kpri_s], axis = 1)
kpri_cdso.columns

Index(['County', 'Type of school', 'District in Bong County',
       'District in Gbarpolu', 'District in River Gee', 'District in Sinoe',
       'District in Lofa', 'District in Nimba', 'District in Grand Cape Mount',
       'District in Maryland',
       ...
       'How many students above age 15 Years old  in Grade 3 are MALES?',
       'How many students above age 15 Years old  in Grade 4 are MALES?',
       'How many students above age 15 Years old  in Grade 5 are MALES?',
       'How many students above age 15 Years old  in Grade 6 are MALES?',
       'How many students  above Age 15 in Grade 1 are FEMALES?',
       'How many students  above Age 15 in Grade 2 are FEMALES?',
       'How many students  above Age 15 in Grade 3 are FEMALES?',
       'How many students  above Age 15 in Grade 4 are FEMALES?',
       'How many students  above Age 15 in Grade 5 are FEMALES?',
       'How many students  above Age 15 in Grade 6 are FEMALES?'],
      dtype='object', length=162)

In [107]:
kpri_melto =kpri_cdso.melt(id_vars=['County','Type of school','How many students  below Age 6 in Grade 1 are MALES?',
 'How many students  below Age 6 in Grade 2 are MALES?',
 'How many students  below Age 6 in Grade 3 are MALES?',
 'How many students  below Age 6 in Grade 4 are MALES?',
 'How many students  below Age 6 in Grade 5 are MALES?',
 'How many students  below Age 6 in Grade 6 are MALES?',
 'How many students  below Age 6 in Grade 1 are FEMALES?',
 'How many students  below Age 6 in Grade 2 are FEMALES?',
 'How many students  below Age 6 in Grade 3 are FEMALES?',
 'How many students  below Age 6 in Grade 4 are FEMALES?',
 'How many students  below Age 6 in Grade 5 are FEMALES?',
 'How many students  below Age 6 in Grade 6 are FEMALES?',
 'How many students  Age 6 years old in Grade 1 are MALES?',
 'How many students  Age 6 years old in Grade 2 are MALES?',
 'How many students  Age 6 years old in Grade 3 are MALES?',
 'How many students  Age 6 years old in Grade 4 are MALES?',
 'How many students  Age 6 years old in Grade 5 are MALES?',
 'How many students  Age 6 years old in Grade 6 are MALES?',
 'How many students  Age 6 years old in Grade 1 are FEMALES?',
 'How many students  Age 6 years old in Grade 2 are FEMALES?',
 'How many students  Age 6 years old in Grade 3 are FEMALES?',
 'How many students  Age 6 years old in Grade 4 are FEMALES?',
 'How many students  Age 6 years old in Grade 5 are FEMALES?',
 'How many students  Age 6 years old in Grade 6 are FEMALES?',
 'How many students  Age 7 years old in Grade 1 are MALES?',
 'How many students  Age 7 years old in Grade 2 are MALES?',
 'How many students  Age 7 years old in Grade 3 are MALES?',
 'How many students  Age 7 years old in Grade 4 are MALES?',
 'How many students  Age 7 years old in Grade 5 are MALES?',
 'How many students  Age 7 years old in Grade 6 are MALES?',
 'How many students  Age 7 years old in Grade 1 are FEMALES?',
 'How many students  Age 7 years old in Grade 2 are FEMALES?',
 'How many students  Age 7 years old in Grade 3 are FEMALES?',
 'How many students  Age 7 years old in Grade 4 are FEMALES?',
 'How many students  Age 7 years old in Grade 5 are FEMALES?',
 'How many students  Age 7 years old in Grade 6 are FEMALES?',
 'How many students  Age 8 years old  in Grade 1 are MALES?',
 'How many students  Age 8 years old  in Grade 2 are MALES?',
 'How many students  Age 8 years old  in Grade 3 are MALES?',
 'How many students  Age 8 years old  in Grade 4 are MALES?',
 'How many students  Age 8 years old  in Grade 5 are MALES?',
 'How many students  Age 8 years old  in Grade 6 are MALES?',
 'How many students  Age 8 years old  in Grade 1 are FEMALES?',
 'How many students  Age 8 years old  in Grade 2 are FEMALES?',
 'How many students  Age 8 years old  in Grade 3 are FEMALES?',
 'How many students  Age 8 years old  in Grade 4 are FEMALES?',
 'How many students  Age 8 years old  in Grade 5 are FEMALES?',
 'How many students  Age 8 years old  in Grade 6 are FEMALES?',
 'How many students   Age 9 years old in Grade 1 are MALES?',
 'How many students   Age 9 years old in Grade 2 are MALES?',
 'How many students   Age 9 years old in Grade 3 are MALES?',
 'How many students   Age 9 years old in Grade 4 are MALES?',
 'How many students   Age 9 years old in Grade 5 are MALES?',
 'How many students   Age 9 years old in Grade 6 are MALES?',
 'How many students  Age 9 years old in Grade 1 are FEMALES?',
 'How many students  Age 9 years old in Grade 2 are FEMALES?',
 'How many students  Age 9 years old in Grade 3 are FEMALES?',
 'How many students  Age 9 years old in Grade 4 are FEMALES?',
 'How many students  Age 9 years old in Grade 5 are FEMALES?',
 'How many students  Age 9 years old in Grade 6 are FEMALES?',
 'How many students  Age 10 years old in Grade 1 are MALES?',
 'How many students  Age 10 years old in Grade 2 are MALES?',
 'How many students  Age 10 years old in Grade 3 are MALES?',
 'How many students  Age 10 years old in Grade 4 are MALES?',
 'How many students  Age 10 years old in Grade 5 are MALES?',
 'How many students  Age 10 years old in Grade 6 are MALES?',
 'How many students  Age 10 years old in Grade 1 are FEMALES?',
 'How many students  Age 10 years old in Grade 2 are FEMALES?',
 'How many students   Age 10 years old in Grade 3 are FEMALES?',
 'How many students   Age 10 years old in Grade 4 are FEMALES?',
 'How many students   Age 10 years old in Grade 5 are FEMALES?',
 'How many students   Age 10 years old in Grade 6 are FEMALES?',
 'How many students   Age 11 years old in Grade 1 are MALES?',
 'How many students   Age 11 years old in Grade 2 are MALES?',
 'How many students   Age 11 years old in Grade 3 are MALES?',
 'How many students   Age 11 years old in Grade 4 are MALES?',
 'How many students   Age 11 years old in Grade 5 are MALES?',
 'How many students   Age 11 years old in Grade 6 are MALES?',
 'How many students   Age 11 years old in Grade 1 are FEMALES?',
 'How many students   Age 11 years old in Grade 2 are FEMALES?',
 'How many students   Age 11 years old in Grade 3 are FEMALES?',
 'How many students   Age 11 years old in Grade 4 are FEMALES?',
 'How many students   Age 11 years old in Grade 5 are FEMALES?',
 'How many students   Age 11 years old in Grade 6 are FEMALES?',
 'How many students  Age 12 years old in Grade 1 are MALES?',
 'How many students  Age 12 years old in Grade 2 are MALES?',
 'How many students  Age 12 years old in Grade 3 are MALES?',
 'How many students  Age 12 years old in Grade 4 are MALES?',
 'How many students  Age 12 years old in Grade 5 are MALES?',
 'How many students  Age 12 years old in Grade 6 are MALES?',
 'How many students  Age 12 years old in Grade 1 are FEMALES?',
 'How many students  Age 12 years old in Grade 2 are FEMALES?',
 'How many students  Age 12 years old in Grade 3 are FEMALES?',
 'How many students   12 years old in Grade 4 are FEMALES?',
 'How many students  Age 12 years old in Grade 5 are FEMALES?',
 'How many students  Age 12 years old in Grade 6 are FEMALES?',
 'How many students  Age 13 years old in Grade 1 are MALES?',
 'How many students  Age 13 years old in Grade 2 are MALES?',
 'How many students  Age 13 years old in Grade 3 are MALES?',
 'How many students  Age 13 years old in Grade 4 are MALES?',
 'How many students  Age 13 years old in Grade 5 are MALES?',
 'How many students  Age 13 years old in Grade 6 are MALES?',
 'How many students  Age 13 years old in Grade 1 are FEMALES?',
 'How many students  Age 13 years old in Grade 2 are FEMALES?',
 'How many students  Age 13 years old in Grade 3 are FEMALES?',
 'How many students  Age 13 years old in Grade 4 are FEMALES?',
 'How many students  Age 13 years old in Grade 5 are FEMALES?',
 'How many students  Age 13 years old in Grade 6 are FEMALES?',
 'How many students Age 14 years old in Grade 1 are MALES?',
 'How many students Age 14 years old in Grade 2 are MALES?',
 'How many students Age 14 years old in Grade 3 are MALES?',
 'How many students Age 14 years old in Grade 4 are MALES?',
 'How many students Age 14 years old in Grade 5 are MALES?',
 'How many students Age 14 years old in Grade 6 are MALES?',
 'How many students  Age 14 years old in Grade 1 are FEMALES?',
 'How many students  Age 14 years old in Grade 2 are FEMALES?',
 'How many students  Age 14 years old in Grade 3 are FEMALES?',
 'How many students  Age 14 years old in Grade 4 are FEMALES?',
 'How many students  Age 14 years old in Grade 5 are FEMALES?',
 'How many students  Age 14 years old in Grade 6 are FEMALES?',
 'How many students  Age 15 years old in Grade 1 are MALES?',
 'How many students  Age 15 years old in Grade 2 are MALES?',
 'How many students  Age 15 years old in Grade 3 are MALES?',
 'How many students  Age 15 years old in Grade 4 are MALES?',
 'How many students  Age 15 years old in Grade 5 are MALES?',
 'How many students  Age 15 years old in Grade 6 are MALES?',
 'How many students  Age 15 years old in Grade 1 are FEMALES?',
 'How many students  Age 15 years old in Grade 2 are FEMALES?',
 'How many students  Age 15 years old in Grade 3 are FEMALES?',
 'How many students  Age 15 years old in Grade 4 are FEMALES?',
 'How many students  age 15 Years old  in Grade 5 are FEMALES?',
 'How many students  age 15 Years old  in Grade 6 are FEMALES?',
 'How many students above age 15 Years old  in Grade 1 are MALES?',
 'How many students above age 15 Years old  in Grade 2 are MALES?',
 'How many students above age 15 Years old  in Grade 3 are MALES?',
 'How many students above age 15 Years old  in Grade 4 are MALES?',
 'How many students above age 15 Years old  in Grade 5 are MALES?',
 'How many students above age 15 Years old  in Grade 6 are MALES?',
 'How many students  above Age 15 in Grade 1 are FEMALES?',
 'How many students  above Age 15 in Grade 2 are FEMALES?',
 'How many students  above Age 15 in Grade 3 are FEMALES?',
 'How many students  above Age 15 in Grade 4 are FEMALES?',
 'How many students  above Age 15 in Grade 5 are FEMALES?',
 'How many students  above Age 15 in Grade 6 are FEMALES?'],var_name = 'district',value_name='count')
kpri_melto.head()

,County,Type of school,How many students below Age 6 in Grade 1 are MALES?,How many students below Age 6 in Grade 2 are MALES?,How many students below Age 6 in Grade 3 are MALES?,How many students below Age 6 in Grade 4 are MALES?,How many students below Age 6 in Grade 5 are MALES?,How many students below Age 6 in Grade 6 are MALES?,How many students below Age 6 in Grade 1 are FEMALES?,How many students below Age 6 in Grade 2 are FEMALES?,How many students below Age 6 in Grade 3 are FEMALES?,How many students below Age 6 in Grade 4 are FEMALES?,How many students below Age 6 in Grade 5 are FEMALES?,How many students below Age 6 in Grade 6 are FEMALES?,How many students Age 6 years old in Grade 1 are MALES?,How many students Age 6 years old in Grade 2 are MALES?,How many students Age 6 years old in Grade 3 are MALES?,How many students Age 6 years old in Grade 4 are MALES?,How many students Age 6 years old in Grade 5 are MALES?,How many students Age 6 years old in Grade 6 are MALES?,How many students Age 6 years old in Grade 1 are FEMALES?,How many students Age 6 years old in Grade 2 are FEMALES?,How many students Age 6 years old in Grade 3 are FEMALES?,How many students Age 6 years old in Grade 4 are FEMALES?,How many students Age 6 years old in Grade 5 are FEMALES?,How many students Age 6 years old in Grade 6 are FEMALES?,How many students Age 7 years old in Grade 1 are MALES?,How many students Age 7 years old in Grade 2 are MALES?,How many students Age 7 years old in Grade 3 are MALES?,How many students Age 7 years old in Grade 4 are MALES?,How many students Age 7 years old in Grade 5 are MALES?,How many students Age 7 years old in Grade 6 are MALES?,How many students Age 7 years old in Grade 1 are FEMALES?,How many students Age 7 years old in Grade 2 are FEMALES?,How many students Age 7 years old in Grade 3 are FEMALES?,How many students Age 7 years old in Grade 4 are FEMALES?,How many students Age 7 years old in Grade 5 are FEMALES?,How many students Age 7 years old in Grade 6 are FEMALES?,How many students Age 8 years old in Grade 1 are MALES?,How many students Age 8 years old in Grade 2 are MALES?,How many students Age 8 years old in Grade 3 are MALES?,How many students Age 8 years old in Grade 4 are MALES?,How many students Age 8 years old in Grade 5 are MALES?,How many students Age 8 years old in Grade 6 are MALES?,How many students Age 8 years old in Grade 1 are FEMALES?,How many students Age 8 years old in Grade 2 are FEMALES?,How many students Age 8 years old in Grade 3 are FEMALES?,How many students Age 8 years old in Grade 4 are FEMALES?,How many students Age 8 years old in Grade 5 are FEMALES?,How many students Age 8 years old in Grade 6 are FEMALES?,How many students Age 9 years old in Grade 1 are MALES?,How many students Age 9 years old in Grade 2 are MALES?,How many students Age 9 years old in Grade 3 are MALES?,How many students Age 9 years old in Grade 4 are MALES?,How many students Age 9 years old in Grade 5 are MALES?,How many students Age 9 years old in Grade 6 are MALES?,How many students Age 9 years old in Grade 1 are FEMALES?,How many students Age 9 years old in Grade 2 are FEMALES?,How many students Age 9 years old in Grade 3 are FEMALES?,How many students Age 9 years old in Grade 4 are FEMALES?,How many students Age 9 years old in Grade 5 are FEMALES?,How many students Age 9 years old in Grade 6 are FEMALES?,How many students Age 10 years old in Grade 1 are MALES?,How many students Age 10 years old in Grade 2 are MALES?,How many students Age 10 years old in Grade 3 are MALES?,How many students Age 10 years old in Grade 4 are MALES?,How many students Age 10 years old in Grade 5 are MALES?,How many students Age 10 years old in Grade 6 are MALES?,How many students Age 10 years old in Grade 1 are FEMALES?,How many students Age 10 years old in Grade 2 are FEMALES?,How many students Age 10 years old in Grade 3 are FEMALES?,How many students Age 10 years old in Grade 4 are FEMALES?,How many students Age 10 years old in Grade 5 are FEMALES?,How many students Age 10 years old in Grade 6 are FEMALES?,How many students Age 11 years old in Grade 1 are MALES?,How many students Age 11 years old in Grade 2 are MALES?,How many students Age 11 years old in Grade 3 are MALES?,How many students Age 11 years old in Grade 4 are MALES?,How many students Age 11 years old in Grade 5 are MALES?,How many students Age 11 years old in Grade 6 are MALES?,How many students Age 11 years old in Grade 1 are FEMALES?,How many students Age 11 years old in Grade 2 are FEMALES?,How many students Age 11 years old in Grade 3 are FEMALES?,How many students Age 11 years old in Grade 4 are FEMALES?,How many students Age 11 years old in Grade 5 are FEMALES?,How many students Age 11 years old in Grade 6 are FEMALES?,How many students Age 12 years old in Grade 1 are MALES?,How many students Age 12 years old in Grade 2 are MALES?,How many students Age 12 years old in Grade 3 are MALES?,How many students Age 12 years old in Grade 4 are MALES?,How many students Age 12 years old in Grade 5 are MALES?,How many students Age 12 years old in Grade 6 are MALES?,How many students Age 12 years old in Grade 1 are FEMALES?,How many students Age 12 years old in Grade 2 are FEMALES?,How many students Age 12 years old in Grade 3 are FEMALES?,How many students 12 years old in Grade 4 are FEMALES?,How many students Age 12 years old in Grade 5 are FEMALES?,How many students Age 12 years old in Grade 6 are FEMALES?,How many students Age 13 years old in Grade 1 are MALES?,How many students Age 13 years old in Grade 2 are MALES?,How many students Age 13 years old in Grade 3 are MALES?,How many students Age 13 years old in Grade 4 are MALES?,How many students Age 13 years old in Grade 5 are MALES?,How many students Age 13 years old in Grade 6 are MALES?,How many students Age 13 years old in Grade 1 are FEMALES?,How many students Age 13 years old in Grade 2 are FEMALES?,How many students Age 13 years old in Grade 3 are FEMALES?,How many students Age 13 years old in Grade 4 are FEMALES?,How many students Age 13 years old in Grade 5 are FEMALES?,How many students Age 13 years old in Grade 6 are FEMALES?,How many students Age 14 years old in Grade 1 are MALES?,How many students Age 14 years old in Grade 2 are MALES?,How many students Age 14 years old in Grade 3 are MALES?,How many students Age 14 years old in Grade 4 are MALES?,How many students Age 14 years old in Grade 5 are MALES?,How many students Age 14 years old in Grade 6 are MALES?,How many students Age 14 years old in Grade 1 are FEMALES?,How many students Age 14 years old in Grade 2 are FEMALES?,How many students Age 14 years old in Grade 3 are FEMALES?,How many students Age 14 years old in Grade 4 are FEMALES?,How many students Age 14 years old in Grade 5 are FEMALES?,How many students Age 14 years old in Grade 6 are FEMALES?,How many students Age 15 years old in Grade 1 are MALES?,How many students Age 15 years old in Grade 2 are MALES?,How many students Age 15 years old in Grade 3 are MALES?,How many students Age 15 years old in Grade 4 are MALES?,How many students Age 15 years old in Grade 5 are MALES?,How many students Age 15 years old in Grade 6 are MALES?,How many students Age 15 years old in Grade 1 are FEMALES?,How many students Age 15 years old in Grade 2 are FEMALES?,How many students Age 15 years old in Grade 3 are FEMALES?,How many students Age 15 years old in Grade 4 are FEMALES?,How many students age 15 Years old in Grade 5 are FEMALES?,How many students age 15 Years old in Grade 6 are FEMALES?,How many students above age 15 Years old in Grade 1 are MALES?,How many students above age 15 Years old in Grade 2 are MALES?,How many students above age 15 Years old in Grade 3 are MALES?,How many students above age 15 Years old in Grade 4 are MALES?,How many students above age 15 Years old in Grade 5 are MALES?,How many students above age 15 Years old in Grade 6 are MALES?,How many students above Age 15 in Grade 1 are FEMALES?,How many students above Age 15 in Grade 2 are FEMALES?,How many students above Age 15 in Grade 3 are FEMALES?,How many students above Age 15 in Grade 4 are FEMALES?,How many students above Age 15 in Grade 5 are FEMALES?,How many students above Age 15 in Grade 6 are FEMALES?,district,count
0,Rivercess,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
1,Nimba,Public,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,4.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0,4.0,2.0,0.0,0.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,2.0,1.0,0.0,2.0,0.0,0.0,2.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0,3.0,0.0,4.0,2.0,2.0,3.0,2.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,District in Bong County,NaN
2,River Gee,Public,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
3,Montserrado 1,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,6.0,5.0,8.0,NaN,NaN,NaN,6.0,7.0,8.0,NaN,NaN,NaN,5.0,5.0,8.0,4.0,NaN,NaN,5.0,7.0,3.0,4.0,NaN,NaN,NaN,4.0,1.0,10.0,NaN,NaN,NaN,4.0,1.0,10.0,NaN,NaN,NaN,NaN,4.0,5.0,NaN,2.0,NaN,2.0,12.0,5.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,2.0,2.0,10.0,NaN,NaN,NaN,4.0,10.0,10.0,NaN,NaN,NaN,4.0,10.0,12.0,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,District in Bong County,NaN
4,Montserrado 1,Private,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,5.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,District in Bong County,NaN

In [108]:
k_s1 = kpri_melto.groupby('Type of school').sum()
k_s1

,How many students below Age 6 in Grade 1 are MALES?,How many students below Age 6 in Grade 2 are MALES?,How many students below Age 6 in Grade 3 are MALES?,How many students below Age 6 in Grade 4 are MALES?,How many students below Age 6 in Grade 5 are MALES?,How many students below Age 6 in Grade 6 are MALES?,How many students below Age 6 in Grade 1 are FEMALES?,How many students below Age 6 in Grade 2 are FEMALES?,How many students below Age 6 in Grade 3 are FEMALES?,How many students below Age 6 in Grade 4 are FEMALES?,How many students below Age 6 in Grade 5 are FEMALES?,How many students below Age 6 in Grade 6 are FEMALES?,How many students Age 6 years old in Grade 1 are MALES?,How many students Age 6 years old in Grade 2 are MALES?,How many students Age 6 years old in Grade 3 are MALES?,How many students Age 6 years old in Grade 4 are MALES?,How many students Age 6 years old in Grade 5 are MALES?,How many students Age 6 years old in Grade 6 are MALES?,How many students Age 6 years old in Grade 1 are FEMALES?,How many students Age 6 years old in Grade 2 are FEMALES?,How many students Age 6 years old in Grade 3 are FEMALES?,How many students Age 6 years old in Grade 4 are FEMALES?,How many students Age 6 years old in Grade 5 are FEMALES?,How many students Age 6 years old in Grade 6 are FEMALES?,How many students Age 7 years old in Grade 1 are MALES?,How many students Age 7 years old in Grade 2 are MALES?,How many students Age 7 years old in Grade 3 are MALES?,How many students Age 7 years old in Grade 4 are MALES?,How many students Age 7 years old in Grade 5 are MALES?,How many students Age 7 years old in Grade 6 are MALES?,How many students Age 7 years old in Grade 1 are FEMALES?,How many students Age 7 years old in Grade 2 are FEMALES?,How many students Age 7 years old in Grade 3 are FEMALES?,How many students Age 7 years old in Grade 4 are FEMALES?,How many students Age 7 years old in Grade 5 are FEMALES?,How many students Age 7 years old in Grade 6 are FEMALES?,How many students Age 8 years old in Grade 1 are MALES?,How many students Age 8 years old in Grade 2 are MALES?,How many students Age 8 years old in Grade 3 are MALES?,How many students Age 8 years old in Grade 4 are MALES?,How many students Age 8 years old in Grade 5 are MALES?,How many students Age 8 years old in Grade 6 are MALES?,How many students Age 8 years old in Grade 1 are FEMALES?,How many students Age 8 years old in Grade 2 are FEMALES?,How many students Age 8 years old in Grade 3 are FEMALES?,How many students Age 8 years old in Grade 4 are FEMALES?,How many students Age 8 years old in Grade 5 are FEMALES?,How many students Age 8 years old in Grade 6 are FEMALES?,How many students Age 9 years old in Grade 1 are MALES?,How many students Age 9 years old in Grade 2 are MALES?,How many students Age 9 years old in Grade 3 are MALES?,How many students Age 9 years old in Grade 4 are MALES?,How many students Age 9 years old in Grade 5 are MALES?,How many students Age 9 years old in Grade 6 are MALES?,How many students Age 9 years old in Grade 1 are FEMALES?,How many students Age 9 years old in Grade 2 are FEMALES?,How many students Age 9 years old in Grade 3 are FEMALES?,How many students Age 9 years old in Grade 4 are FEMALES?,How many students Age 9 years old in Grade 5 are FEMALES?,How many students Age 9 years old in Grade 6 are FEMALES?,How many students Age 10 years old in Grade 1 are MALES?,How many students Age 10 years old in Grade 2 are MALES?,How many students Age 10 years old in Grade 3 are MALES?,How many students Age 10 years old in Grade 4 are MALES?,How many students Age 10 years old in Grade 5 are MALES?,How many students Age 10 years old in Grade 6 are MALES?,How many students Age 10 years old in Grade 1 are FEMALES?,How many students Age 10 years old in Grade 2 are FEMALES?,How many students Age 10 years old in Grade 3 are FEMALES?,How many students Age 10 years old in Grade 4 are FEMALES?,How many students Age 10 years old in Grade 5 are FEMALES?,How many students Age 10 years old in Grade 6 are FEMALES?,How many students Age 11 years old in Grade 1 are MALES?,How many students Age 11 years old in Grade 2 are MALES?,How many students Age 11 years old in Grade 3 are MALES?,How many students Age 11 years old in Grade 4 are MALES?,How many students Age 11 years old in Grade 5 are MALES?,How many students Age 11 years old in Grade 6 are MALES?,How many students Age 11 years old in Grade 1 are FEMALES?,How many students Age 11 years old in Grade 2 are FEMALES?,How many students Age 11 years old in Grade 3 are FEMALES?,How many students Age 11 years old in Grade 4 are FEMALES?,How many students Age 11 years old in Grade 5 are FEMALES?,How many students Age 11 years old in Grade 6 are FEMALES?,How many students Age 12 years old in Grade 1 are MALES?,How many students Age 12 years old in Grade 2 are MALES?,How many students Age 12 years old in Grade 3 are MALES?,How many students Age 12 years old in Grade 4 are MALES?,How many students Age 12 years old in Grade 5 are MALES?,How many students Age 12 years old in Grade 6 are MALES?,How many students Age 12 years old in Grade 1 are FEMALES?,How many students Age 12 years old in Grade 2 are FEMALES?,How many students Age 12 years old in Grade 3 are FEMALES?,How many students 12 years old in Grade 4 are FEMALES?,How many students Age 12 years old in Grade 5 are FEMALES?,How many students Age 12 years old in Grade 6 are FEMALES?,How many students Age 13 years old in Grade 1 are MALES?,How many students Age 13 years old in Grade 2 are MALES?,How many students Age 13 years old in Grade 3 are MALES?,How many students Age 13 years old in Grade 4 are MALES?,How many students Age 13 years old in Grade 5 are MALES?,How many students Age 13 years old in Grade 6 are MALES?,How many students Age 13 years old in Grade 1 are FEMALES?,How many students Age 13 years old in Grade 2 are FEMALES?,How many students Age 13 years old in Grade 3 are FEMALES?,How many students Age 13 years old in Grade 4 are FEMALES?,How many students Age 13 years old in Grade 5 are FEMALES?,How many students Age 13 years old in Grade 6 are FEMALES?,How many students Age 14 years old in Grade 1 are MALES?,How many students Age 14 years old in Grade 2 are MALES?,How many students Age 14 years old in Grade 3 are MALES?,How many students Age 14 years old in Grade 4 are MALES?,How many students Age 14 years old in Grade 5 are MALES?,How many students Age 14 years old in Grade 6 are MALES?,How many students Age 14 years old in Grade 1 are FEMALES?,How many students Age 14 years old in Grade 2 are FEMALES?,How many students Age 14 years old in Grade 3 are FEMALES?,How many students Age 14 years old in Grade 4 are FEMALES?,How many students Age 14 years old in Grade 5 are FEMALES?,How many students Age 14 years old in Grade 6 are FEMALES?,How many students Age 15 years old in Grade 1 are MALES?,How many students Age 15 years old in Grade 2 are MALES?,How many students Age 15 years old in Grade 3 are MALES?,How many students Age 15 years old in Grade 4 are MALES?,How many students Age 15 years old in Grade 5 are MALES?,How many students Age 15 years old in Grade 6 are MALES?,How many students Age 15 years old in Grade 1 are FEMALES?,How many students Age 15 years old in Grade 2 are FEMALES?,How many students Age 15 years old in Grade 3 are FEMALES?,How many students Age 15 years old in Grade 4 are FEMALES?,How many students age 15 Years old in Grade 5 are FEMALES?,How many students age 15 Years old in Grade 6 are FEMALES?,How many students above age 15 Years old in Grade 1 are MALES?,How many students above age 15 Years old in Grade 2 are MALES?,How many students above age 15 Years old in Grade 3 are MALES?,How many students above age 15 Years old in Grade 4 are MALES?,How many students above age 15 Years old in Grade 5 are MALES?,How many students above age 15 Years old in Grade 6 are MALES?,How many students above Age 15 in Grade 1 are FEMALES?,How many students above Age 15 in Grade 2 are FEMALES?,How many students above Age 15 in Grade 3 are FEMALES?,How many students above Age 15 in Grade 4 are FEMALES?,How many students above Age 15 in Grade 5 are FEMALES?,How many students above Age 15 in Grade 6 are FEMALES?
Type of school,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Community,1344.0,496.0,1344.0,288.0,176.0,96.0,1152.0,464.0,320.0,400.0,240.0,96.0,2880.0,1200.0,1152.0,480.0,480.0,80.0,2208.0,1104.0,992.0,480.0,512.0,32.0,4304.0,3136.0,2128.0,912.0,800.0,224.0,4656.0,2864.0,1920.0,944.0,560.0,384.0,4048.0,3568.0,3296.0,1376.0,736.0,672.0,3776.0,3520.0,2672.0,1216.0,624.0,368.0,3536.0,3472.0,2896.0,2720.0,1248.0,848.0,2544.0,3216.0,3168.0,1952.0,1408.0,928.0,2416.0,2176.0,3488.0,2704.0,1808.0,1584.0,2688.0,2688.0,3232.0,2640.0,2256.0,1680.0,1952.0,1504.0,2240.0,2592.0,1456.0,1632.0,1920.0,1520.0,2096.0,2288.0,1632.0,1056.0,1696.0,1568.0,1824.0,2096.0,2640.0,1840.0,1520.0,1936.0,2208.0,2128.0,2352.0,2160.0,1632.0,1200.0,1792.0,2032.0,2816.0,1744.0,1168.0,1344.0,1664.0,2112.0,2400.0,2080.0,512.0,832.0,1008.0,1680.0,2288.0,2112.0,176.0,880.0,1120.0,1696.0,1920.0,2464.0,464.0,672.0,736.0,1168.0,1472.0,1808.0,544.0,432.0,832.0,1136.0,2032.0,1792.0,368.0,336.0,304.0,848.0,1632.0,2096.0,304.0,272.0,512.0,656.0,1392.0,2096.0
Faith-based,4464.0,1808.0,1216.0,576.0,544.0,704.0,5536.0,2480.0,1104.0,784.0,4624.0,704.0,16448.0,5952.0,2272.0,1456.0,1456.0,928.0,16656.0,7408.0,2832.0,1216.0,1216.0,1136.0,18960.0,14848.0,7808.0,3472.0,1712.0,832.0,20048.0,17360.0,6192.0,3168.0,1472.0,832.0,17808.0,15168.0,13760.0,6352.0,3648.0,1680.0,19296.0,15600.0,16464.0,8240.0,3408.0,1888.0,14144.0,14928.0,13232.0,10672.0,4976.0,3168.0,13536.0,13616.0,14928.0,13536.0,6048.0,3392.0,11344.0,12816.0,13472.0,11904.0,11088.0,4848.0,12064.0,13792.0,14944.0,13392.0,11328.0,4848.0,7440.0,9984.0,11040.0,11184.0,11200.0,8176.0,7008.0,10752.0,13792.0,15088.0,13328.0,10272.0,7584.0,9664.0,10512.0,13136.0,12560.0,11504.0,6048.0,9008.0,12608.0,14848.0,13872.0,13728.0,3744.0,5040.0,7424.0,10800.0,12560.0,12448.0,4112.0,4976.0,9664.0,12624.0,13248.0,13536.0,1808.0,2928.0,5328.0,8896.0,10736.0,12736.0,336.0,2640.0,5616.0,8464.0,11952.0,14800.0,1776.0,1840.0,2640.0,4896.0,7696.0,11296.0,1632.0,1824.0,3456.0,4640.0,9312.0,12048.0,1696.0,1856.0,2192.0,3952.0,6432.0,15680.0,1392.0,1632.0,2448.0,3600.0,5920.0,11680.0
Private,11520.0,7152.0,3840.0,3024.0,1952.0,2416.0,14416.0,7280.0,3952.0,2912.0,2672.0,2160.0,36688.0,13792.0,6096.0,3072.0,2960.0,2864.0,38880.0,14816.0,8016.0,4720.0,2880.0,2672.0,36416.0,34032.0,13712.0,7776.0,4768.0,3040.0,37920.0,34448.0,14800.0,8080.0,4784.0,4016.0,29920.0,30464.0,28400.0,13488.0,7728.0,4304.0,30656.0,32640.0,29968.0,14832.0,9200.0,4688.0,24128.0,27824.0,28384.0,23936.0,13552.0,7984.0,24112.0,28096.0,29216.0,24848.0,12320.0,6464.0,18128.0,22944.0,24976.0,25152.0,22000.0,11120.0,18944.0,22032.0,26912.0,24672.0,23456.0,10672.0,11744.0,14640.0,21376.0,22640.0,20704.0,20752.0,11632.0,16224.0,21936.0,24720.0,24224.0,21104.0,7808.0,10688.0,16304.0,20208.0,24464.0,20560.0,7600.0,12272.0,17264.0,24064.0,26208.0,21600.0,3936.0,6864.0,11424.0,15888.0,21344.0,20304.0,4400.0,7136.0,11920.0,17632.0,22224.0,21552.0,2720.0,4448.0,7152.0,9920.0,15360.0,20928.0,1008.0,4144.0,7872.0,11728.0,17760.0,22304.0,1984.0,1760.0,3712.0,6368.0,10768.0,15216.0,2128.0,2176.0,4064.0,7216.0,10432.0,16288.0,1568.0,1824.0,2864.0,4992.0,8144.0,14768.0,1616.0,2016.0,2800.0,4336.0,8464.0,14192.0
Public,6896.0,3248.0,3088.0,1680.0,1584.0,2432.0,5248.0,2704.0,1136.0,1616.0,672.0,672.0,38480.0,7888.0,3632.0,1664.0,960.0,528.0,18960.0,7456.0,2560.0,784.0,944.0,800.0,35120.0,21232.0,11680.0,3392.0,2624.0,1504.0,30288.0,18624.0,8464.0,3216.0,1376.0,1504.0,45536.0,30352.0,19536.0,8608.0,3760.0,2128.0,38640.0,25200.0,17696.0,8432.0,2848.0,1504.0,45232.0,35072.0,22864.0,15776.0,10672.0,3920.0,38224.0,30032.0,20816.0,13168.0,5792.0,2512.0,50528.0,39296.0,31184.0,22064.0,13120.0,5664.0,42528.0,34656.0,26672.0,17200.0,10608.0,4976.0,37296.0,37440.0,31008.0,24448.0,16288.0,9616.0,33312.0,31184.0,28544.0,20048.0,12464.0,6592.0,33520.0,39232.0,36576.0,33808.0,20288.0,14304.0,29632.0,34976.0,34640.0,27728.0,18272.0,11456.0,22848.0,29072.0,38080.0,35152.0,27728.0,19216.0,18608.0,27312.0,32464.0,31040.0,24768.0,16640.0,15728.0,20080.0,30064.0,37440.0,35264.0,28704.0,928.0,18400.0,24608.0,33296.0,31568.0,27232.0,10000.0,14016.0,21888.0,31632.0,35728.0,35600.0,7792.0,11024.0,18288.0,24704.0,30928.0,31856.0,9056.0,11936.0,18576.0,30176.0,41040.0,54048.0,7488.0,8496.0,14432.0,24656.0,32480.0,47408.0

In [109]:
#calculating primary students by district by school levels
k_s2 = kpri_melto[(kpri_melto['district']== 'District in Montserrado 2') & (kpri_melto['count']== 'Right Bank 3')].groupby('Type of school').sum(1).sum(1)
k_s2

Type of school
Faith-based     819.0
Private        3401.0
Public         2079.0
dtype: float64

In [110]:
ka_nur = k_a[:2].append(k_a[6:20])
#ka_nur

In [111]:
ka_nur.sum()

138.0

In [112]:
ka_pk = k_a[2:4].append(k_a[20:34])
#ka_pk

In [113]:
ka_pk.sum()

188.0

In [114]:
ka_k = k_a[4:6].append(k_a[34:])
#ka_k

In [115]:
ka_k.sum()

3373.0

# Enrollment by District and Ownership

In [116]:
kece_c.head()

          County
0      Rivercess
1          Nimba
2      River Gee
3  Montserrado 1
4  Montserrado 1

In [117]:
kece_c = kcensus.iloc[:,[2]]
kece_o = kcensus.iloc[:,[39]]
kece_s = kece_student.iloc[:,46:87]
kece_c = kcensus.iloc[:,[2]]
kece_d = kcensus.iloc[:,3:19]
kece_s = kece_student.iloc[:,46:87]

NameError: name 'kece_student' is not defined

In [118]:
kece_cdso = pd.concat([kece_c, kece_o, kece_d, kece_s], axis = 1)
kece_cdso.columns

NameError: name 'kece_d' is not defined

In [ ]:
kece_melto =kece_cdso.melt(id_vars=['County', 'Type of school','How many MALE students below AGE 3 YEARS OLD are in Nursery?',
       'How many FEMALE students below AGE 3 YEARS OLD are in Nursery?',
       'How many MALE students below AGE 3 YEARS OLD are in Pre-kindergarten?',
       'How many FEMALE students below AGE 3 YEARS OLD are in Pre-kindergarten?',
       'How many MALE students below AGE 3 YEARS OLD are in Kindergarten?',
       'How many FEMALE students below AGE 3 YEARS OLD are in Kindergarten?',
       'How many MALE students AGE 3 YEARS OLD are in Nursery?',
       'How many MALE students AGE 4 YEARS OLD are in Nursery?',
       'How many MALE students AGE 5 YEARS OLD are in Nursery?',
       'How many MALE students AGE 6 YEARS OLD are in Nursery?',
       'How many MALE students AGE 7 YEARS OLD are in Nursery?',
       'How many MALE students AGE 8 YEARS OLD are in Nursery?',
       'How many MALE students Above AGE 8 YEARS OLD are in Nursery?',
       'How many FEMALE students  AGE 3 YEARS OLD are in Nursery?',
       'How many FEMALE students  AGE 4 YEARS OLD are in Nursery?',
       'How many FEMALE students  AGE 5 YEARS OLD are in Nursery?',
       'How many FEMALE students  AGE 6 YEARS OLD are in Nursery?',
       'How many FEMALE students  AGE 7 YEARS OLD are in Nursery?',
       'How many FEMALE students  AGE 8 YEARS OLD are in Nursery?',
       'How many FEMALE students  above AGE 8 YEARS OLD are in Nursery?',
       'How many MALE students AGE 3 YEARS OLD are in Pre-Kindergarten?',
       'How many MALE students AGE 4 YEARS OLD are in Pre-Kindergarten?',
       'How many MALE students AGE 5 YEARS OLD are in Pre-Kindergarten?',
       'How many MALE students AGE 6 YEARS OLD are in Pre-Kindergarten?',
       'How many MALE students AGE 7 YEARS OLD are in Pre-Kindergarten?',
       'How many MALE students AGE 8 YEARS OLD are in Pre-Kindergarten?',
       'How many MALE students above AGE 8 YEARS OLD are in Pre-Kindergarten?',
       'How many FEMALE students  AGE 3 YEARS OLD are in Pre-Kindergarten?',
       'How many FEMALE students  AGE 4 YEARS OLD are in Pre-Kindergarten?',
       'How many FEMALE students  AGE 5 YEARS OLD are in Pre-Kindergarten?',
       'How many FEMALE students  AGE 6 YEARS OLD are in Pre-Kindergarten?',
       'How many FEMALE students  AGE 7 YEARS OLD are in Pre-Kindergarten?',
       'How many FEMALE students  AGE 8 YEARS OLD are in Pre-Kindergarten?',
       'How many FEMALE students  above AGE 8 YEARS OLD are in Pre-Kindergarten?',
       'How many MALE students AGE 3 YEARS OLD are in Kindergarten?',
       'How many MALE students AGE 4 YEARS OLD are in Kindergarten?',
       'How many FEMALE students  AGE 5 YEARS OLD are in Kindergarten?',
       'How many FEMALE students  AGE 6 YEARS OLD are in Kindergarten?',
       'How many FEMALE students  AGE 7 YEARS OLD are in Kindergarten?',
       'How many FEMALE students  AGE 8 YEARS OLD are in Kindergarten?',
       'How many FEMALE students  above AGE 8 YEARS OLD are in Kindergarten?'],var_name = 'district',value_name='count')
#kece_melto.head()

In [ ]:
k_so = kece_melto[(kece_melt['district']== 'District in Gbarpolu') & (kece_melt['count']== 'Gbarma')].head(2).groupby('Type of school').sum()#.sum(1)
k_so

In [ ]:
k_so = kece_melto[(kece_melt['district']== 'District in Sinoe') & (kece_melt['count']== 'Greenville')].groupby('Type of school').sum().sum(1)
k_so

In [ ]:
kece_c = kcensus.iloc[:,[2]]
kece_o = kcensus.iloc[:,[39]]
kece_s = kece_student.iloc[:,46:87]
kece_c = kcensus.iloc[:,[2]]
kece_d = kcensus.iloc[:,3:19]
kece_s = kece_student.iloc[:,46:87]
kece_disa = kece_student.iloc[:,22:46]

In [ ]:
kece_cdd = pd.concat([kece_c, kece_d, kece_disa], axis = 1)
kece_cdd.columns

In [ ]:
dd = kece_cdd.groupby('County').sum()
#dd

In [ ]:
k_od = kece_cdd[(kece_cdd['district']== 'District in Sinoe') & (kece_cdd['count']== 'Greenville')].groupby('Type of school').sum()#.sum(1)

In [41]:
#dd.iloc[:,:6].sum(1)#.sum() #+
dd.iloc[:,6:12].sum(1)#.sum()#+ 
#dd.iloc[:,12:18].sum(1).sum() + 
#dd.iloc[:,18:].sum(1).sum()

NameError: name 'dd' is not defined

In [42]:
dd.iloc[:,6:12].sum(1).sum()

NameError: name 'dd' is not defined

In [43]:
dd.iloc[:,12:18].sum(1).sum()

NameError: name 'dd' is not defined

In [ ]:
kece_meltdd =kece_cdd.melt(id_vars=['County', 'How many MALE students in nursery are Visually impaired ?',
       'How many female students in Nursery are Visually impaired ?',
       'How many FEMALE students in Pre-Kindergarten are Visually impaired ?',
       'How many MALE students in pre-Kindergarten are Visually impaired ?',
       'How many FEMALE students in kindergarten are Visually impaired ?',
       'How many MALE students in kindergarten are Visually impaired ?',
       'How many MALE students in  nursery have hearing impairment?',
       'How many FEMALE students in nursery have hearing impairment?',
       'How many FEMALE students in pre- kindergarten are hearing impairment?',
       'How many MALE students in pre-kindergarten have hearing impairment?',
       'How many MALE students in kindergarten have hearing impairment?',
       'How many FEMALE students in  Kindergarten have hearing impairment?',
       'How many MALE students in Nursery have other physical disabilities?',
       'How many FEMALE students in Nursery have other physical disabilities ?',
       'How many FEMALE students in  Pre-Kindergarten have other physical disabilities?',
       'How many MALE students in  Pre-Kindergarten have other physical disabilities?',
       'How many MALE students in  Kindergarten have other physical disabilities?',
       'How many FEMALE students in  Kindergarten have other physical disabilities?',
       'How many MALE students in Nursery have other mental disability or learning difficulty?',
       'How many FEMALE students in Nursery have other mental disability or learning difficulty?',
       'How many MALE students in  Pre-Kindergarten have other mental disability or learning difficulty?',
       'How many FEMALE students in  Pre-Kindergarten have other mental disability or learning difficulty?',
       'How many MALE students in  Kindergarten have other mental disability or learning difficulty?',
       'How many FEMALE students in  Kindergarten have other mental disability or learning difficulty?'],var_name = 'district',value_name='count')
kece_meltdd.head()

In [44]:
kece_meltdd.iloc[:,18:]#.sum(1).sum()

NameError: name 'kece_meltdd' is not defined

In [ ]:
#ece disability disagregated by gender
#dd.iloc[:,0,3]

In [ ]:
d_1 = dd.sum()

In [45]:
#d_1.sum()

In [46]:
district_dic =pd.Series(kece_cdso.columns[2:18])
district_dic.to_csv('district_dic.csv', index = False)

NameError: name 'kece_cdso' is not defined

In [47]:
d_2 = dd.iloc[:,:6].sum()
d_2

NameError: name 'dd' is not defined

In [48]:
d_2[[0,3,5]].sum()

NameError: name 'd_2' is not defined

In [49]:
d_2.sum()

NameError: name 'd_2' is not defined

In [ ]:
dd.iloc[:,6:12].sum()[[0,3,4]].sum()

In [50]:
dd.iloc[:,6:12].sum().sum()

NameError: name 'dd' is not defined

In [ ]:
dd.iloc[:,12:18].sum()[[0,3,4]].sum()

In [ ]:
dd.iloc[:,12:18].sum().sum()

In [51]:
dd.iloc[:,18:].sum()[[0,2,4]].sum()

NameError: name 'dd' is not defined

In [ ]:
dd.iloc[:,18:].sum().sum()

In [ ]:
dd

In [ ]:
dd.iloc[:].sum()[[22,23]].sum()

In [ ]:
kece_cdso.head()

In [52]:
ece_vi_c=kece_cdso.iloc[:,[0,2,3,4,5,6,7]]
ece_vi_c

NameError: name 'kece_cdso' is not defined

In [ ]:
ece_vi_c.groupby('County').sum().sum(1)

In [ ]:
ece_hp_c=kece_cdso.iloc[:,[0,8,9,10,11,12,13]]
ece_hp_c.groupby('County').sum().sum(1)

In [53]:
ece_p_c=kece_cdso.iloc[:,[0,14,15,16,17,18,19]]
ece_p_c.groupby('County').sum().sum(1)

NameError: name 'kece_cdso' is not defined

In [ ]:
ece_m_c=kece_cdso.iloc[:,[0,20,21,22,23,24,25]]
ece_m_c.groupby('County').sum().sum(1)

In [54]:
k_od = kece_meltdd[(kece_meltdd['district']== 'District in Sinoe') & (kece_meltdd['count']== 'Central Kpanyan')].sum()#.sum(1)#.groupby('Type of school').sum()#.sum(1)

kdis=k_od[1:-2]

kdis

NameError: name 'kece_meltdd' is not defined

In [55]:
#visual
kdis[:6].sum()

NameError: name 'kdis' is not defined

In [ ]:
#hearing
kdis[6:12].sum()

In [ ]:
#physical
kdis[12:18].sum()

In [56]:
#mental
kdis[18:24].sum()

NameError: name 'kdis' is not defined

In [75]:
kece_c = kcensus.iloc[:,[2]]
kece_o = kcensus.iloc[:,[39]]
kece_s = kece_student.iloc[:,46:87]
kece_c = kcensus.iloc[:,[2]]
kece_d = kcensus.iloc[:,3:19]
kece_s = kece_student.iloc[:,46:87]
kece_disa = kece_student.iloc[:,22:46]

NameError: name 'kece_student' is not defined

In [57]:
kece_cdd = pd.concat([kece_c, kece_d, kece_disa], axis = 1)
kece_cdd.columns

NameError: name 'kece_c' is not defined

In [ ]:
kece_cdd.head()

In [58]:
kece_meltdd =kece_cdd.melt(id_vars=['County','How many MALE students in nursery are Visually impaired ?',
       'How many female students in Nursery are Visually impaired ?',
       'How many FEMALE students in Pre-Kindergarten are Visually impaired ?',
       'How many MALE students in pre-Kindergarten are Visually impaired ?',
       'How many FEMALE students in kindergarten are Visually impaired ?',
       'How many MALE students in kindergarten are Visually impaired ?',
       'How many MALE students in  nursery have hearing impairment?',
       'How many FEMALE students in nursery have hearing impairment?',
       'How many FEMALE students in pre- kindergarten are hearing impairment?',
       'How many MALE students in pre-kindergarten have hearing impairment?',
       'How many MALE students in kindergarten have hearing impairment?',
       'How many FEMALE students in  Kindergarten have hearing impairment?',
       'How many MALE students in Nursery have other physical disabilities?',
       'How many FEMALE students in Nursery have other physical disabilities ?',
       'How many FEMALE students in  Pre-Kindergarten have other physical disabilities?',
       'How many MALE students in  Pre-Kindergarten have other physical disabilities?',
       'How many MALE students in  Kindergarten have other physical disabilities?',
       'How many FEMALE students in  Kindergarten have other physical disabilities?',
       'How many MALE students in Nursery have other mental disability or learning difficulty?',
       'How many FEMALE students in Nursery have other mental disability or learning difficulty?',
       'How many MALE students in  Pre-Kindergarten have other mental disability or learning difficulty?',
       'How many FEMALE students in  Pre-Kindergarten have other mental disability or learning difficulty?',
       'How many MALE students in  Kindergarten have other mental disability or learning difficulty?',
       'How many FEMALE students in  Kindergarten have other mental disability or learning difficulty?'],var_name = 'district',value_name='count')
kdd_1 = kece_meltdd
#kdd_1['district'].unique()
kdd_1['count'].unique()

NameError: name 'kece_cdd' is not defined

In [59]:
d15 = kdd_1[(kdd_1['district']=='District in Montserrado 1') &(kdd_1['count']== 'Paynesville 1')].sum()
dk15 = d15[1:-2]
dk15

NameError: name 'kdd_1' is not defined

In [ ]:
dk15[:6].sum()

In [60]:
dk15[6:12].sum()

NameError: name 'dk15' is not defined

In [ ]:
dk15[12:18].sum()

In [ ]:
dk15[18:].sum()

In [ ]:
kece_cdso.head()

In [61]:
h = kece_cdso.iloc[:,:26].groupby('County').sum()
h.iloc[:,18:].sum(1)

NameError: name 'kece_cdso' is not defined

In [ ]:
kece_meltdd =kece_cdd.melt(id_vars=['County', 'How many MALE students in nursery are Visually impaired ?',
       'How many female students in Nursery are Visually impaired ?',
       'How many FEMALE students in Pre-Kindergarten are Visually impaired ?',
       'How many MALE students in pre-Kindergarten are Visually impaired ?',
       'How many FEMALE students in kindergarten are Visually impaired ?',
       'How many MALE students in kindergarten are Visually impaired ?',
       'How many MALE students in  nursery have hearing impairment?',
       'How many FEMALE students in nursery have hearing impairment?',
       'How many FEMALE students in pre- kindergarten are hearing impairment?',
       'How many MALE students in pre-kindergarten have hearing impairment?',
       'How many MALE students in kindergarten have hearing impairment?',
       'How many FEMALE students in  Kindergarten have hearing impairment?',
       'How many MALE students in Nursery have other physical disabilities?',
       'How many FEMALE students in Nursery have other physical disabilities ?',
       'How many FEMALE students in  Pre-Kindergarten have other physical disabilities?',
       'How many MALE students in  Pre-Kindergarten have other physical disabilities?',
       'How many MALE students in  Kindergarten have other physical disabilities?',
       'How many FEMALE students in  Kindergarten have other physical disabilities?',
       'How many MALE students in Nursery have other mental disability or learning difficulty?',
       'How many FEMALE students in Nursery have other mental disability or learning difficulty?',
       'How many MALE students in  Pre-Kindergarten have other mental disability or learning difficulty?',
       'How many FEMALE students in  Pre-Kindergarten have other mental disability or learning difficulty?',
       'How many MALE students in  Kindergarten have other mental disability or learning difficulty?',
       'How many FEMALE students in  Kindergarten have other mental disability or learning difficulty?'],var_name = 'district',value_name='count')
kece_meltdd.head()

In [62]:
count_di = pd.Series(kece_meltdd['count'].unique())
count_dic = count_di[1:]
count_dic.to_csv('count_dic.csv', index = False)

NameError: name 'kece_meltdd' is not defined

In [ ]:
# calculating number of ece students disagregated by grade level
kece_s = kece_student.iloc[:,46:87].sum()

kece_s

In [63]:
#nur 
knur = kece_s[:2].append(kece_s[6:20])
knur[:2].sum()
knur[[2,9]].sum()
knur.sum()

NameError: name 'kece_s' is not defined

In [ ]:
#prk 
prk = kece_s[2:4].append(kece_s[20:34])
prk.sum()#[:2].sum()
#prk[[2,9]].sum()
#prk[[8,15]].sum()

In [ ]:
kk = kece_s[4:6].append(kece_s[34:])
kk[:2].sum()

In [ ]:
#knur_male
knur = kece_s[:2].append(kece_s[6:20])
knur_m=knur[[0]].append(knur[2:9])
knur_m[:]

In [64]:
#knur_female
knur = kece_s[:2].append(kece_s[6:20])
knur_f=knur[[1]].append(knur[9:])
knur_f[:]

NameError: name 'kece_s' is not defined

In [ ]:
#kpk_male
prk = kece_s[2:4].append(kece_s[20:34])
prk_m=prk[[0]].append(prk[2:9])
prk_m

In [ ]:
#kpk_female
prk = kece_s[2:4].append(kece_s[20:34])
prk_f=prk[[1]].append(prk[9:])
prk_f

In [ ]:
#kk_male
kk = kece_s[4:6].append(kece_s[34:])
kk[[0,2,3]]

In [65]:
#kk_female
kk = kece_s[4:6].append(kece_s[34:])
kk[[1,4,5,6,7,8]]#.sum()

NameError: name 'kece_s' is not defined

In [ ]:
# ece enrollment disagregated by age and county


kece_s.head()

In [ ]:
kece_st = kece_student.iloc[:,46:87]

In [66]:
ece_asc=pd.concat([kcensus.iloc[:,[2]],kece_st],axis=1).groupby("County").sum()
ece_asc.head()

NameError: name 'kece_st' is not defined

In [ ]:
kece_repeat=kcensus.iloc[:,65:71]
kece_repeat

In [ ]:
kece_repeat=pd.concat([kcensus.iloc[:,[2,39]],kece_repeat],axis=1)

kece_repeat

In [67]:
kece_repeat_o=kece_repeat.iloc[:,:]#.head#groupby('Type of school')

kece_repeat_o.groupby('Type of school').sum()#.sum(1).sum()

NameError: name 'kece_repeat' is not defined

In [ ]:
kece_repeat_o.groupby('County').sum()#.sum(1).sum()

In [68]:
#calculating students enrollment by districts and grade

k_s = kpri_melt[(kpri_melt['district']== 'Districts in Grand Gedeh') & (kpri_melt['count']== 'Konobo')].sum()
#k_grades=
#k_s

In [69]:
kgrade1=k_s[1:-2][[0,6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120,126,132,138]]
kgrade1.sum()

521.0

In [70]:
kgrade2=k_s[1:-2][[1,7,13,19,25,31,37,43,49,55,61,67,73,79,85,91,97,103,109,115,121,127,133,139]]
kgrade2.sum()

446.0

In [71]:
kgrade3=k_s[1:-2][[2,8,14,20,26,32,38,44,50,56,62,68,74,80,86,92,98,104,110,116,122,128,134,140]]
kgrade3.sum()

420.0

In [72]:
kgrade4=k_s[1:-2][[3,9,15,21,27,33,39,45,51,57,63,69,75,81,87,93,99,105,111,117,123,129,135,141]]
kgrade4.sum()

399.0

In [73]:
kgrade5=k_s[1:-2][[4,10,16,22,28,34,40,46,52,58,64,70,76,82,88,94,100,106,112,118,124,130,136,142]]
kgrade5.sum()

261.0

In [74]:
kgrade6=k_s[1:-2][[5,11,17,23,29,35,41,47,53,59,65,71,77,83,89,95,101,107,113,119,125,131,137,143]]
kgrade6.sum()

185.0